<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Documents/Types/DocumentTypeDescription.proto

namespace Diadoc\Api\Proto\Documents\Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.Documents.Types.DetectedDocumentType</code>
 */
class DetectedDocumentType extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional string TypeNamedId = 1;</code>
     */
    protected $TypeNamedId = null;
    /**
     * Generated from protobuf field <code>optional string Function = 2;</code>
     */
    protected $Function = null;
    /**
     * Generated from protobuf field <code>optional string Version = 3;</code>
     */
    protected $Version = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $TypeNamedId
     *     @type string $Function
     *     @type string $Version
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Documents\Types\DocumentTypeDescription::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string TypeNamedId = 1;</code>
     * @return string
     */
    public function getTypeNamedId()
    {
        return isset($this->TypeNamedId) ? $this->TypeNamedId : '';
    }

    public function hasTypeNamedId()
    {
        return isset($this->TypeNamedId);
    }

    public function clearTypeNamedId()
    {
        unset($this->TypeNamedId);
    }

    /**
     * Generated from protobuf field <code>optional string TypeNamedId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTypeNamedId($var)
    {
        GPBUtil::checkString($var, True);
        $this->TypeNamedId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string Function = 2;</code>
     * @return string
     */
    public function getFunction()
    {
        return isset($this->Function) ? $this->Function : '';
    }

    public function hasFunction()
    {
        return isset($this->Function);
    }

    public function clearFunction()
    {
        unset($this->Function);
    }

    /**
     * Generated from protobuf field <code>optional string Function = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setFunction($var)
    {
        GPBUtil::checkString($var, True);
        $this->Function = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string Version = 3;</code>
     * @return string
     */
    public function getVersion()
    {
        return isset($this->Version) ? $this->Version : '';
    }

    public function hasVersion()
    {
        return isset($this->Version);
    }

    public function clearVersion()
    {
        unset($this->Version);
    }

    /**
     * Generated from protobuf field <code>optional string Version = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->Version = $var;

        return $this;
    }

}

