<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Registration/RegistrationRequest.proto

namespace GPBMetadata\Registration;

class RegistrationRequest
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xAD\x07\x0A&Registration/RegistrationRequest.proto\x12\x1DDiadoc.Api.Proto.Registration\"u\x0A\x13RegistrationRequest\x12\x1F\x0A\x12CertificateContent\x18\x01 \x01(\x0CH\x00\x88\x01\x01\x12\x17\x0A\x0AThumbprint\x18\x02 \x01(\x09H\x01\x88\x01\x01B\x15\x0A\x13_CertificateContentB\x0D\x0A\x0B_Thumbprint\"\xC7\x01\x0A\x14RegistrationResponse\x12R\x0A\x12RegistrationStatus\x18\x01 \x01(\x0E21.Diadoc.Api.Proto.Registration.RegistrationStatusH\x00\x88\x01\x01\x12\x12\x0A\x05BoxId\x18\x02 \x01(\x09H\x01\x88\x01\x01\x12\x17\x0A\x0ADataToSign\x18\x03 \x01(\x0CH\x02\x88\x01\x01B\x15\x0A\x13_RegistrationStatusB\x08\x0A\x06_BoxIdB\x0D\x0A\x0B_DataToSign\"\xCA\x01\x0A\x1ARegistrationConfirmRequest\x12\x1F\x0A\x12CertificateContent\x18\x01 \x01(\x0CH\x00\x88\x01\x01\x12\x17\x0A\x0AThumbprint\x18\x02 \x01(\x09H\x01\x88\x01\x01\x12\x17\x0A\x0ADataToSign\x18\x03 \x01(\x0CH\x02\x88\x01\x01\x12\x16\x0A\x09Signature\x18\x04 \x01(\x0CH\x03\x88\x01\x01B\x15\x0A\x13_CertificateContentB\x0D\x0A\x0B_ThumbprintB\x0D\x0A\x0B_DataToSignB\x0C\x0A\x0A_Signature*\xB0\x02\x0A\x12RegistrationStatus\x12\x0B\x0A\x07Unknown\x10\x00\x12\x12\x0A\x0EAccessIsDenied\x10\x01\x12\x1B\x0A\x17AccessRequestIsRejected\x10\x02\x12'\x0A#CertificateOwnershipProofIsRequired\x10\x03\x12\x1D\x0A\x19CertificateIsNotQualified\x10\x04\x12\x1B\x0A\x17RegistrationIsCompleted\x10\x05\x12\x1C\x0A\x18RegistrationIsInProgress\x10\x06\x12#\x0A\x1FRegistrationInBranchIsForbidden\x10\x07\x12\x1A\x0A\x16AccessRequestIsPending\x10\x08\x12\x18\x0A\x14OrganizationNotFound\x10\x09B\x1BB\x19RegistrationRequestProtosb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

