<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Employees/Employee.proto

namespace Diadoc\Api\Proto\Employees;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.Employees.EmployeePermissions</code>
 */
class EmployeePermissions extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional string UserDepartmentId = 1;</code>
     */
    protected $UserDepartmentId = null;
    /**
     * Generated from protobuf field <code>optional bool IsAdministrator = 2;</code>
     */
    protected $IsAdministrator = null;
    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.DocumentAccessLevel DocumentAccessLevel = 3 [default = UnknownDocumentAccessLevel];</code>
     */
    protected $DocumentAccessLevel = null;
    /**
     * Generated from protobuf field <code>repeated string SelectedDepartmentIds = 4;</code>
     */
    private $SelectedDepartmentIds;
    /**
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.Employees.EmployeeAction Actions = 5;</code>
     */
    private $Actions;
    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.AuthorizationPermission AuthorizationPermission = 6;</code>
     */
    protected $AuthorizationPermission = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $UserDepartmentId
     *     @type bool $IsAdministrator
     *     @type int $DocumentAccessLevel
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $SelectedDepartmentIds
     *     @type array<\Diadoc\Api\Proto\Employees\EmployeeAction>|\Google\Protobuf\Internal\RepeatedField $Actions
     *     @type \Diadoc\Api\Proto\AuthorizationPermission $AuthorizationPermission
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Employees\Employee::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string UserDepartmentId = 1;</code>
     * @return string
     */
    public function getUserDepartmentId()
    {
        return isset($this->UserDepartmentId) ? $this->UserDepartmentId : '';
    }

    public function hasUserDepartmentId()
    {
        return isset($this->UserDepartmentId);
    }

    public function clearUserDepartmentId()
    {
        unset($this->UserDepartmentId);
    }

    /**
     * Generated from protobuf field <code>optional string UserDepartmentId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUserDepartmentId($var)
    {
        GPBUtil::checkString($var, True);
        $this->UserDepartmentId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool IsAdministrator = 2;</code>
     * @return bool
     */
    public function getIsAdministrator()
    {
        return isset($this->IsAdministrator) ? $this->IsAdministrator : false;
    }

    public function hasIsAdministrator()
    {
        return isset($this->IsAdministrator);
    }

    public function clearIsAdministrator()
    {
        unset($this->IsAdministrator);
    }

    /**
     * Generated from protobuf field <code>optional bool IsAdministrator = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsAdministrator($var)
    {
        GPBUtil::checkBool($var);
        $this->IsAdministrator = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.DocumentAccessLevel DocumentAccessLevel = 3 [default = UnknownDocumentAccessLevel];</code>
     * @return int
     */
    public function getDocumentAccessLevel()
    {
        return isset($this->DocumentAccessLevel) ? $this->DocumentAccessLevel : 0;
    }

    public function hasDocumentAccessLevel()
    {
        return isset($this->DocumentAccessLevel);
    }

    public function clearDocumentAccessLevel()
    {
        unset($this->DocumentAccessLevel);
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.DocumentAccessLevel DocumentAccessLevel = 3 [default = UnknownDocumentAccessLevel];</code>
     * @param int $var
     * @return $this
     */
    public function setDocumentAccessLevel($var)
    {
        GPBUtil::checkEnum($var, \Diadoc\Api\Proto\DocumentAccessLevel::class);
        $this->DocumentAccessLevel = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string SelectedDepartmentIds = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSelectedDepartmentIds()
    {
        return $this->SelectedDepartmentIds;
    }

    /**
     * Generated from protobuf field <code>repeated string SelectedDepartmentIds = 4;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSelectedDepartmentIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->SelectedDepartmentIds = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.Employees.EmployeeAction Actions = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getActions()
    {
        return $this->Actions;
    }

    /**
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.Employees.EmployeeAction Actions = 5;</code>
     * @param array<\Diadoc\Api\Proto\Employees\EmployeeAction>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setActions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Diadoc\Api\Proto\Employees\EmployeeAction::class);
        $this->Actions = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.AuthorizationPermission AuthorizationPermission = 6;</code>
     * @return \Diadoc\Api\Proto\AuthorizationPermission|null
     */
    public function getAuthorizationPermission()
    {
        return $this->AuthorizationPermission;
    }

    public function hasAuthorizationPermission()
    {
        return isset($this->AuthorizationPermission);
    }

    public function clearAuthorizationPermission()
    {
        unset($this->AuthorizationPermission);
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.AuthorizationPermission AuthorizationPermission = 6;</code>
     * @param \Diadoc\Api\Proto\AuthorizationPermission $var
     * @return $this
     */
    public function setAuthorizationPermission($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\AuthorizationPermission::class);
        $this->AuthorizationPermission = $var;

        return $this;
    }

}

