<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Employees/EmployeeToUpdate.proto

namespace Diadoc\Proto\Employees;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.Employees.EmployeeDocumentAccessLevelPatch</code>
 */
class EmployeeDocumentAccessLevelPatch extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.DocumentAccessLevel DocumentAccessLevel = 1;</code>
     */
    protected $DocumentAccessLevel = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $DocumentAccessLevel
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Employees\EmployeeToUpdate::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.DocumentAccessLevel DocumentAccessLevel = 1;</code>
     * @return int
     */
    public function getDocumentAccessLevel()
    {
        return isset($this->DocumentAccessLevel) ? $this->DocumentAccessLevel : 0;
    }

    public function hasDocumentAccessLevel()
    {
        return isset($this->DocumentAccessLevel);
    }

    public function clearDocumentAccessLevel()
    {
        unset($this->DocumentAccessLevel);
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.DocumentAccessLevel DocumentAccessLevel = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setDocumentAccessLevel($var)
    {
        GPBUtil::checkEnum($var, \Diadoc\Api\Proto\DocumentAccessLevel::class);
        $this->DocumentAccessLevel = $var;

        return $this;
    }

}

