<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Employees/EmployeeToUpdate.proto

namespace Diadoc\Proto\Employees;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.Employees.EmployeeDepartmentPatch</code>
 */
class EmployeeDepartmentPatch extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional string DepartmentId = 1;</code>
     */
    protected $DepartmentId = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $DepartmentId
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Employees\EmployeeToUpdate::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string DepartmentId = 1;</code>
     * @return string
     */
    public function getDepartmentId()
    {
        return isset($this->DepartmentId) ? $this->DepartmentId : '';
    }

    public function hasDepartmentId()
    {
        return isset($this->DepartmentId);
    }

    public function clearDepartmentId()
    {
        unset($this->DepartmentId);
    }

    /**
     * Generated from protobuf field <code>optional string DepartmentId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDepartmentId($var)
    {
        GPBUtil::checkString($var, True);
        $this->DepartmentId = $var;

        return $this;
    }

}

