<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Employees/Employee.proto

namespace Diadoc\Api\Proto\Employees;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.Employees.EmployeeAction</code>
 */
class EmployeeAction extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional string Name = 1;</code>
     */
    protected $Name = null;
    /**
     * Generated from protobuf field <code>optional bool IsAllowed = 2;</code>
     */
    protected $IsAllowed = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Name
     *     @type bool $IsAllowed
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Employees\Employee::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string Name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return isset($this->Name) ? $this->Name : '';
    }

    public function hasName()
    {
        return isset($this->Name);
    }

    public function clearName()
    {
        unset($this->Name);
    }

    /**
     * Generated from protobuf field <code>optional string Name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->Name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool IsAllowed = 2;</code>
     * @return bool
     */
    public function getIsAllowed()
    {
        return isset($this->IsAllowed) ? $this->IsAllowed : false;
    }

    public function hasIsAllowed()
    {
        return isset($this->IsAllowed);
    }

    public function clearIsAllowed()
    {
        unset($this->IsAllowed);
    }

    /**
     * Generated from protobuf field <code>optional bool IsAllowed = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsAllowed($var)
    {
        GPBUtil::checkBool($var);
        $this->IsAllowed = $var;

        return $this;
    }

}

