<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Events/CancellationInfo.proto

namespace GPBMetadata\Events;

class CancellationInfo
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0Av\x0A\x1DEvents/CancellationInfo.proto\x12\x17Diadoc.Api.Proto.Events\"\"\x0A\x10CancellationInfo\x12\x0E\x0A\x06Author\x18\x01 \x01(\x09B\x18B\x16CancellationInfoProtos"
        , true);

        static::$is_initialized = true;
    }
}

