<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Events/DiadocCounteragent-GetApi.proto

namespace GPBMetadata\Events;

class DiadocCounteragentGetApi
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Counteragent::initOnce();
        \GPBMetadata\TotalCountType::initOnce();
        \GPBMetadata\DocumentId::initOnce();
        \GPBMetadata\Events\CounteragentEventType::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xD1\x06\x0A&Events/DiadocCounteragent-GetApi.proto\x12\x17Diadoc.Api.Proto.Events\x1A\x14TotalCountType.proto\x1A\x10DocumentId.proto\x1A\"Events/CounteragentEventType.proto\"\xA7\x01\x0A\x18BoxCounteragentEventList\x12=\x0A\x06Events\x18\x01 \x03(\x0B2-.Diadoc.Api.Proto.Events.BoxCounteragentEvent\x12\x12\x0A\x0ATotalCount\x18\x02 \x01(\x05\x128\x0A\x0ETotalCountType\x18\x03 \x01(\x0E2 .Diadoc.Api.Proto.TotalCountType\"\xBE\x01\x0A\x14BoxCounteragentEvent\x12\x0F\x0A\x07EventId\x18\x01 \x01(\x09\x12?\x0A\x0CCounteragent\x18\x02 \x01(\x0B2).Diadoc.Api.Proto.Events.CounteragentInfo\x12\x10\x0A\x08IndexKey\x18\x03 \x01(\x09\x12B\x0A\x0AEventTypes\x18\x04 \x03(\x0E2..Diadoc.Api.Proto.Events.CounteragentEventType\"\xB3\x02\x0A\x10CounteragentInfo\x12\x19\x0A\x11CounteragentBoxId\x18\x01 \x01(\x09\x124\x0A\x06Status\x18\x02 \x01(\x0E2\$.Diadoc.Api.Proto.CounteragentStatus\x12\x1B\x0A\x13EventTimestampTicks\x18\x03 \x01(\x10\x12\x18\x0A\x10LastEventComment\x18\x04 \x01(\x09\x12\x1F\x0A\x17MessageFromCounteragent\x18\x05 \x01(\x09\x12\x1D\x0A\x15MessageToCounteragent\x18\x06 \x01(\x09\x12:\x0A\x14InvitationDocumentId\x18\x07 \x01(\x0B2\x1C.Diadoc.Api.Proto.DocumentId\x12\x1B\x0A\x13CounteragentGroupId\x18\x08 \x01(\x09B!B\x1FDiadocCounteragent_GetApiProtos"
        , true);

        static::$is_initialized = true;
    }
}

