<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Events/PowerOfAttorneyToPost.proto

namespace GPBMetadata\Events;

class PowerOfAttorneyToPost
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\PowersOfAttorney\PowerOfAttorney::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xA9\x03\x0A\"Events/PowerOfAttorneyToPost.proto\x12\x17Diadoc.Api.Proto.Events\"\xCA\x02\x0A\x15PowerOfAttorneyToPost\x12H\x0A\x06FullId\x18\x01 \x01(\x0B28.Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyFullId\x12\x12\x0A\x0AUseDefault\x18\x02 \x01(\x08\x12P\x0A\x07Content\x18\x03 \x01(\x0B2?.Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneySignedContent\x12\x12\x0A\x0ASendAsFile\x18\x04 \x01(\x08\x12Q\x0A\x08Contents\x18\x05 \x03(\x0B2?.Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneySignedContent\x12\x1A\x0A\x12UseDocumentContent\x18\x06 \x01(\x08B\x1DB\x1BPowerOfAttorneyToPostProtos"
        , true);

        static::$is_initialized = true;
    }
}

