<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Events/PowerOfAttorneyInfo.proto

namespace GPBMetadata\Events;

class PowerOfAttorneyInfo
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\PowersOfAttorney\PowerOfAttorney::initOnce();
        \GPBMetadata\PowersOfAttorney\PowerOfAttorneyValidation::initOnce();
        \GPBMetadata\RoamingSendingStatus::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xFF\x03\x0A Events/PowerOfAttorneyInfo.proto\x12\x17Diadoc.Api.Proto.Events\x1A0PowersOfAttorney/PowerOfAttorneyValidation.proto\x1A\x1ARoamingSendingStatus.proto\"\xD6\x02\x0A\x13PowerOfAttorneyInfo\x12H\x0A\x06FullId\x18\x01 \x01(\x0B28.Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyFullId\x12R\x0A\x06Status\x18\x02 \x01(\x0B2B.Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyValidationStatus\x12D\x0A\x14RoamingSendingStatus\x18\x03 \x01(\x0B2&.Diadoc.Api.Proto.RoamingSendingStatus\x12[\x0A\x0BSendingType\x18\x04 \x01(\x0E2=.Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneySendingType:\x07UnknownB\x1BB\x19PowerOfAttorneyInfoProtos"
        , true);

        static::$is_initialized = true;
    }
}

