<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Events/ResolutionInfo.proto

namespace GPBMetadata\Events;

class ResolutionInfo
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\ResolutionType::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xDC\x01\x0A\x1BEvents/ResolutionInfo.proto\x12\x17Diadoc.Api.Proto.Events\"\x8B\x01\x0A\x0EResolutionInfo\x12O\x0A\x0EResolutionType\x18\x01 \x01(\x0E2 .Diadoc.Api.Proto.ResolutionType:\x15UnknownResolutionType\x12\x0E\x0A\x06Author\x18\x02 \x01(\x09\x12\x18\x0A\x10InitialRequestId\x18\x03 \x01(\x09B\x16B\x14ResolutionInfoProtos"
        , true);

        static::$is_initialized = true;
    }
}

