<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Events/ResolutionRequestInfo.proto

namespace GPBMetadata\Events;

class ResolutionRequestInfo
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\ResolutionAction::initOnce();
        \GPBMetadata\ResolutionTarget::initOnce();
        \GPBMetadata\ResolutionRequestType::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\x96\x03\x0A\"Events/ResolutionRequestInfo.proto\x12\x17Diadoc.Api.Proto.Events\x1A\x16ResolutionTarget.proto\x1A\x1BResolutionRequestType.proto\"\x82\x02\x0A\x15ResolutionRequestInfo\x12Z\x0A\x0BRequestType\x18\x01 \x01(\x0E2'.Diadoc.Api.Proto.ResolutionRequestType:\x1CUnknownResolutionRequestType\x12\x0E\x0A\x06Author\x18\x02 \x01(\x09\x122\x0A\x06Target\x18\x03 \x01(\x0B2\".Diadoc.Api.Proto.ResolutionTarget\x12\x14\x0A\x0CResolvedWith\x18\x04 \x01(\x09\x123\x0A\x07Actions\x18\x05 \x03(\x0E2\".Diadoc.Api.Proto.ResolutionActionB\x1DB\x1BResolutionRequestInfoProtos"
        , true);

        static::$is_initialized = true;
    }
}

