<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Events/ResolutionRouteInfo.proto

namespace GPBMetadata\Events;

class ResolutionRouteInfo
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xD9\x01\x0A Events/ResolutionRouteInfo.proto\x12\x17Diadoc.Api.Proto.Events\"@\x0A\x1DResolutionRouteAssignmentInfo\x12\x0F\x0A\x07RouteId\x18\x01 \x01(\x09\x12\x0E\x0A\x06Author\x18\x02 \x01(\x09\"=\x0A\x1AResolutionRouteRemovalInfo\x12\x0F\x0A\x07RouteId\x18\x01 \x01(\x09\x12\x0E\x0A\x06Author\x18\x02 \x01(\x09B\x1BB\x19ResolutionRouteInfoProtos"
        , true);

        static::$is_initialized = true;
    }
}

