<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Events/RevocationRequestInfo.proto

namespace GPBMetadata\Events;

class RevocationRequestInfo
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\x8D\x01\x0A\"Events/RevocationRequestInfo.proto\x12\x17Diadoc.Api.Proto.Events\"/\x0A\x15RevocationRequestInfo\x12\x16\x0A\x0EInitiatorBoxId\x18\x01 \x01(\x09B\x1DB\x1BRevocationRequestInfoProtos"
        , true);

        static::$is_initialized = true;
    }
}

