<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Documents/DocumentProtocol.proto

namespace Diadoc\Api\Proto\Documents;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.Documents.DocumentProtocol</code>
 */
class DocumentProtocol extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional bytes PrintForm = 1;</code>
     */
    protected $PrintForm = null;
    /**
     * Generated from protobuf field <code>optional bytes Signature = 2;</code>
     */
    protected $Signature = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $PrintForm
     *     @type string $Signature
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Documents\DocumentProtocol::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional bytes PrintForm = 1;</code>
     * @return string
     */
    public function getPrintForm()
    {
        return isset($this->PrintForm) ? $this->PrintForm : '';
    }

    public function hasPrintForm()
    {
        return isset($this->PrintForm);
    }

    public function clearPrintForm()
    {
        unset($this->PrintForm);
    }

    /**
     * Generated from protobuf field <code>optional bytes PrintForm = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPrintForm($var)
    {
        GPBUtil::checkString($var, False);
        $this->PrintForm = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bytes Signature = 2;</code>
     * @return string
     */
    public function getSignature()
    {
        return isset($this->Signature) ? $this->Signature : '';
    }

    public function hasSignature()
    {
        return isset($this->Signature);
    }

    public function clearSignature()
    {
        unset($this->Signature);
    }

    /**
     * Generated from protobuf field <code>optional bytes Signature = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSignature($var)
    {
        GPBUtil::checkString($var, False);
        $this->Signature = $var;

        return $this;
    }

}

