<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Employees/PowersOfAttorney/EmployeePowerOfAttorney.proto

namespace GPBMetadata\Employees\PowersOfAttorney;

class EmployeePowerOfAttorney
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\PowersOfAttorney\PowerOfAttorney::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xCE\x04\x0A8Employees/PowersOfAttorney/EmployeePowerOfAttorney.proto\x12+Diadoc.Api.Proto.Employees.PowersOfAttorney\"}\x0A\x1BEmployeePowerOfAttorneyList\x12^\x0A\x10PowersOfAttorney\x18\x01 \x03(\x0B2D.Diadoc.Api.Proto.Employees.PowersOfAttorney.EmployeePowerOfAttorney\"y\x0A\x17EmployeePowerOfAttorney\x12K\x0A\x0FPowerOfAttorney\x18\x01 \x01(\x0B22.Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorney\x12\x11\x0A\x09IsDefault\x18\x02 \x01(\x08\"\x8D\x01\x0A\x1FEmployeePowerOfAttorneyToUpdate\x12j\x0A\x0EIsDefaultPatch\x18\x01 \x01(\x0B2R.Diadoc.Api.Proto.Employees.PowersOfAttorney.EmployeePowerOfAttorneyIsDefaultPatch\":\x0A%EmployeePowerOfAttorneyIsDefaultPatch\x12\x11\x0A\x09IsDefault\x18\x01 \x01(\x08B\x1FB\x1DEmployeePowerOfAttorneyProtos"
        , true);

        static::$is_initialized = true;
    }
}

