<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Documents/Types/DocumentTypeDescriptionV2.proto

namespace Diadoc\Proto\Documents\Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.Documents.Types.DocumentVersionV2</code>
 */
class DocumentVersionV2 extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional string Version = 1;</code>
     */
    protected $Version = null;
    /**
     * Generated from protobuf field <code>optional bool SupportsContentPatching = 2;</code>
     */
    protected $SupportsContentPatching = null;
    /**
     * Generated from protobuf field <code>optional bool SupportsEncrypting = 3;</code>
     */
    protected $SupportsEncrypting = null;
    /**
     * Generated from protobuf field <code>optional bool SupportsPredefinedRecipientTitle = 7;</code>
     */
    protected $SupportsPredefinedRecipientTitle = null;
    /**
     * Generated from protobuf field <code>optional bool SupportsAmendmentRequest = 8;</code>
     */
    protected $SupportsAmendmentRequest = null;
    /**
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.Documents.Types.DocumentTitleV2 Titles = 4;</code>
     */
    private $Titles;
    /**
     * Generated from protobuf field <code>optional bool IsActual = 5;</code>
     */
    protected $IsActual = null;
    /**
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.Documents.Types.DocumentWorkflowV2 Workflows = 6;</code>
     */
    private $Workflows;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Version
     *     @type bool $SupportsContentPatching
     *     @type bool $SupportsEncrypting
     *     @type bool $SupportsPredefinedRecipientTitle
     *     @type bool $SupportsAmendmentRequest
     *     @type array<\Diadoc\Api\Proto\Documents\Types\DocumentTitleV2>|\Google\Protobuf\Internal\RepeatedField $Titles
     *     @type bool $IsActual
     *     @type array<\Diadoc\Api\Proto\Documents\Types\DocumentWorkflowV2>|\Google\Protobuf\Internal\RepeatedField $Workflows
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Documents\Types\DocumentTypeDescriptionV2::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string Version = 1;</code>
     * @return string
     */
    public function getVersion()
    {
        return isset($this->Version) ? $this->Version : '';
    }

    public function hasVersion()
    {
        return isset($this->Version);
    }

    public function clearVersion()
    {
        unset($this->Version);
    }

    /**
     * Generated from protobuf field <code>optional string Version = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->Version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool SupportsContentPatching = 2;</code>
     * @return bool
     */
    public function getSupportsContentPatching()
    {
        return isset($this->SupportsContentPatching) ? $this->SupportsContentPatching : false;
    }

    public function hasSupportsContentPatching()
    {
        return isset($this->SupportsContentPatching);
    }

    public function clearSupportsContentPatching()
    {
        unset($this->SupportsContentPatching);
    }

    /**
     * Generated from protobuf field <code>optional bool SupportsContentPatching = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setSupportsContentPatching($var)
    {
        GPBUtil::checkBool($var);
        $this->SupportsContentPatching = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool SupportsEncrypting = 3;</code>
     * @return bool
     */
    public function getSupportsEncrypting()
    {
        return isset($this->SupportsEncrypting) ? $this->SupportsEncrypting : false;
    }

    public function hasSupportsEncrypting()
    {
        return isset($this->SupportsEncrypting);
    }

    public function clearSupportsEncrypting()
    {
        unset($this->SupportsEncrypting);
    }

    /**
     * Generated from protobuf field <code>optional bool SupportsEncrypting = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setSupportsEncrypting($var)
    {
        GPBUtil::checkBool($var);
        $this->SupportsEncrypting = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool SupportsPredefinedRecipientTitle = 7;</code>
     * @return bool
     */
    public function getSupportsPredefinedRecipientTitle()
    {
        return isset($this->SupportsPredefinedRecipientTitle) ? $this->SupportsPredefinedRecipientTitle : false;
    }

    public function hasSupportsPredefinedRecipientTitle()
    {
        return isset($this->SupportsPredefinedRecipientTitle);
    }

    public function clearSupportsPredefinedRecipientTitle()
    {
        unset($this->SupportsPredefinedRecipientTitle);
    }

    /**
     * Generated from protobuf field <code>optional bool SupportsPredefinedRecipientTitle = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setSupportsPredefinedRecipientTitle($var)
    {
        GPBUtil::checkBool($var);
        $this->SupportsPredefinedRecipientTitle = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool SupportsAmendmentRequest = 8;</code>
     * @return bool
     */
    public function getSupportsAmendmentRequest()
    {
        return isset($this->SupportsAmendmentRequest) ? $this->SupportsAmendmentRequest : false;
    }

    public function hasSupportsAmendmentRequest()
    {
        return isset($this->SupportsAmendmentRequest);
    }

    public function clearSupportsAmendmentRequest()
    {
        unset($this->SupportsAmendmentRequest);
    }

    /**
     * Generated from protobuf field <code>optional bool SupportsAmendmentRequest = 8;</code>
     * @param bool $var
     * @return $this
     */
    public function setSupportsAmendmentRequest($var)
    {
        GPBUtil::checkBool($var);
        $this->SupportsAmendmentRequest = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.Documents.Types.DocumentTitleV2 Titles = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTitles()
    {
        return $this->Titles;
    }

    /**
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.Documents.Types.DocumentTitleV2 Titles = 4;</code>
     * @param array<\Diadoc\Api\Proto\Documents\Types\DocumentTitleV2>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTitles($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Diadoc\Api\Proto\Documents\Types\DocumentTitleV2::class);
        $this->Titles = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool IsActual = 5;</code>
     * @return bool
     */
    public function getIsActual()
    {
        return isset($this->IsActual) ? $this->IsActual : false;
    }

    public function hasIsActual()
    {
        return isset($this->IsActual);
    }

    public function clearIsActual()
    {
        unset($this->IsActual);
    }

    /**
     * Generated from protobuf field <code>optional bool IsActual = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsActual($var)
    {
        GPBUtil::checkBool($var);
        $this->IsActual = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.Documents.Types.DocumentWorkflowV2 Workflows = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getWorkflows()
    {
        return $this->Workflows;
    }

    /**
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.Documents.Types.DocumentWorkflowV2 Workflows = 6;</code>
     * @param array<\Diadoc\Api\Proto\Documents\Types\DocumentWorkflowV2>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setWorkflows($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Diadoc\Api\Proto\Documents\Types\DocumentWorkflowV2::class);
        $this->Workflows = $arr;

        return $this;
    }

}

