<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Documents/Types/DocumentTypeDescriptionV2.proto

namespace Diadoc\Api\Proto\Documents\Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.Documents.Types.DocumentMetadataItemV2</code>
 */
class DocumentMetadataItemV2 extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional string Id = 1;</code>
     */
    protected $Id = null;
    /**
     * Generated from protobuf field <code>optional int32 Type = 2;</code>
     */
    protected $Type = null;
    /**
     * Generated from protobuf field <code>optional bool IsRequired = 3;</code>
     */
    protected $IsRequired = null;
    /**
     * Generated from protobuf field <code>optional int32 Source = 4;</code>
     */
    protected $Source = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Id
     *     @type int $Type
     *     @type bool $IsRequired
     *     @type int $Source
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Documents\Types\DocumentTypeDescriptionV2::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string Id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return isset($this->Id) ? $this->Id : '';
    }

    public function hasId()
    {
        return isset($this->Id);
    }

    public function clearId()
    {
        unset($this->Id);
    }

    /**
     * Generated from protobuf field <code>optional string Id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->Id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 Type = 2;</code>
     * @return int
     */
    public function getType()
    {
        return isset($this->Type) ? $this->Type : 0;
    }

    public function hasType()
    {
        return isset($this->Type);
    }

    public function clearType()
    {
        unset($this->Type);
    }

    /**
     * Generated from protobuf field <code>optional int32 Type = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkInt32($var);
        $this->Type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool IsRequired = 3;</code>
     * @return bool
     */
    public function getIsRequired()
    {
        return isset($this->IsRequired) ? $this->IsRequired : false;
    }

    public function hasIsRequired()
    {
        return isset($this->IsRequired);
    }

    public function clearIsRequired()
    {
        unset($this->IsRequired);
    }

    /**
     * Generated from protobuf field <code>optional bool IsRequired = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsRequired($var)
    {
        GPBUtil::checkBool($var);
        $this->IsRequired = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 Source = 4;</code>
     * @return int
     */
    public function getSource()
    {
        return isset($this->Source) ? $this->Source : 0;
    }

    public function hasSource()
    {
        return isset($this->Source);
    }

    public function clearSource()
    {
        unset($this->Source);
    }

    /**
     * Generated from protobuf field <code>optional int32 Source = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setSource($var)
    {
        GPBUtil::checkInt32($var);
        $this->Source = $var;

        return $this;
    }

}

