<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Documents/Types/DocumentTypeDescriptionV2.proto

namespace Diadoc\Proto\Documents\Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.Documents.Types.DocumentWorkflowV2</code>
 */
class DocumentWorkflowV2 extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional int32 Id = 1;</code>
     */
    protected $Id = null;
    /**
     * Generated from protobuf field <code>optional bool IsDefault = 2;</code>
     */
    protected $IsDefault = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $Id
     *     @type bool $IsDefault
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Documents\Types\DocumentTypeDescriptionV2::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional int32 Id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return isset($this->Id) ? $this->Id : 0;
    }

    public function hasId()
    {
        return isset($this->Id);
    }

    public function clearId()
    {
        unset($this->Id);
    }

    /**
     * Generated from protobuf field <code>optional int32 Id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->Id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool IsDefault = 2;</code>
     * @return bool
     */
    public function getIsDefault()
    {
        return isset($this->IsDefault) ? $this->IsDefault : false;
    }

    public function hasIsDefault()
    {
        return isset($this->IsDefault);
    }

    public function clearIsDefault()
    {
        unset($this->IsDefault);
    }

    /**
     * Generated from protobuf field <code>optional bool IsDefault = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsDefault($var)
    {
        GPBUtil::checkBool($var);
        $this->IsDefault = $var;

        return $this;
    }

}

