<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: CounteragentGroups/CounteragentGroupToCreate.proto

namespace GPBMetadata\CounteragentGroups;

class CounteragentGroupToCreate
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\CounteragentGroups\DepartmentsInGroup::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xF5\x01\x0A2CounteragentGroups/CounteragentGroupToCreate.proto\x12#Diadoc.Api.Proto.CounteragentGroups\"w\x0A\x19CounteragentGroupToCreate\x12\x0C\x0A\x04Name\x18\x01 \x01(\x09\x12L\x0A\x0BDepartments\x18\x02 \x01(\x0B27.Diadoc.Api.Proto.CounteragentGroups.DepartmentsInGroupB!B\x1FCounteragentGroupToCreateProtos"
        , true);

        static::$is_initialized = true;
    }
}

