<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: CounteragentGroups/CounteragentGroupToUpdate.proto

namespace GPBMetadata\CounteragentGroups;

class CounteragentGroupToUpdate
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\CounteragentGroups\DepartmentsInGroup::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\x93\x03\x0A2CounteragentGroups/CounteragentGroupToUpdate.proto\x12#Diadoc.Api.Proto.CounteragentGroups\"\x8A\x01\x0A\x19CounteragentGroupToUpdate\x12\x0C\x0A\x04Name\x18\x01 \x01(\x09\x12_\x0A\x10GroupDepartments\x18\x02 \x01(\x0B2E.Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupDepartmentPatch\"\x87\x01\x0A CounteragentGroupDepartmentPatch\x12\x15\x0A\x0DAnyDepartment\x18\x01 \x01(\x08\x12L\x0A\x0BDepartments\x18\x02 \x01(\x0B27.Diadoc.Api.Proto.CounteragentGroups.DepartmentsInGroupB!B\x1FCounteragentGroupToUpdateProtos"
        , true);

        static::$is_initialized = true;
    }
}

