<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: CounteragentGroups/CounteragentGroup.proto

namespace GPBMetadata\CounteragentGroups;

class CounteragentGroup
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\CounteragentGroups\DepartmentsInGroup::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xF1\x02\x0A*CounteragentGroups/CounteragentGroup.proto\x12#Diadoc.Api.Proto.CounteragentGroups\"\x8C\x01\x0A\x11CounteragentGroup\x12\x1B\x0A\x13CounteragentGroupId\x18\x01 \x01(\x09\x12\x0C\x0A\x04Name\x18\x02 \x01(\x09\x12L\x0A\x0BDepartments\x18\x03 \x01(\x0B27.Diadoc.Api.Proto.CounteragentGroups.DepartmentsInGroup\"t\x0A\x16CounteragentGroupsList\x12F\x0A\x06Groups\x18\x01 \x03(\x0B26.Diadoc.Api.Proto.CounteragentGroups.CounteragentGroup\x12\x12\x0A\x0ATotalCount\x18\x02 \x01(\x05B\x19B\x17CounteragentGroupProtos"
        , true);

        static::$is_initialized = true;
    }
}

