<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: CounteragentGroups/CounteragentFromGroupResponse.proto

namespace GPBMetadata\CounteragentGroups;

class CounteragentFromGroupResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xEB\x01\x0A6CounteragentGroups/CounteragentFromGroupResponse.proto\x12#Diadoc.Api.Proto.CounteragentGroups\"e\x0A\x1DCounteragentFromGroupResponse\x12\x19\x0A\x11CounteragentBoxId\x18\x01 \x03(\x09\x12\x12\x0A\x0ATotalCount\x18\x02 \x01(\x05\x12\x15\x0A\x0DAfterIndexKey\x18\x03 \x01(\x09B%B#CounteragentFromGroupResponseProtos"
        , true);

        static::$is_initialized = true;
    }
}

