<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: CounteragentGroups/DepartmentsInGroup.proto

namespace GPBMetadata\CounteragentGroups;

class DepartmentsInGroup
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\x9B\x01\x0A+CounteragentGroups/DepartmentsInGroup.proto\x12#Diadoc.Api.Proto.CounteragentGroups\"+\x0A\x12DepartmentsInGroup\x12\x15\x0A\x0DDepartmentIds\x18\x01 \x03(\x09B\x1AB\x18DepartmentsInGroupProtos"
        , true);

        static::$is_initialized = true;
    }
}

