<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Forwarding/ForwardingApi.proto

namespace Diadoc\Api\Proto\Forwarding;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.Forwarding.ForwardDocumentRequest</code>
 */
class ForwardDocumentRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional string ToBoxId = 1;</code>
     */
    protected $ToBoxId = null;
    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.DocumentId DocumentId = 2;</code>
     */
    protected $DocumentId = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $ToBoxId
     *     @type \Diadoc\Api\Proto\DocumentId $DocumentId
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Forwarding\ForwardingApi::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string ToBoxId = 1;</code>
     * @return string
     */
    public function getToBoxId()
    {
        return isset($this->ToBoxId) ? $this->ToBoxId : '';
    }

    public function hasToBoxId()
    {
        return isset($this->ToBoxId);
    }

    public function clearToBoxId()
    {
        unset($this->ToBoxId);
    }

    /**
     * Generated from protobuf field <code>optional string ToBoxId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setToBoxId($var)
    {
        GPBUtil::checkString($var, True);
        $this->ToBoxId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.DocumentId DocumentId = 2;</code>
     * @return \Diadoc\Api\Proto\DocumentId|null
     */
    public function getDocumentId()
    {
        return $this->DocumentId;
    }

    public function hasDocumentId()
    {
        return isset($this->DocumentId);
    }

    public function clearDocumentId()
    {
        unset($this->DocumentId);
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.DocumentId DocumentId = 2;</code>
     * @param \Diadoc\Api\Proto\DocumentId $var
     * @return $this
     */
    public function setDocumentId($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\DocumentId::class);
        $this->DocumentId = $var;

        return $this;
    }

}

