<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Employees/PowersOfAttorney/EmployeePowerOfAttorney.proto

namespace Diadoc\Proto\Employees\PowersOfAttorney;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.Employees.PowersOfAttorney.EmployeePowerOfAttorneyIsDefaultPatch</code>
 */
class EmployeePowerOfAttorneyIsDefaultPatch extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional bool IsDefault = 1;</code>
     */
    protected $IsDefault = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $IsDefault
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Employees\PowersOfAttorney\EmployeePowerOfAttorney::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional bool IsDefault = 1;</code>
     * @return bool
     */
    public function getIsDefault()
    {
        return isset($this->IsDefault) ? $this->IsDefault : false;
    }

    public function hasIsDefault()
    {
        return isset($this->IsDefault);
    }

    public function clearIsDefault()
    {
        unset($this->IsDefault);
    }

    /**
     * Generated from protobuf field <code>optional bool IsDefault = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsDefault($var)
    {
        GPBUtil::checkBool($var);
        $this->IsDefault = $var;

        return $this;
    }

}

