<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Events/CancellationInfo.proto

namespace Diadoc\Proto\Events;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.Events.CancellationInfo</code>
 */
class CancellationInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional string Author = 1;</code>
     */
    protected $Author = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Author
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Events\CancellationInfo::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string Author = 1;</code>
     * @return string
     */
    public function getAuthor()
    {
        return isset($this->Author) ? $this->Author : '';
    }

    public function hasAuthor()
    {
        return isset($this->Author);
    }

    public function clearAuthor()
    {
        unset($this->Author);
    }

    /**
     * Generated from protobuf field <code>optional string Author = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAuthor($var)
    {
        GPBUtil::checkString($var, True);
        $this->Author = $var;

        return $this;
    }

}

