<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Events/RevocationRequestInfo.proto

namespace Diadoc\Api\Proto\Events;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.Events.RevocationRequestInfo</code>
 */
class RevocationRequestInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional string InitiatorBoxId = 1;</code>
     */
    protected $InitiatorBoxId = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $InitiatorBoxId
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Events\RevocationRequestInfo::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string InitiatorBoxId = 1;</code>
     * @return string
     */
    public function getInitiatorBoxId()
    {
        return isset($this->InitiatorBoxId) ? $this->InitiatorBoxId : '';
    }

    public function hasInitiatorBoxId()
    {
        return isset($this->InitiatorBoxId);
    }

    public function clearInitiatorBoxId()
    {
        unset($this->InitiatorBoxId);
    }

    /**
     * Generated from protobuf field <code>optional string InitiatorBoxId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setInitiatorBoxId($var)
    {
        GPBUtil::checkString($var, True);
        $this->InitiatorBoxId = $var;

        return $this;
    }

}

