<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: AcquireCounteragent.proto

namespace GPBMetadata;

class AcquireCounteragent
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Events\DiadocMessagePostApi::initOnce();
        \GPBMetadata\DocumentId::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xF2\x04\x0A\x19AcquireCounteragent.proto\x12\x10Diadoc.Api.Proto\x1A\x10DocumentId.proto\"\xA8\x01\x0A\x1AAcquireCounteragentRequest\x12\x0D\x0A\x05OrgId\x18\x01 \x01(\x09\x12\x0B\x0A\x03Inn\x18\x02 \x01(\x09\x12\x1D\x0A\x15MessageToCounteragent\x18\x03 \x01(\x09\x12@\x0A\x12InvitationDocument\x18\x04 \x01(\x0B2\$.Diadoc.Api.Proto.InvitationDocument\x12\x0D\x0A\x05BoxId\x18\x05 \x01(\x09\"\x96\x01\x0A\x12InvitationDocument\x12=\x0A\x0DSignedContent\x18\x01 \x01(\x0B2&.Diadoc.Api.Proto.Events.SignedContent\x12\x10\x0A\x08FileName\x18\x02 \x01(\x09\x12!\x0A\x12SignatureRequested\x18\x03 \x01(\x08:\x05false\x12\x0C\x0A\x04Type\x18\x04 \x01(\x09\"f\x0A\x19AcquireCounteragentResult\x12\x0D\x0A\x05OrgId\x18\x01 \x01(\x09\x12:\x0A\x14InvitationDocumentId\x18\x02 \x01(\x0B2\x1C.Diadoc.Api.Proto.DocumentId\"h\x0A\x1BAcquireCounteragentResultV2\x12\x0D\x0A\x05BoxId\x18\x01 \x01(\x09\x12:\x0A\x14InvitationDocumentId\x18\x02 \x01(\x0B2\x1C.Diadoc.Api.Proto.DocumentIdB\x1BB\x19AcquireCounteragentProtos"
        , true);

        static::$is_initialized = true;
    }
}

