<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: CertificateInfo.proto

namespace GPBMetadata;

class CertificateInfo
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xB4\x01\x0A\x15CertificateInfo.proto\x12\x10Diadoc.Api.Proto\"p\x0A\x0FCertificateInfo\x12\x12\x0A\x0AThumbprint\x18\x01 \x01(\x09\x12\x11\x0A\x09ValidFrom\x18\x02 \x01(\x10\x12\x0F\x0A\x07ValidTo\x18\x03 \x01(\x10\x12\x18\x0A\x10OrganizationName\x18\x04 \x01(\x09\x12\x0B\x0A\x03Inn\x18\x05 \x01(\x09B\x17B\x15CertificateInfoProtos"
        , true);

        static::$is_initialized = true;
    }
}

