<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: CertificateList.proto

namespace GPBMetadata;

class CertificateList
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\CertificateInfoV2::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\x90\x01\x0A\x15CertificateList.proto\x12\x10Diadoc.Api.Proto\"L\x0A\x0FCertificateList\x129\x0A\x0CCertificates\x18\x01 \x03(\x0B2#.Diadoc.Api.Proto.CertificateInfoV2B\x17B\x15CertificateListProtos"
        , true);

        static::$is_initialized = true;
    }
}

