<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: CloudSign.proto

namespace GPBMetadata;

class CloudSign
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\ContentV2::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\x87\x03\x0A\x0FCloudSign.proto\x12\x10Diadoc.Api.Proto\"B\x0A\x10CloudSignRequest\x12.\x0A\x05Files\x18\x01 \x03(\x0B2\x1F.Diadoc.Api.Proto.CloudSignFile\"P\x0A\x0DCloudSignFile\x12-\x0A\x07Content\x18\x01 \x01(\x0B2\x1C.Diadoc.Api.Proto.Content_v2\x12\x10\x0A\x08FileName\x18\x02 \x01(\x09\" \x0A\x0FCloudSignResult\x12\x0D\x0A\x05Token\x18\x01 \x01(\x09\"J\x0A\x16CloudSignConfirmResult\x120\x0A\x0ASignatures\x18\x01 \x03(\x0B2\x1C.Diadoc.Api.Proto.Content_v2\"K\x0A\x16AutosignReceiptsResult\x12\x1B\x0A\x13SignedReceiptsCount\x18\x01 \x01(\x03\x12\x14\x0A\x0CNextBatchKey\x18\x02 \x01(\x09B\x11B\x0FCloudSignProtos"
        , true);

        static::$is_initialized = true;
    }
}

