<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Content.proto

namespace GPBMetadata;

class Content
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0AY\x0A\x0DContent.proto\x12\x10Diadoc.Api.Proto\"%\x0A\x07Content\x12\x0C\x0A\x04Size\x18\x01 \x01(\x0F\x12\x0C\x0A\x04Data\x18\x02 \x01(\x0CB\x0FB\x0DContentProtos"
        , true);

        static::$is_initialized = true;
    }
}

