<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Content_v3.proto

namespace GPBMetadata;

class ContentV3
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\DocumentId::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xB6\x01\x0A\x10Content_v3.proto\x12\x10Diadoc.Api.Proto\"|\x0A\x0AContent_v3\x12\x0F\x0A\x07Content\x18\x01 \x01(\x0C\x12\x13\x0A\x0BNameOnShelf\x18\x02 \x01(\x09\x12.\x0A\x08EntityId\x18\x03 \x01(\x0B2\x1C.Diadoc.Api.Proto.DocumentId\x12\x18\x0A\x10PatchedContentId\x18\x04 \x01(\x09B\x12B\x10Content_v3Protos"
        , true);

        static::$is_initialized = true;
    }
}

