<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: CustomPrintFormDetection.proto

namespace GPBMetadata;

class CustomPrintFormDetection
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\DocumentId::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\x85\x03\x0A\x1ECustomPrintFormDetection.proto\x12\x10Diadoc.Api.Proto\"T\x0A\x1FCustomPrintFormDetectionRequest\x121\x0A\x0BDocumentIds\x18\x01 \x03(\x0B2\x1C.Diadoc.Api.Proto.DocumentId\"e\x0A\x1ECustomPrintFormDetectionResult\x12C\x0A\x05Items\x18\x01 \x03(\x0B24.Diadoc.Api.Proto.CustomPrintFormDetectionItemResult\"r\x0A\"CustomPrintFormDetectionItemResult\x120\x0A\x0ADocumentId\x18\x01 \x01(\x0B2\x1C.Diadoc.Api.Proto.DocumentId\x12\x1A\x0A\x12HasCustomPrintForm\x18\x02 \x01(\x08B B\x1ECustomPrintFormDetectionProtos"
        , true);

        static::$is_initialized = true;
    }
}

