<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: DocflowStatusV3.proto

namespace GPBMetadata;

class DocflowStatusV3
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\PowersOfAttorney\PowerOfAttorneyValidation::initOnce();
        \GPBMetadata\RoamingSendingStatus::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xE7\x03\x0A\x15DocflowStatusV3.proto\x12\x10Diadoc.Api.Proto\x1A\x1ARoamingSendingStatus.proto\"\xC8\x02\x0A\x0FDocflowStatusV3\x12=\x0A\x0DPrimaryStatus\x18\x01 \x01(\x0B2&.Diadoc.Api.Proto.DocflowStatusModelV3\x12?\x0A\x0FSecondaryStatus\x18\x02 \x01(\x0B2&.Diadoc.Api.Proto.DocflowStatusModelV3\x12h\x0A\x1CPowerOfAttorneyGeneralStatus\x18\x03 \x01(\x0B2B.Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyValidationStatus\x12K\x0A\x1BGeneralRoamingSendingStatus\x18\x04 \x01(\x0B2&.Diadoc.Api.Proto.RoamingSendingStatus\"<\x0A\x14DocflowStatusModelV3\x12\x10\x0A\x08Severity\x18\x01 \x01(\x09\x12\x12\x0A\x0AStatusText\x18\x02 \x01(\x09B\x17B\x15DocflowStatusV3Protos"
        , true);

        static::$is_initialized = true;
    }
}

