<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ForwardDocumentEvent.proto

namespace GPBMetadata;

class ForwardDocumentEvent
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Timestamp::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xA5\x01\x0A\x1AForwardDocumentEvent.proto\x12\x10Diadoc.Api.Proto\"W\x0A\x14ForwardDocumentEvent\x12.\x0A\x09Timestamp\x18\x01 \x01(\x0B2\x1B.Diadoc.Api.Proto.Timestamp\x12\x0F\x0A\x07ToBoxId\x18\x02 \x01(\x09B\x1CB\x1AForwardDocumentEventProtos"
        , true);

        static::$is_initialized = true;
    }
}

