<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: LoginPassword.proto

namespace GPBMetadata;

class LoginPassword
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0Ap\x0A\x13LoginPassword.proto\x12\x10Diadoc.Api.Proto\"0\x0A\x0DLoginPassword\x12\x0D\x0A\x05Login\x18\x01 \x01(\x09\x12\x10\x0A\x08Password\x18\x02 \x01(\x09B\x15B\x13LoginPasswordProtos"
        , true);

        static::$is_initialized = true;
    }
}

