<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: OrganizationPropertiesToUpdate.proto

namespace GPBMetadata;

class OrganizationPropertiesToUpdate
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Address::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xC4\x04\x0A\$OrganizationPropertiesToUpdate.proto\x12\x10Diadoc.Api.Proto\"\x1C\x0A\x0BStringValue\x12\x0D\x0A\x05Value\x18\x01 \x01(\x09\"\x93\x02\x0A\x1EOrganizationPropertiesToUpdate\x12\x0D\x0A\x05OrgId\x18\x01 \x01(\x09\x12+\x0A\x04Ogrn\x18\x02 \x01(\x0B2\x1D.Diadoc.Api.Proto.StringValue\x12/\x0A\x08IfnsCode\x18\x03 \x01(\x0B2\x1D.Diadoc.Api.Proto.StringValue\x12*\x0A\x07Address\x18\x04 \x01(\x0B2\x19.Diadoc.Api.Proto.Address\x12X\x0A\x1AHeadOrganizationProperties\x18\x05 \x01(\x0B24.Diadoc.Api.Proto.HeadOrganizationPropertiesToUpdate\"\xAD\x01\x0A\"HeadOrganizationPropertiesToUpdate\x12*\x0A\x03Kpp\x18\x01 \x01(\x0B2\x1D.Diadoc.Api.Proto.StringValue\x12/\x0A\x08FullName\x18\x02 \x01(\x0B2\x1D.Diadoc.Api.Proto.StringValue\x12*\x0A\x07Address\x18\x03 \x01(\x0B2\x19.Diadoc.Api.Proto.AddressB&B\$OrganizationPropertiesToUpdateProtos"
        , true);

        static::$is_initialized = true;
    }
}

