<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: OrganizationUser.proto

namespace GPBMetadata;

class OrganizationUser
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\OrganizationUserPermissions::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xAC\x02\x0A\x16OrganizationUser.proto\x12\x10Diadoc.Api.Proto\"\x82\x01\x0A\x10OrganizationUser\x12\x0A\x0A\x02Id\x18\x01 \x01(\x09\x12\x0C\x0A\x04Name\x18\x02 \x01(\x09\x12B\x0A\x0BPermissions\x18\x03 \x01(\x0B2-.Diadoc.Api.Proto.OrganizationUserPermissions\x12\x10\x0A\x08Position\x18\x04 \x01(\x09\"a\x0A\x15OrganizationUsersList\x121\x0A\x05Users\x18\x01 \x03(\x0B2\".Diadoc.Api.Proto.OrganizationUser\x12\x15\x0A\x0DCurrentUserId\x18\x02 \x01(\x09B\x18B\x16OrganizationUserProtos"
        , true);

        static::$is_initialized = true;
    }
}

