<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ResolutionRouteList.proto

namespace GPBMetadata;

class ResolutionRouteList
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xD0\x01\x0A\x19ResolutionRouteList.proto\x12\x10Diadoc.Api.Proto\"R\x0A\x13ResolutionRouteList\x12;\x0A\x10ResolutionRoutes\x18\x01 \x03(\x0B2!.Diadoc.Api.Proto.ResolutionRoute\"0\x0A\x0FResolutionRoute\x12\x0F\x0A\x07RouteId\x18\x01 \x01(\x09\x12\x0C\x0A\x04Name\x18\x02 \x01(\x09B\x1BB\x19ResolutionRouteListProtos"
        , true);

        static::$is_initialized = true;
    }
}

