<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: RoamingOperator.proto

namespace GPBMetadata;

class RoamingOperator
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xC3\x02\x0A\x15RoamingOperator.proto\x12\x10Diadoc.Api.Proto\"R\x0A\x13RoamingOperatorList\x12;\x0A\x10RoamingOperators\x18\x01 \x03(\x0B2!.Diadoc.Api.Proto.RoamingOperator\"u\x0A\x0FRoamingOperator\x12\x0D\x0A\x05FnsId\x18\x01 \x01(\x09\x12\x0C\x0A\x04Name\x18\x02 \x01(\x09\x12\x10\x0A\x08IsActive\x18\x03 \x01(\x08\x123\x0A\x08Features\x18\x04 \x03(\x0B2!.Diadoc.Api.Proto.OperatorFeature\"4\x0A\x0FOperatorFeature\x12\x0C\x0A\x04Name\x18\x01 \x01(\x09\x12\x13\x0A\x0BDescription\x18\x02 \x01(\x09B\x17B\x15RoamingOperatorProtos"
        , true);

        static::$is_initialized = true;
    }
}

