<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: RoamingNotification.proto

namespace GPBMetadata;

class RoamingNotification
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\x87\x01\x0A\x19RoamingNotification.proto\x12\x10Diadoc.Api.Proto\";\x0A\x13RoamingNotification\x12\x0F\x0A\x07Success\x18\x01 \x01(\x08\x12\x13\x0A\x0BDescription\x18\x02 \x01(\x09B\x1BB\x19RoamingNotificationProtos"
        , true);

        static::$is_initialized = true;
    }
}

