<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SignatureVerificationResult.proto

namespace GPBMetadata;

class SignatureVerificationResult
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Timestamp::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\x97\x04\x0A!SignatureVerificationResult.proto\x12\x10Diadoc.Api.Proto\"\xB3\x01\x0A\x1BSignatureVerificationResult\x12\x0F\x0A\x07IsValid\x18\x01 \x01(\x08\x12J\x0A\x11CertificateStatus\x18\x02 \x01(\x0B2/.Diadoc.Api.Proto.CertificateVerificationResult\x127\x0A\x12SignatureTimestamp\x18\x03 \x01(\x0B2\x1B.Diadoc.Api.Proto.Timestamp\"\xAC\x01\x0A\x1DCertificateVerificationResult\x12\x0F\x0A\x07IsValid\x18\x02 \x01(\x08\x12C\x0A\x10CertificateChain\x18\x03 \x03(\x0B2).Diadoc.Api.Proto.CertificateChainElement\x125\x0A\x10VerificationTime\x18\x04 \x01(\x0B2\x1B.Diadoc.Api.Proto.Timestamp\"V\x0A\x17CertificateChainElement\x12#\x0A\x1BCertificateChainStatusFlags\x18\x01 \x01(\x05\x12\x16\x0A\x0EDerCertificate\x18\x02 \x01(\x0CB#B!SignatureVerificationResultProtos"
        , true);

        static::$is_initialized = true;
    }
}

