<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Timestamp.proto

namespace GPBMetadata;

class Timestamp
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0AR\x0A\x0FTimestamp.proto\x12\x10Diadoc.Api.Proto\"\x1A\x0A\x09Timestamp\x12\x0D\x0A\x05Ticks\x18\x01 \x01(\x10B\x11B\x0FTimestampProtos"
        , true);

        static::$is_initialized = true;
    }
}

