<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: User.proto

namespace GPBMetadata;

class User
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\CertificateInfo::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xEA\x02\x0A\x0AUser.proto\x12\x10Diadoc.Api.Proto\"\x89\x01\x0A\x04User\x12\x0A\x0A\x02Id\x18\x01 \x01(\x09\x12\x10\x0A\x08LastName\x18\x02 \x01(\x09\x12\x11\x0A\x09FirstName\x18\x03 \x01(\x09\x12\x12\x0A\x0AMiddleName\x18\x04 \x01(\x09\x12<\x0A\x11CloudCertificates\x18\x05 \x03(\x0B2!.Diadoc.Api.Proto.CertificateInfo\"k\x0A\x06UserV2\x12\x0E\x0A\x06UserId\x18\x01 \x01(\x09\x12\x0D\x0A\x05Login\x18\x02 \x01(\x09\x12,\x0A\x08FullName\x18\x03 \x01(\x0B2\x1A.Diadoc.Api.Proto.FullName\x12\x14\x0A\x0CIsRegistered\x18\x04 \x01(\x08\"C\x0A\x08FullName\x12\x10\x0A\x08LastName\x18\x01 \x01(\x09\x12\x11\x0A\x09FirstName\x18\x02 \x01(\x09\x12\x12\x0A\x0AMiddleName\x18\x03 \x01(\x09B\x0CB\x0AUserProtos"
        , true);

        static::$is_initialized = true;
    }
}

