<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Events/ResolutionInfo.proto

namespace Diadoc\Api\Proto\Events;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.Events.ResolutionInfo</code>
 */
class ResolutionInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.ResolutionType ResolutionType = 1 [default = UnknownResolutionType];</code>
     */
    protected $ResolutionType = null;
    /**
     * ФИО согласователя
     *
     * Generated from protobuf field <code>optional string Author = 2;</code>
     */
    protected $Author = null;
    /**
     * Generated from protobuf field <code>optional string InitialRequestId = 3;</code>
     */
    protected $InitialRequestId = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $ResolutionType
     *     @type string $Author
     *           ФИО согласователя
     *     @type string $InitialRequestId
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Events\ResolutionInfo::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.ResolutionType ResolutionType = 1 [default = UnknownResolutionType];</code>
     * @return int
     */
    public function getResolutionType()
    {
        return isset($this->ResolutionType) ? $this->ResolutionType : 0;
    }

    public function hasResolutionType()
    {
        return isset($this->ResolutionType);
    }

    public function clearResolutionType()
    {
        unset($this->ResolutionType);
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.ResolutionType ResolutionType = 1 [default = UnknownResolutionType];</code>
     * @param int $var
     * @return $this
     */
    public function setResolutionType($var)
    {
        GPBUtil::checkEnum($var, \Diadoc\Api\Proto\ResolutionType::class);
        $this->ResolutionType = $var;

        return $this;
    }

    /**
     * ФИО согласователя
     *
     * Generated from protobuf field <code>optional string Author = 2;</code>
     * @return string
     */
    public function getAuthor()
    {
        return isset($this->Author) ? $this->Author : '';
    }

    public function hasAuthor()
    {
        return isset($this->Author);
    }

    public function clearAuthor()
    {
        unset($this->Author);
    }

    /**
     * ФИО согласователя
     *
     * Generated from protobuf field <code>optional string Author = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAuthor($var)
    {
        GPBUtil::checkString($var, True);
        $this->Author = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string InitialRequestId = 3;</code>
     * @return string
     */
    public function getInitialRequestId()
    {
        return isset($this->InitialRequestId) ? $this->InitialRequestId : '';
    }

    public function hasInitialRequestId()
    {
        return isset($this->InitialRequestId);
    }

    public function clearInitialRequestId()
    {
        unset($this->InitialRequestId);
    }

    /**
     * Generated from protobuf field <code>optional string InitialRequestId = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setInitialRequestId($var)
    {
        GPBUtil::checkString($var, True);
        $this->InitialRequestId = $var;

        return $this;
    }

}

