<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Organizations/AutoBlockStatus.proto

namespace GPBMetadata\Organizations;

class AutoBlockStatus
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\x84\x01\x0A#Organizations/AutoBlockStatus.proto\x12\x1EDiadoc.Api.Proto.Organizations\"\$\x0A\x0FAutoBlockStatus\x12\x11\x0A\x09IsBlocked\x18\x01 \x01(\x08B\x17B\x15AutoBlockStatusProtos"
        , true);

        static::$is_initialized = true;
    }
}

