<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Organizations/BlockStatus.proto

namespace GPBMetadata\Organizations;

class BlockStatus
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Organizations\ManualBlockStatus::initOnce();
        \GPBMetadata\Organizations\AutoBlockStatus::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xA3\x02\x0A\x1FOrganizations/BlockStatus.proto\x12\x1EDiadoc.Api.Proto.Organizations\x1A#Organizations/AutoBlockStatus.proto\"\xA5\x01\x0A\x0BBlockStatus\x12L\x0A\x11ManualBlockStatus\x18\x01 \x01(\x0B21.Diadoc.Api.Proto.Organizations.ManualBlockStatus\x12H\x0A\x0FAutoBlockStatus\x18\x02 \x01(\x0B2/.Diadoc.Api.Proto.Organizations.AutoBlockStatusB\x13B\x11BlockStatusProtos"
        , true);

        static::$is_initialized = true;
    }
}

