<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Organizations/ManualBlockStatus.proto

namespace GPBMetadata\Organizations;

class ManualBlockStatus
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xA2\x01\x0A%Organizations/ManualBlockStatus.proto\x12\x1EDiadoc.Api.Proto.Organizations\">\x0A\x11ManualBlockStatus\x12\x11\x0A\x09IsBlocked\x18\x01 \x01(\x08\x12\x16\x0A\x0ERequestedTicks\x18\x02 \x01(\x10B\x19B\x17ManualBlockStatusProtos"
        , true);

        static::$is_initialized = true;
    }
}

