<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Organizations/OrganizationFeatures.proto

namespace GPBMetadata\Organizations;

class OrganizationFeatures
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Organizations\BlockStatus::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xD4\x01\x0A(Organizations/OrganizationFeatures.proto\x12\x1EDiadoc.Api.Proto.Organizations\"j\x0A\x14OrganizationFeatures\x12@\x0A\x0BBlockStatus\x18\x01 \x01(\x0B2+.Diadoc.Api.Proto.Organizations.BlockStatus\x12\x10\x0A\x08Features\x18\x02 \x03(\x09B\x1CB\x1AOrganizationFeaturesProtos"
        , true);

        static::$is_initialized = true;
    }
}

