<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Invoicing/InvoiceCorrectionRequestInfo.proto

namespace GPBMetadata\Invoicing;

class InvoiceCorrectionRequestInfo
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Invoicing\Signer::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xE0\x02\x0A,Invoicing/InvoiceCorrectionRequestInfo.proto\x12\x1ADiadoc.Api.Proto.Invoicing\"h\x0A\x1CInvoiceCorrectionRequestInfo\x12\x14\x0A\x0CErrorMessage\x18\x01 \x01(\x09\x122\x0A\x06Signer\x18\x02 \x01(\x0B2\".Diadoc.Api.Proto.Invoicing.Signer\"\x83\x01\x0A+InvoiceCorrectionRequestGenerationRequestV2\x12\x14\x0A\x0CErrorMessage\x18\x01 \x01(\x09\x12\x11\x0A\x09MessageId\x18\x02 \x01(\x09\x12\x14\x0A\x0CAttachmentId\x18\x03 \x01(\x09\x12\x15\x0A\x0DSignerContent\x18\x04 \x01(\x0CB\$B\"InvoiceCorrectionRequestInfoProtos"
        , true);

        static::$is_initialized = true;
    }
}

