<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Invoicing/Official.proto

namespace GPBMetadata\Invoicing;

class Official
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xA3\x03\x0A\x18Invoicing/Official.proto\x12\x1ADiadoc.Api.Proto.Invoicing\"T\x0A\x08Official\x12\x0F\x0A\x07Surname\x18\x01 \x01(\x09\x12\x11\x0A\x09FirstName\x18\x02 \x01(\x09\x12\x12\x0A\x0APatronymic\x18\x03 \x01(\x09\x12\x10\x0A\x08JobTitle\x18\x04 \x01(\x09\"\x82\x02\x0A\x08Attorney\x12\x0C\x0A\x04Date\x18\x01 \x01(\x09\x12\x0E\x0A\x06Number\x18\x02 \x01(\x09\x12\x1E\x0A\x16IssuerOrganizationName\x18\x03 \x01(\x09\x12:\x0A\x0CIssuerPerson\x18\x04 \x01(\x0B2\$.Diadoc.Api.Proto.Invoicing.Official\x12\x1C\x0A\x14IssuerAdditionalInfo\x18\x05 \x01(\x09\x12=\x0A\x0FRecipientPerson\x18\x06 \x01(\x0B2\$.Diadoc.Api.Proto.Invoicing.Official\x12\x1F\x0A\x17RecipientAdditionalInfo\x18\x07 \x01(\x09B\x10B\x0EOfficialProtos"
        , true);

        static::$is_initialized = true;
    }
}

