<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Invoicing/ReceiptGenerationRequest.proto

namespace GPBMetadata\Invoicing;

class ReceiptGenerationRequest
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xC6\x01\x0A(Invoicing/ReceiptGenerationRequest.proto\x12\x1ADiadoc.Api.Proto.Invoicing\"\\\x0A\x1AReceiptGenerationRequestV2\x12\x11\x0A\x09MessageId\x18\x01 \x01(\x09\x12\x14\x0A\x0CAttachmentId\x18\x02 \x01(\x09\x12\x15\x0A\x0DSignerContent\x18\x03 \x01(\x0CB B\x1EReceiptGenerationRequestProtos"
        , true);

        static::$is_initialized = true;
    }
}

