<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Invoicing/RevocationRequestInfo.proto

namespace GPBMetadata\Invoicing;

class RevocationRequestInfo
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Invoicing\Signer::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xC0\x01\x0A%Invoicing/RevocationRequestInfo.proto\x12\x1ADiadoc.Api.Proto.Invoicing\"\\\x0A\x15RevocationRequestInfo\x12\x0F\x0A\x07Comment\x18\x01 \x01(\x09\x122\x0A\x06Signer\x18\x02 \x01(\x0B2\".Diadoc.Api.Proto.Invoicing.SignerB\x1DB\x1BRevocationRequestInfoProtos"
        , true);

        static::$is_initialized = true;
    }
}

