<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Invoicing/SignatureRejectionInfo.proto

namespace GPBMetadata\Invoicing;

class SignatureRejectionInfo
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Invoicing\Signer::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xC7\x02\x0A&Invoicing/SignatureRejectionInfo.proto\x12\x1ADiadoc.Api.Proto.Invoicing\"b\x0A\x16SignatureRejectionInfo\x12\x14\x0A\x0CErrorMessage\x18\x01 \x01(\x09\x122\x0A\x06Signer\x18\x02 \x01(\x0B2\".Diadoc.Api.Proto.Invoicing.Signer\"}\x0A%SignatureRejectionGenerationRequestV2\x12\x14\x0A\x0CErrorMessage\x18\x01 \x01(\x09\x12\x11\x0A\x09MessageId\x18\x02 \x01(\x09\x12\x14\x0A\x0CAttachmentId\x18\x03 \x01(\x09\x12\x15\x0A\x0DSignerContent\x18\x04 \x01(\x0CB\x1EB\x1CSignatureRejectionInfoProtos"
        , true);

        static::$is_initialized = true;
    }
}

