<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Certificates/CertificateList.proto

namespace GPBMetadata\Certificates;

class CertificateList
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Certificates\CertificateInfoV2::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xB7\x01\x0A\"Certificates/CertificateList.proto\x12\x1DDiadoc.Api.Proto.Certificates\"Y\x0A\x0FCertificateList\x12F\x0A\x0CCertificates\x18\x01 \x03(\x0B20.Diadoc.Api.Proto.Certificates.CertificateInfoV2B\x17B\x15CertificateListProtos"
        , true);

        static::$is_initialized = true;
    }
}

