<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Workflows/AmendmentRequestResponseBehavior.proto

namespace GPBMetadata\Workflows;

class AmendmentRequestResponseBehavior
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xA7\x02\x0A0Workflows/AmendmentRequestResponseBehavior.proto\x12;Diadoc.Api.Proto.Workflows.AmendmentRequestResponseBehavior*\x83\x01\x0A AmendmentRequestResponseBehavior\x12\x0B\x0A\x07Unknown\x10\x00\x12\x08\x0A\x04None\x10\x01\x12\x0B\x0A\x07Receipt\x10\x02\x12\x18\x0A\x14OperatorConfirmation\x10\x03\x12!\x0A\x1DOperatorConfirmationOrReceipt\x10\x04B(B&AmendmentRequestResponseBehaviorProtosb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

