<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Workflows/OperatorConfirmationBehavior.proto

namespace GPBMetadata\Workflows;

class OperatorConfirmationBehavior
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xF6\x01\x0A,Workflows/OperatorConfirmationBehavior.proto\x127Diadoc.Api.Proto.Workflows.OperatorConfirmationBehavior*_\x0A\x1COperatorConfirmationBehavior\x12\x0B\x0A\x07Unknown\x10\x00\x12\x09\x0A\x05Never\x10\x01\x12\x0D\x0A\x09Initiator\x10\x02\x12\x18\x0A\x14InitiatorCounterpart\x10\x03B\$B\"OperatorConfirmationBehaviorProtosb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

