<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Workflows/ParticipantType.proto

namespace GPBMetadata\Workflows;

class ParticipantType
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xB4\x01\x0A\x1FWorkflows/ParticipantType.proto\x12*Diadoc.Api.Proto.Workflows.ParticipantType*D\x0A\x0FParticipantType\x12\x0B\x0A\x07Unknown\x10\x00\x12\x0A\x0A\x06Sender\x10\x01\x12\x09\x0A\x05Proxy\x10\x02\x12\x0D\x0A\x09Recipient\x10\x03B\x17B\x15ParticipantTypeProtosb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

