<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Workflows/ParticipantAction.proto

namespace GPBMetadata\Workflows;

class ParticipantAction
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xC7\x01\x0A!Workflows/ParticipantAction.proto\x12,Diadoc.Api.Proto.Workflows.ParticipantAction*Q\x0A\x11ParticipantAction\x12\x0B\x0A\x07Unknown\x10\x00\x12\x09\x0A\x05Title\x10\x01\x12\x0D\x0A\x09Signature\x10\x02\x12\x15\x0A\x11OptionalSignature\x10\x03B\x19B\x17ParticipantActionProtosb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

