<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Workflows/ReceiptOperatorConfirmationReceiptBehavior.proto

namespace GPBMetadata\Workflows;

class ReceiptOperatorConfirmationReceiptBehavior
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\x91\x02\x0A:Workflows/ReceiptOperatorConfirmationReceiptBehavior.proto\x12EDiadoc.Api.Proto.Workflows.ReceiptOperatorConfirmationReceiptBehavior*P\x0A*ReceiptOperatorConfirmationReceiptBehavior\x12\x0B\x0A\x07Unknown\x10\x00\x12\x09\x0A\x05Never\x10\x01\x12\x0A\x0A\x06Always\x10\x02B2B0ReceiptOperatorConfirmationReceiptBehaviorProtosb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

