<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Workflows/RoamingConfirmationBehavior.proto

namespace GPBMetadata\Workflows;

class RoamingConfirmationBehavior
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xD5\x01\x0A+Workflows/RoamingConfirmationBehavior.proto\x126Diadoc.Api.Proto.Workflows.RoamingConfirmationBehavior*A\x0A\x1BRoamingConfirmationBehavior\x12\x0B\x0A\x07Unknown\x10\x00\x12\x09\x0A\x05Never\x10\x01\x12\x0A\x0A\x06Always\x10\x02B#B!RoamingConfirmationBehaviorProtosb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

