<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Workflows/TitleReceiptBehavior.proto

namespace GPBMetadata\Workflows;

class TitleReceiptBehavior
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xCB\x01\x0A\$Workflows/TitleReceiptBehavior.proto\x12/Diadoc.Api.Proto.Workflows.TitleReceiptBehavior*L\x0A\x14TitleReceiptBehavior\x12\x0B\x0A\x07Unknown\x10\x00\x12\x09\x0A\x05Never\x10\x01\x12\x10\x0A\x0CDefineByUser\x10\x02\x12\x0A\x0A\x06Always\x10\x03B\x1CB\x1ATitleReceiptBehaviorProtosb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

