<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Forwarding/ForwardingApi.proto

namespace GPBMetadata\Forwarding;

class ForwardingApi
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Timestamp::initOnce();
        \GPBMetadata\DocumentId::initOnce();
        \GPBMetadata\TotalCountType::initOnce();
        \GPBMetadata\TimeBasedFilter::initOnce();
        \GPBMetadata\Forwarding\ForwardedDocument::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xA8\x0A\x0A\x1EForwarding/ForwardingApi.proto\x12\x1BDiadoc.Api.Proto.Forwarding\x1A\x10DocumentId.proto\x1A\x14TotalCountType.proto\x1A\x15TimeBasedFilter.proto\x1A\"Forwarding/ForwardedDocument.proto\"[\x0A\x16ForwardDocumentRequest\x12\x0F\x0A\x07ToBoxId\x18\x01 \x01(\x09\x120\x0A\x0ADocumentId\x18\x02 \x01(\x0B2\x1C.Diadoc.Api.Proto.DocumentId\"\x9F\x01\x0A\x17ForwardDocumentResponse\x125\x0A\x10ForwardTimestamp\x18\x01 \x01(\x0B2\x1B.Diadoc.Api.Proto.Timestamp\x12M\x0A\x13ForwardedDocumentId\x18\x02 \x01(\x0B20.Diadoc.Api.Proto.Forwarding.ForwardedDocumentId\"\x92\x01\x0A\x1CGetForwardedDocumentsRequest\x12N\x0A\x14ForwardedDocumentIds\x18\x01 \x03(\x0B20.Diadoc.Api.Proto.Forwarding.ForwardedDocumentId\x12\"\x0A\x13InjectEntityContent\x18\x02 \x01(\x08:\x05false\"k\x0A\x1DGetForwardedDocumentsResponse\x12J\x0A\x12ForwardedDocuments\x18\x01 \x03(\x0B2..Diadoc.Api.Proto.Forwarding.ForwardedDocument\"\xBC\x01\x0A!GetForwardedDocumentEventsRequest\x121\x0A\x06Filter\x18\x01 \x01(\x0B2!.Diadoc.Api.Proto.TimeBasedFilter\x12\x15\x0A\x0DAfterIndexKey\x18\x02 \x01(\x0C\x12)\x0A\x1APopulateForwardedDocuments\x18\x03 \x01(\x08:\x05false\x12\"\x0A\x13InjectEntityContent\x18\x04 \x01(\x08:\x05false\"\xB7\x01\x0A\"GetForwardedDocumentEventsResponse\x12\x12\x0A\x0ATotalCount\x18\x01 \x01(\x05\x12C\x0A\x06Events\x18\x02 \x03(\x0B23.Diadoc.Api.Proto.Forwarding.ForwardedDocumentEvent\x128\x0A\x0ETotalCountType\x18\x03 \x01(\x0E2 .Diadoc.Api.Proto.TotalCountType\"\xF4\x01\x0A\x16ForwardedDocumentEvent\x12.\x0A\x09Timestamp\x18\x01 \x01(\x0B2\x1B.Diadoc.Api.Proto.Timestamp\x12M\x0A\x13ForwardedDocumentId\x18\x02 \x01(\x0B20.Diadoc.Api.Proto.Forwarding.ForwardedDocumentId\x12\x10\x0A\x08IndexKey\x18\x03 \x01(\x0C\x12I\x0A\x11ForwardedDocument\x18\x04 \x01(\x0B2..Diadoc.Api.Proto.Forwarding.ForwardedDocumentB\x15B\x13ForwardingApiProtos"
        , true);

        static::$is_initialized = true;
    }
}

