<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Forwarding/ForwardedDocument.proto

namespace GPBMetadata\Forwarding;

class ForwardedDocument
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Timestamp::initOnce();
        \GPBMetadata\DocumentId::initOnce();
        \GPBMetadata\Docflow\DocumentWithDocflow::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xED\x03\x0A\"Forwarding/ForwardedDocument.proto\x12\x1BDiadoc.Api.Proto.Forwarding\x1A\x10DocumentId.proto\x1A!Docflow/DocumentWithDocflow.proto\"r\x0A\x13ForwardedDocumentId\x12\x11\x0A\x09FromBoxId\x18\x01 \x01(\x09\x120\x0A\x0ADocumentId\x18\x02 \x01(\x0B2\x1C.Diadoc.Api.Proto.DocumentId\x12\x16\x0A\x0EForwardEventId\x18\x03 \x01(\x09\"\xE5\x01\x0A\x11ForwardedDocument\x125\x0A\x10ForwardTimestamp\x18\x01 \x01(\x0B2\x1B.Diadoc.Api.Proto.Timestamp\x12M\x0A\x13ForwardedDocumentId\x18\x02 \x01(\x0B20.Diadoc.Api.Proto.Forwarding.ForwardedDocumentId\x12J\x0A\x13DocumentWithDocflow\x18\x03 \x01(\x0B2-.Diadoc.Api.Proto.Docflow.DocumentWithDocflowB\x19B\x17ForwardedDocumentProtos"
        , true);

        static::$is_initialized = true;
    }
}

