<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: CounteragentGroups/CounteragentGroupToUpdate.proto

namespace Diadoc\Api\Proto\CounteragentGroups;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupDepartmentPatch</code>
 */
class CounteragentGroupDepartmentPatch extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional bool AnyDepartment = 1;</code>
     */
    protected $AnyDepartment = null;
    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.CounteragentGroups.DepartmentsInGroup Departments = 2;</code>
     */
    protected $Departments = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $AnyDepartment
     *     @type \Diadoc\Api\Proto\CounteragentGroups\DepartmentsInGroup $Departments
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\CounteragentGroups\CounteragentGroupToUpdate::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional bool AnyDepartment = 1;</code>
     * @return bool
     */
    public function getAnyDepartment()
    {
        return isset($this->AnyDepartment) ? $this->AnyDepartment : false;
    }

    public function hasAnyDepartment()
    {
        return isset($this->AnyDepartment);
    }

    public function clearAnyDepartment()
    {
        unset($this->AnyDepartment);
    }

    /**
     * Generated from protobuf field <code>optional bool AnyDepartment = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setAnyDepartment($var)
    {
        GPBUtil::checkBool($var);
        $this->AnyDepartment = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.CounteragentGroups.DepartmentsInGroup Departments = 2;</code>
     * @return \Diadoc\Api\Proto\CounteragentGroups\DepartmentsInGroup|null
     */
    public function getDepartments()
    {
        return $this->Departments;
    }

    public function hasDepartments()
    {
        return isset($this->Departments);
    }

    public function clearDepartments()
    {
        unset($this->Departments);
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.CounteragentGroups.DepartmentsInGroup Departments = 2;</code>
     * @param \Diadoc\Api\Proto\CounteragentGroups\DepartmentsInGroup $var
     * @return $this
     */
    public function setDepartments($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\CounteragentGroups\DepartmentsInGroup::class);
        $this->Departments = $var;

        return $this;
    }

}

