<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Docflow/Attachment.proto

namespace GPBMetadata\Docflow;

class Attachment
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Content::initOnce();
        \GPBMetadata\Timestamp::initOnce();
        \GPBMetadata\SignatureVerificationResult::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xF8\x05\x0A\x18Docflow/Attachment.proto\x12\x18Diadoc.Api.Proto.Docflow\x1A\x0FTimestamp.proto\x1A!SignatureVerificationResult.proto\"~\x0A\x06Entity\x12\x10\x0A\x08EntityId\x18\x01 \x01(\x09\x126\x0A\x11CreationTimestamp\x18\x02 \x01(\x0B2\x1B.Diadoc.Api.Proto.Timestamp\x12*\x0A\x07Content\x18\x03 \x01(\x0B2\x19.Diadoc.Api.Proto.Content\"s\x0A\x0AAttachment\x120\x0A\x06Entity\x18\x01 \x01(\x0B2 .Diadoc.Api.Proto.Docflow.Entity\x12\x1A\x0A\x12AttachmentFilename\x18\x02 \x01(\x09\x12\x17\x0A\x0FDisplayFilename\x18\x03 \x01(\x09\"\xCA\x01\x0A\x09Signature\x120\x0A\x06Entity\x18\x01 \x01(\x0B2 .Diadoc.Api.Proto.Docflow.Entity\x12\x13\x0A\x0BSignerBoxId\x18\x02 \x01(\x09\x12\x1A\x0A\x12SignerDepartmentId\x18\x03 \x01(\x09\x12\x0F\x0A\x07IsValid\x18\x04 \x01(\x08\x12I\x0A\x12VerificationResult\x18\x05 \x01(\x0B2-.Diadoc.Api.Proto.SignatureVerificationResult\"\xB7\x01\x0A\x10SignedAttachment\x128\x0A\x0AAttachment\x18\x01 \x01(\x0B2\$.Diadoc.Api.Proto.Docflow.Attachment\x126\x0A\x09Signature\x18\x02 \x01(\x0B2#.Diadoc.Api.Proto.Docflow.Signature\x121\x0A\x07Comment\x18\x03 \x01(\x0B2 .Diadoc.Api.Proto.Docflow.EntityB\x12B\x10AttachmentProtos"
        , true);

        static::$is_initialized = true;
    }
}

