<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Docflow/DocflowApiV3.proto

namespace GPBMetadata\Docflow;

class DocflowApiV3
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Timestamp::initOnce();
        \GPBMetadata\DocumentId::initOnce();
        \GPBMetadata\TotalCountType::initOnce();
        \GPBMetadata\Docflow\DocumentWithDocflowV3::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xC7\x08\x0A\x1ADocflow/DocflowApiV3.proto\x12\x18Diadoc.Api.Proto.Docflow\x1A\x10DocumentId.proto\x1A\x14TotalCountType.proto\x1A#Docflow/DocumentWithDocflowV3.proto\"_\x0A\x19GetDocflowBatchResponseV3\x12B\x0A\x09Documents\x18\x01 \x03(\x0B2/.Diadoc.Api.Proto.Docflow.DocumentWithDocflowV3\"y\x0A\x18SearchDocflowsResponseV3\x12B\x0A\x09Documents\x18\x01 \x03(\x0B2/.Diadoc.Api.Proto.Docflow.DocumentWithDocflowV3\x12\x19\x0A\x11HaveMoreDocuments\x18\x02 \x01(\x08\"h\x0A\x11FetchedDocumentV3\x12A\x0A\x08Document\x18\x01 \x01(\x0B2/.Diadoc.Api.Proto.Docflow.DocumentWithDocflowV3\x12\x10\x0A\x08IndexKey\x18\x02 \x01(\x0C\"{\x0A\x1FGetDocflowsByPacketIdResponseV3\x12>\x0A\x09Documents\x18\x01 \x03(\x0B2+.Diadoc.Api.Proto.Docflow.FetchedDocumentV3\x12\x18\x0A\x10NextPageIndexKey\x18\x02 \x01(\x0C\"\xA4\x01\x0A\x1AGetDocflowEventsResponseV3\x12\x12\x0A\x0ATotalCount\x18\x01 \x01(\x05\x128\x0A\x06Events\x18\x02 \x03(\x0B2(.Diadoc.Api.Proto.Docflow.DocflowEventV3\x128\x0A\x0ETotalCountType\x18\x03 \x01(\x0E2 .Diadoc.Api.Proto.TotalCountType\"\xC1\x02\x0A\x0EDocflowEventV3\x12\x0F\x0A\x07EventId\x18\x01 \x01(\x09\x12.\x0A\x09Timestamp\x18\x02 \x01(\x0B2\x1B.Diadoc.Api.Proto.Timestamp\x120\x0A\x0ADocumentId\x18\x03 \x01(\x0B2\x1C.Diadoc.Api.Proto.DocumentId\x12\x10\x0A\x08IndexKey\x18\x04 \x01(\x0C\x12A\x0A\x08Document\x18\x05 \x01(\x0B2/.Diadoc.Api.Proto.Docflow.DocumentWithDocflowV3\x12\x17\x0A\x0FPreviousEventId\x18\x06 \x01(\x09\x12N\x0A\x15PreviousDocumentState\x18\x07 \x01(\x0B2/.Diadoc.Api.Proto.Docflow.DocumentWithDocflowV3B\x14B\x12DocflowApiV3Protos"
        , true);

        static::$is_initialized = true;
    }
}

