<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Docflow/DocumentWithDocflow.proto

namespace GPBMetadata\Docflow;

class DocumentWithDocflow
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Timestamp::initOnce();
        \GPBMetadata\DocumentId::initOnce();
        \GPBMetadata\ForwardDocumentEvent::initOnce();
        \GPBMetadata\Docflow\Docflow::initOnce();
        \GPBMetadata\Docflow\DocumentInfo::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\x84\x05\x0A!Docflow/DocumentWithDocflow.proto\x12\x18Diadoc.Api.Proto.Docflow\x1A\x10DocumentId.proto\x1A\x1AForwardDocumentEvent.proto\x1A\x15Docflow/Docflow.proto\x1A\x1ADocflow/DocumentInfo.proto\"\xC6\x03\x0A\x13DocumentWithDocflow\x120\x0A\x0ADocumentId\x18\x01 \x01(\x0B2\x1C.Diadoc.Api.Proto.DocumentId\x12\x13\x0A\x0BLastEventId\x18\x02 \x01(\x09\x127\x0A\x12LastEventTimestamp\x18\x03 \x01(\x0B2\x1B.Diadoc.Api.Proto.Timestamp\x12<\x0A\x0CDocumentInfo\x18\x04 \x01(\x0B2&.Diadoc.Api.Proto.Docflow.DocumentInfo\x122\x0A\x07Docflow\x18\x05 \x01(\x0B2!.Diadoc.Api.Proto.Docflow.Docflow\x128\x0A\x12InitialDocumentIds\x18\x06 \x03(\x0B2\x1C.Diadoc.Api.Proto.DocumentId\x12<\x0A\x16SubordinateDocumentIds\x18\x07 \x03(\x0B2\x1C.Diadoc.Api.Proto.DocumentId\x12E\x0A\x15ForwardDocumentEvents\x18\x08 \x03(\x0B2&.Diadoc.Api.Proto.ForwardDocumentEventB\x1BB\x19DocumentWithDocflowProtos"
        , true);

        static::$is_initialized = true;
    }
}

