<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Docflow/DocumentWithDocflowV3.proto

namespace GPBMetadata\Docflow;

class DocumentWithDocflowV3
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\DocumentId::initOnce();
        \GPBMetadata\Timestamp::initOnce();
        \GPBMetadata\Docflow\DocumentInfoV3::initOnce();
        \GPBMetadata\Docflow\DocflowV3::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xEE\x03\x0A#Docflow/DocumentWithDocflowV3.proto\x12\x18Diadoc.Api.Proto.Docflow\x1A\x0FTimestamp.proto\x1A\x1CDocflow/DocumentInfoV3.proto\x1A\x17Docflow/DocflowV3.proto\"\xF7\x01\x0A\x15DocumentWithDocflowV3\x120\x0A\x0ADocumentId\x18\x01 \x01(\x0B2\x1C.Diadoc.Api.Proto.DocumentId\x126\x0A\x09LastEvent\x18\x02 \x01(\x0B2#.Diadoc.Api.Proto.Docflow.LastEvent\x12>\x0A\x0CDocumentInfo\x18\x03 \x01(\x0B2(.Diadoc.Api.Proto.Docflow.DocumentInfoV3\x124\x0A\x07Docflow\x18\x04 \x01(\x0B2#.Diadoc.Api.Proto.Docflow.DocflowV3\"L\x0A\x09LastEvent\x12\x0F\x0A\x07EventId\x18\x01 \x01(\x09\x12.\x0A\x09Timestamp\x18\x02 \x01(\x0B2\x1B.Diadoc.Api.Proto.TimestampB\x1DB\x1BDocumentWithDocflowV3Protos"
        , true);

        static::$is_initialized = true;
    }
}

