<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Docflow/ReceiptDocflow.proto

namespace GPBMetadata\Docflow;

class ReceiptDocflow
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Docflow\Attachment::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xBD\x01\x0A\x1CDocflow/ReceiptDocflow.proto\x12\x18Diadoc.Api.Proto.Docflow\"k\x0A\x0EReceiptDocflow\x12\x12\x0A\x0AIsFinished\x18\x01 \x01(\x08\x12E\x0A\x11ReceiptAttachment\x18\x02 \x01(\x0B2*.Diadoc.Api.Proto.Docflow.SignedAttachmentB\x16B\x14ReceiptDocflowProtos"
        , true);

        static::$is_initialized = true;
    }
}

