<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Docflow/ResolutionDocflow.proto

namespace GPBMetadata\Docflow;

class ResolutionDocflow
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Timestamp::initOnce();
        \GPBMetadata\ResolutionTarget::initOnce();
        \GPBMetadata\Docflow\Attachment::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\x9D\x01\x0A\x1FDocflow/ResolutionDocflow.proto\x12\x18Diadoc.Api.Proto.Docflow\x1A\x16ResolutionTarget.proto\x1A\x18Docflow/Attachment.proto\"\x13\x0A\x11ResolutionDocflowB\x19B\x17ResolutionDocflowProtos"
        , true);

        static::$is_initialized = true;
    }
}

