<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Docflow/RoamingNotification.proto

namespace GPBMetadata\Docflow;

class RoamingNotification
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Docflow\Attachment::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xBC\x01\x0A!Docflow/RoamingNotification.proto\x12\x18Diadoc.Api.Proto.Docflow\"`\x0A\x13RoamingNotification\x126\x0A\x0CNotification\x18\x01 \x01(\x0B2 .Diadoc.Api.Proto.Docflow.Entity\x12\x11\x0A\x09IsSuccess\x18\x02 \x01(\x08B\x1BB\x19RoamingNotificationProtos"
        , true);

        static::$is_initialized = true;
    }
}

