<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Docflow/SignaturePowerOfAttorney.proto

namespace GPBMetadata\Docflow;

class SignaturePowerOfAttorney
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\PowersOfAttorney\PowerOfAttorney::initOnce();
        \GPBMetadata\PowersOfAttorney\PowerOfAttorneyValidation::initOnce();
        \GPBMetadata\Docflow\Attachment::initOnce();
        \GPBMetadata\RoamingSendingStatus::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xDF\x06\x0A&Docflow/SignaturePowerOfAttorney.proto\x12\x18Diadoc.Api.Proto.Docflow\x1A0PowersOfAttorney/PowerOfAttorneyValidation.proto\x1A\x18Docflow/Attachment.proto\x1A\x1ARoamingSendingStatus.proto\"\xDB\x03\x0A\x18SignaturePowerOfAttorney\x120\x0A\x06Entity\x18\x01 \x01(\x0B2 .Diadoc.Api.Proto.Docflow.Entity\x12H\x0A\x06FullId\x18\x02 \x01(\x0B28.Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyFullId\x12R\x0A\x06Status\x18\x03 \x01(\x0B2B.Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyValidationStatus\x12L\x0A\x0DStatusChanges\x18\x04 \x03(\x0B25.Diadoc.Api.Proto.Docflow.PowerOfAttorneyStatusChange\x12D\x0A\x14RoamingSendingStatus\x18\x05 \x01(\x0B2&.Diadoc.Api.Proto.RoamingSendingStatus\x12[\x0A\x0BSendingType\x18\x06 \x01(\x0E2=.Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneySendingType:\x07Unknown\"\xB2\x01\x0A\x1BPowerOfAttorneyStatusChange\x120\x0A\x06Entity\x18\x01 \x01(\x0B2 .Diadoc.Api.Proto.Docflow.Entity\x12a\x0A\x15PowerOfAttorneyStatus\x18\x02 \x01(\x0B2B.Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyValidationStatusB B\x1ESignaturePowerOfAttorneyProtos"
        , true);

        static::$is_initialized = true;
    }
}

