<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Employees/EmployeeToUpdate.proto

namespace GPBMetadata\Employees;

class EmployeeToUpdate
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Employees\Employee::initOnce();
        \GPBMetadata\OrganizationUserPermissions::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xC7\x0A\x0A Employees/EmployeeToUpdate.proto\x12\x1ADiadoc.Api.Proto.Employees\x1A!OrganizationUserPermissions.proto\"\xFD\x01\x0A\x10EmployeeToUpdate\x12I\x0A\x0BPermissions\x18\x01 \x01(\x0B24.Diadoc.Api.Proto.Employees.EmployeePermissionsPatch\x12C\x0A\x08Position\x18\x02 \x01(\x0B21.Diadoc.Api.Proto.Employees.EmployeePositionPatch\x12Y\x0A\x13CanBeInvitedForChat\x18\x03 \x01(\x0B2<.Diadoc.Api.Proto.Employees.EmployeeCanBeInvitedForChatPatch\"\x84\x04\x0A\x18EmployeePermissionsPatch\x12G\x0A\x0ADepartment\x18\x01 \x01(\x0B23.Diadoc.Api.Proto.Employees.EmployeeDepartmentPatch\x12Q\x0A\x0FIsAdministrator\x18\x02 \x01(\x0B28.Diadoc.Api.Proto.Employees.EmployeeIsAdministratorPatch\x12Y\x0A\x13DocumentAccessLevel\x18\x03 \x01(\x0B2<.Diadoc.Api.Proto.Employees.EmployeeDocumentAccessLevelPatch\x12Y\x0A\x13SelectedDepartments\x18\x04 \x01(\x0B2<.Diadoc.Api.Proto.Employees.EmployeeSelectedDepartmentsPatch\x12;\x0A\x07Actions\x18\x05 \x03(\x0B2*.Diadoc.Api.Proto.Employees.EmployeeAction\x12Y\x0A\x17AuthorizationPermission\x18\x06 \x01(\x0B28.Diadoc.Api.Proto.Employees.AuthorizationPermissionPatch\"/\x0A\x17EmployeeDepartmentPatch\x12\x14\x0A\x0CDepartmentId\x18\x01 \x01(\x09\"7\x0A\x1CEmployeeIsAdministratorPatch\x12\x17\x0A\x0FIsAdministrator\x18\x01 \x01(\x08\"f\x0A EmployeeDocumentAccessLevelPatch\x12B\x0A\x13DocumentAccessLevel\x18\x01 \x01(\x0E2%.Diadoc.Api.Proto.DocumentAccessLevel\"A\x0A EmployeeSelectedDepartmentsPatch\x12\x1D\x0A\x15SelectedDepartmentIds\x18\x01 \x03(\x09\")\x0A\x15EmployeePositionPatch\x12\x10\x0A\x08Position\x18\x01 \x01(\x09\"?\x0A EmployeeCanBeInvitedForChatPatch\x12\x1B\x0A\x13CanBeInvitedForChat\x18\x01 \x01(\x08\"B\x0A\x1CAuthorizationPermissionPatch\x12\x11\x0A\x09IsBlocked\x18\x01 \x01(\x08\x12\x0F\x0A\x07Comment\x18\x02 \x01(\x09B\x18B\x16EmployeeToUpdateProtos"
        , true);

        static::$is_initialized = true;
    }
}

