<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Employees/Employee.proto

namespace GPBMetadata\Employees;

class Employee
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\User::initOnce();
        \GPBMetadata\OrganizationUserPermissions::initOnce();
        \GPBMetadata\Timestamp::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xC1\x06\x0A\x18Employees/Employee.proto\x12\x1ADiadoc.Api.Proto.Employees\x1A!OrganizationUserPermissions.proto\x1A\x0FTimestamp.proto\"\xDF\x01\x0A\x08Employee\x12&\x0A\x04User\x18\x01 \x01(\x0B2\x18.Diadoc.Api.Proto.UserV2\x12D\x0A\x0BPermissions\x18\x02 \x01(\x0B2/.Diadoc.Api.Proto.Employees.EmployeePermissions\x12\x10\x0A\x08Position\x18\x03 \x01(\x09\x12\x1B\x0A\x13CanBeInvitedForChat\x18\x04 \x01(\x08\x126\x0A\x11CreationTimestamp\x18\x05 \x01(\x0B2\x1B.Diadoc.Api.Proto.Timestamp\"\xD0\x02\x0A\x13EmployeePermissions\x12\x18\x0A\x10UserDepartmentId\x18\x01 \x01(\x09\x12\x17\x0A\x0FIsAdministrator\x18\x02 \x01(\x08\x12^\x0A\x13DocumentAccessLevel\x18\x03 \x01(\x0E2%.Diadoc.Api.Proto.DocumentAccessLevel:\x1AUnknownDocumentAccessLevel\x12\x1D\x0A\x15SelectedDepartmentIds\x18\x04 \x03(\x09\x12;\x0A\x07Actions\x18\x05 \x03(\x0B2*.Diadoc.Api.Proto.Employees.EmployeeAction\x12J\x0A\x17AuthorizationPermission\x18\x06 \x01(\x0B2).Diadoc.Api.Proto.AuthorizationPermission\"1\x0A\x0EEmployeeAction\x12\x0C\x0A\x04Name\x18\x01 \x01(\x09\x12\x11\x0A\x09IsAllowed\x18\x02 \x01(\x08\"[\x0A\x0CEmployeeList\x127\x0A\x09Employees\x18\x01 \x03(\x0B2\$.Diadoc.Api.Proto.Employees.Employee\x12\x12\x0A\x0ATotalCount\x18\x02 \x01(\x05B\x10B\x0EEmployeeProtos"
        , true);

        static::$is_initialized = true;
    }
}

