<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Employees/EmployeeToCreate.proto

namespace GPBMetadata\Employees;

class EmployeeToCreate
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\User::initOnce();
        \GPBMetadata\Employees\Employee::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xAC\x05\x0A Employees/EmployeeToCreate.proto\x12\x1ADiadoc.Api.Proto.Employees\x1A\x18Employees/Employee.proto\"\xD5\x01\x0A\x10EmployeeToCreate\x12L\x0A\x0BCredentials\x18\x01 \x01(\x0B27.Diadoc.Api.Proto.Employees.EmployeeToCreateCredentials\x12\x10\x0A\x08Position\x18\x02 \x01(\x09\x12\x1B\x0A\x13CanBeInvitedForChat\x18\x03 \x01(\x08\x12D\x0A\x0BPermissions\x18\x04 \x01(\x0B2/.Diadoc.Api.Proto.Employees.EmployeePermissions\"\xB1\x01\x0A\x1BEmployeeToCreateCredentials\x12B\x0A\x05Login\x18\x01 \x01(\x0B23.Diadoc.Api.Proto.Employees.EmployeeToCreateByLogin\x12N\x0A\x0BCertificate\x18\x02 \x01(\x0B29.Diadoc.Api.Proto.Employees.EmployeeToCreateByCertificate\"V\x0A\x17EmployeeToCreateByLogin\x12\x0D\x0A\x05Login\x18\x01 \x01(\x09\x12,\x0A\x08FullName\x18\x02 \x01(\x0B2\x1A.Diadoc.Api.Proto.FullName\"T\x0A\x1DEmployeeToCreateByCertificate\x12\x0F\x0A\x07Content\x18\x01 \x01(\x0C\x12\x13\x0A\x0BAccessBasis\x18\x02 \x01(\x09\x12\x0D\x0A\x05Email\x18\x03 \x01(\x09B\x18B\x16EmployeeToCreateProtos"
        , true);

        static::$is_initialized = true;
    }
}

