<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: CloudSign.proto

namespace Diadoc\Api\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.AutosignReceiptsResult</code>
 */
class AutosignReceiptsResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional int64 SignedReceiptsCount = 1;</code>
     */
    protected $SignedReceiptsCount = null;
    /**
     * Generated from protobuf field <code>optional string NextBatchKey = 2;</code>
     */
    protected $NextBatchKey = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $SignedReceiptsCount
     *     @type string $NextBatchKey
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\CloudSign::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional int64 SignedReceiptsCount = 1;</code>
     * @return int|string
     */
    public function getSignedReceiptsCount()
    {
        return isset($this->SignedReceiptsCount) ? $this->SignedReceiptsCount : 0;
    }

    public function hasSignedReceiptsCount()
    {
        return isset($this->SignedReceiptsCount);
    }

    public function clearSignedReceiptsCount()
    {
        unset($this->SignedReceiptsCount);
    }

    /**
     * Generated from protobuf field <code>optional int64 SignedReceiptsCount = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSignedReceiptsCount($var)
    {
        GPBUtil::checkInt64($var);
        $this->SignedReceiptsCount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string NextBatchKey = 2;</code>
     * @return string
     */
    public function getNextBatchKey()
    {
        return isset($this->NextBatchKey) ? $this->NextBatchKey : '';
    }

    public function hasNextBatchKey()
    {
        return isset($this->NextBatchKey);
    }

    public function clearNextBatchKey()
    {
        unset($this->NextBatchKey);
    }

    /**
     * Generated from protobuf field <code>optional string NextBatchKey = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setNextBatchKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->NextBatchKey = $var;

        return $this;
    }

}

