<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: CertificateInfoV2.proto

namespace Diadoc\Api\Proto;

use UnexpectedValueException;

/**
 * Protobuf type <code>Diadoc.Api.Proto.CertificateType</code>
 */
class CertificateType
{
    /**
     * Generated from protobuf enum <code>UnknownCertificateType = 0;</code>
     */
    const UnknownCertificateType = 0;
    /**
     * Generated from protobuf enum <code>TokenCertificateType = 1;</code>
     */
    const TokenCertificateType = 1;
    /**
     * Generated from protobuf enum <code>DssCertificateType = 2;</code>
     */
    const DssCertificateType = 2;
    /**
     * Generated from protobuf enum <code>KonturCertificateType = 3;</code>
     */
    const KonturCertificateType = 3;

    private static $valueToName = [
        self::UnknownCertificateType => 'UnknownCertificateType',
        self::TokenCertificateType => 'TokenCertificateType',
        self::DssCertificateType => 'DssCertificateType',
        self::KonturCertificateType => 'KonturCertificateType',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

