<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: DocumentId.proto

namespace Diadoc\Api\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.DocumentId</code>
 */
class DocumentId extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional string MessageId = 1;</code>
     */
    protected $MessageId = null;
    /**
     * Generated from protobuf field <code>optional string EntityId = 2;</code>
     */
    protected $EntityId = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $MessageId
     *     @type string $EntityId
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\DocumentId::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string MessageId = 1;</code>
     * @return string
     */
    public function getMessageId()
    {
        return isset($this->MessageId) ? $this->MessageId : '';
    }

    public function hasMessageId()
    {
        return isset($this->MessageId);
    }

    public function clearMessageId()
    {
        unset($this->MessageId);
    }

    /**
     * Generated from protobuf field <code>optional string MessageId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMessageId($var)
    {
        GPBUtil::checkString($var, True);
        $this->MessageId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string EntityId = 2;</code>
     * @return string
     */
    public function getEntityId()
    {
        return isset($this->EntityId) ? $this->EntityId : '';
    }

    public function hasEntityId()
    {
        return isset($this->EntityId);
    }

    public function clearEntityId()
    {
        unset($this->EntityId);
    }

    /**
     * Generated from protobuf field <code>optional string EntityId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setEntityId($var)
    {
        GPBUtil::checkString($var, True);
        $this->EntityId = $var;

        return $this;
    }

}

