<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: OuterDocflows/OuterDocflow.proto

namespace GPBMetadata\OuterDocflows;

class OuterDocflow
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\OuterDocflows\OuterDocflowStatus::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xD9\x01\x0A OuterDocflows/OuterDocflow.proto\x12\x1EDiadoc.Api.Proto.OuterDocflows\"\x7F\x0A\x10OuterDocflowInfo\x12\x16\x0A\x0EDocflowNamedId\x18\x01 \x01(\x09\x12\x1B\x0A\x13DocflowFriendlyName\x18\x02 \x01(\x09\x126\x0A\x06Status\x18\x03 \x01(\x0B2&.Diadoc.Api.Proto.OuterDocflows.StatusB\x14B\x12OuterDocflowProtos"
        , true);

        static::$is_initialized = true;
    }
}

