<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Departments/Department.proto

namespace Diadoc\Proto\Departments;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.Departments.Department</code>
 */
class Department extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional string Id = 1;</code>
     */
    protected $Id = null;
    /**
     * Generated from protobuf field <code>optional string ParentDepartmentId = 2;</code>
     */
    protected $ParentDepartmentId = null;
    /**
     * Generated from protobuf field <code>optional string Name = 3;</code>
     */
    protected $Name = null;
    /**
     * Generated from protobuf field <code>optional string Abbreviation = 4;</code>
     */
    protected $Abbreviation = null;
    /**
     * Generated from protobuf field <code>optional string Kpp = 5;</code>
     */
    protected $Kpp = null;
    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Address Address = 6;</code>
     */
    protected $Address = null;
    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Departments.Routing Routing = 7;</code>
     */
    protected $Routing = null;
    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Timestamp CreationTimestamp = 8;</code>
     */
    protected $CreationTimestamp = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Id
     *     @type string $ParentDepartmentId
     *     @type string $Name
     *     @type string $Abbreviation
     *     @type string $Kpp
     *     @type \Diadoc\Api\Proto\Address $Address
     *     @type \Diadoc\Api\Proto\Departments\Routing $Routing
     *     @type \Diadoc\Api\Proto\Timestamp $CreationTimestamp
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Departments\Department::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string Id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return isset($this->Id) ? $this->Id : '';
    }

    public function hasId()
    {
        return isset($this->Id);
    }

    public function clearId()
    {
        unset($this->Id);
    }

    /**
     * Generated from protobuf field <code>optional string Id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->Id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string ParentDepartmentId = 2;</code>
     * @return string
     */
    public function getParentDepartmentId()
    {
        return isset($this->ParentDepartmentId) ? $this->ParentDepartmentId : '';
    }

    public function hasParentDepartmentId()
    {
        return isset($this->ParentDepartmentId);
    }

    public function clearParentDepartmentId()
    {
        unset($this->ParentDepartmentId);
    }

    /**
     * Generated from protobuf field <code>optional string ParentDepartmentId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setParentDepartmentId($var)
    {
        GPBUtil::checkString($var, True);
        $this->ParentDepartmentId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string Name = 3;</code>
     * @return string
     */
    public function getName()
    {
        return isset($this->Name) ? $this->Name : '';
    }

    public function hasName()
    {
        return isset($this->Name);
    }

    public function clearName()
    {
        unset($this->Name);
    }

    /**
     * Generated from protobuf field <code>optional string Name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->Name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string Abbreviation = 4;</code>
     * @return string
     */
    public function getAbbreviation()
    {
        return isset($this->Abbreviation) ? $this->Abbreviation : '';
    }

    public function hasAbbreviation()
    {
        return isset($this->Abbreviation);
    }

    public function clearAbbreviation()
    {
        unset($this->Abbreviation);
    }

    /**
     * Generated from protobuf field <code>optional string Abbreviation = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setAbbreviation($var)
    {
        GPBUtil::checkString($var, True);
        $this->Abbreviation = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string Kpp = 5;</code>
     * @return string
     */
    public function getKpp()
    {
        return isset($this->Kpp) ? $this->Kpp : '';
    }

    public function hasKpp()
    {
        return isset($this->Kpp);
    }

    public function clearKpp()
    {
        unset($this->Kpp);
    }

    /**
     * Generated from protobuf field <code>optional string Kpp = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setKpp($var)
    {
        GPBUtil::checkString($var, True);
        $this->Kpp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Address Address = 6;</code>
     * @return \Diadoc\Api\Proto\Address|null
     */
    public function getAddress()
    {
        return $this->Address;
    }

    public function hasAddress()
    {
        return isset($this->Address);
    }

    public function clearAddress()
    {
        unset($this->Address);
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Address Address = 6;</code>
     * @param \Diadoc\Api\Proto\Address $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\Address::class);
        $this->Address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Departments.Routing Routing = 7;</code>
     * @return \Diadoc\Api\Proto\Departments\Routing|null
     */
    public function getRouting()
    {
        return $this->Routing;
    }

    public function hasRouting()
    {
        return isset($this->Routing);
    }

    public function clearRouting()
    {
        unset($this->Routing);
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Departments.Routing Routing = 7;</code>
     * @param \Diadoc\Api\Proto\Departments\Routing $var
     * @return $this
     */
    public function setRouting($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\Departments\Routing::class);
        $this->Routing = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Timestamp CreationTimestamp = 8;</code>
     * @return \Diadoc\Api\Proto\Timestamp|null
     */
    public function getCreationTimestamp()
    {
        return $this->CreationTimestamp;
    }

    public function hasCreationTimestamp()
    {
        return isset($this->CreationTimestamp);
    }

    public function clearCreationTimestamp()
    {
        unset($this->CreationTimestamp);
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Timestamp CreationTimestamp = 8;</code>
     * @param \Diadoc\Api\Proto\Timestamp $var
     * @return $this
     */
    public function setCreationTimestamp($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\Timestamp::class);
        $this->CreationTimestamp = $var;

        return $this;
    }

}

