<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Departments/DepartmentToUpdate.proto

namespace Diadoc\Api\Proto\Departments;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.Departments.DepartmentRoutingPatch</code>
 */
class DepartmentRoutingPatch extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional bool Kpp = 1;</code>
     */
    protected $Kpp = null;
    /**
     * Generated from protobuf field <code>optional bool Address = 2;</code>
     */
    protected $Address = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $Kpp
     *     @type bool $Address
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Departments\DepartmentToUpdate::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional bool Kpp = 1;</code>
     * @return bool
     */
    public function getKpp()
    {
        return isset($this->Kpp) ? $this->Kpp : false;
    }

    public function hasKpp()
    {
        return isset($this->Kpp);
    }

    public function clearKpp()
    {
        unset($this->Kpp);
    }

    /**
     * Generated from protobuf field <code>optional bool Kpp = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setKpp($var)
    {
        GPBUtil::checkBool($var);
        $this->Kpp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool Address = 2;</code>
     * @return bool
     */
    public function getAddress()
    {
        return isset($this->Address) ? $this->Address : false;
    }

    public function hasAddress()
    {
        return isset($this->Address);
    }

    public function clearAddress()
    {
        unset($this->Address);
    }

    /**
     * Generated from protobuf field <code>optional bool Address = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkBool($var);
        $this->Address = $var;

        return $this;
    }

}

