<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Documents/DetectTitleResponse.proto

namespace GPBMetadata\Documents;

class DetectTitleResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Events\DiadocMessagePostApi::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xDF\x02\x0A#Documents/DetectTitleResponse.proto\x12\x1ADiadoc.Api.Proto.Documents\"`\x0A\x13DetectTitleResponse\x12I\x0A\x0EDocumentTitles\x18\x01 \x03(\x0B21.Diadoc.Api.Proto.Documents.DetectedDocumentTitle\"\x9C\x01\x0A\x15DetectedDocumentTitle\x12\x13\x0A\x0BTypeNamedId\x18\x01 \x01(\x09\x12\x10\x0A\x08Function\x18\x02 \x01(\x09\x12\x0F\x0A\x07Version\x18\x03 \x01(\x09\x12\x12\x0A\x0ATitleIndex\x18\x04 \x01(\x05\x127\x0A\x08Metadata\x18\x05 \x03(\x0B2%.Diadoc.Api.Proto.Events.MetadataItemB\x1BB\x19DetectTitleResponseProtos"
        , true);

        static::$is_initialized = true;
    }
}

