<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Documents/DocumentList.proto

namespace GPBMetadata\Documents;

class DocumentList
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Documents\Document::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xC5\x01\x0A\x1CDocuments/DocumentList.proto\x12\x1ADiadoc.Api.Proto.Documents\"s\x0A\x0CDocumentList\x12\x12\x0A\x0ATotalCount\x18\x01 \x01(\x05\x127\x0A\x09Documents\x18\x02 \x03(\x0B2\$.Diadoc.Api.Proto.Documents.Document\x12\x16\x0A\x0EHasMoreResults\x18\x03 \x01(\x08B\x14B\x12DocumentListProtos"
        , true);

        static::$is_initialized = true;
    }
}

