<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Documents/DocumentZip.proto

namespace GPBMetadata\Documents;

class DocumentZip
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\x89\x01\x0A\x1BDocuments/DocumentZip.proto\x12\x1ADiadoc.Api.Proto.Documents\"9\x0A\x1BDocumentZipGenerationResult\x12\x1A\x0A\x12ZipFileNameOnShelf\x18\x01 \x01(\x09B\x13B\x11DocumentZipProtos"
        , true);

        static::$is_initialized = true;
    }
}

