<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Employees/Subscriptions/Subscription.proto

namespace GPBMetadata\Employees\Subscriptions;

class Subscription
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xEE\x02\x0A*Employees/Subscriptions/Subscription.proto\x12(Diadoc.Api.Proto.Employees.Subscriptions\"f\x0A\x15EmployeeSubscriptions\x12M\x0A\x0DSubscriptions\x18\x01 \x03(\x0B26.Diadoc.Api.Proto.Employees.Subscriptions.Subscription\"f\x0A\x15SubscriptionsToUpdate\x12M\x0A\x0DSubscriptions\x18\x01 \x03(\x0B26.Diadoc.Api.Proto.Employees.Subscriptions.Subscription\"0\x0A\x0CSubscription\x12\x0A\x0A\x02Id\x18\x01 \x01(\x09\x12\x14\x0A\x0CIsSubscribed\x18\x02 \x01(\x08B\x14B\x12SubscriptionProtos"
        , true);

        static::$is_initialized = true;
    }
}

