<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: KeyValueStorage/KeyValueStorage.proto

namespace GPBMetadata\KeyValueStorage;

class KeyValueStorage
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\x97\x03\x0A%KeyValueStorage/KeyValueStorage.proto\x12 Diadoc.Api.Proto.KeyValueStorage\"2\x0A\x14KeyValueStorageEntry\x12\x0B\x0A\x03Key\x18\x01 \x01(\x09\x12\x0D\x0A\x05Value\x18\x02 \x01(\x09\",\x0A\x1CKeyValueStorageApiGetRequest\x12\x0C\x0A\x04Keys\x18\x01 \x03(\x09\"h\x0A\x1DKeyValueStorageApiGetResponse\x12G\x0A\x07Entries\x18\x01 \x03(\x0B26.Diadoc.Api.Proto.KeyValueStorage.KeyValueStorageEntry\"g\x0A\x1CKeyValueStorageApiPutRequest\x12G\x0A\x07Entries\x18\x01 \x03(\x0B26.Diadoc.Api.Proto.KeyValueStorage.KeyValueStorageEntryB\x17B\x15KeyValueStorageProtos"
        , true);

        static::$is_initialized = true;
    }
}

