<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Invoicing/AcceptanceCertificateInfo.proto

namespace Diadoc\Proto\Invoicing;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Со стороны исполнителя
 *
 * Generated from protobuf message <code>Diadoc.Api.Proto.Invoicing.AcceptanceCertificateSellerTitleInfo</code>
 */
class AcceptanceCertificateSellerTitleInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * исполнитель (продавец услуг)
     *
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.DiadocOrganizationInfo Seller = 1;</code>
     */
    protected $Seller = null;
    /**
     * заказчик (покупатель услуг)
     *
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.DocflowParticipant Buyer = 2;</code>
     */
    protected $Buyer = null;
    /**
     * дата составления акта о выполнении
     *
     * Generated from protobuf field <code>optional string DocumentDate = 3;</code>
     */
    protected $DocumentDate = null;
    /**
     * номер акта
     *
     * Generated from protobuf field <code>optional string DocumentNumber = 4;</code>
     */
    protected $DocumentNumber = null;
    /**
     * заголовок документа
     *
     * Generated from protobuf field <code>optional string DocumentTitle = 5;</code>
     */
    protected $DocumentTitle = null;
    /**
     * описание выполненных работ
     *
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.Invoicing.WorkDescription Works = 6;</code>
     */
    private $Works;
    /**
     * сведения о подписи акта
     *
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.AcceptanceCertificateSignatureInfo Signature = 7;</code>
     */
    protected $Signature = null;
    /**
     * подписант
     *
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.Signer Signer = 8;</code>
     */
    protected $Signer = null;
    /**
     * дополнительная информация
     *
     * Generated from protobuf field <code>optional string AdditionalInfo = 9;</code>
     */
    protected $AdditionalInfo = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Diadoc\Api\Proto\Invoicing\DiadocOrganizationInfo $Seller
     *           исполнитель (продавец услуг)
     *     @type \Diadoc\Api\Proto\Invoicing\DocflowParticipant $Buyer
     *           заказчик (покупатель услуг)
     *     @type string $DocumentDate
     *           дата составления акта о выполнении
     *     @type string $DocumentNumber
     *           номер акта
     *     @type string $DocumentTitle
     *           заголовок документа
     *     @type array<\Diadoc\Api\Proto\Invoicing\WorkDescription>|\Google\Protobuf\Internal\RepeatedField $Works
     *           описание выполненных работ
     *     @type \Diadoc\Api\Proto\Invoicing\AcceptanceCertificateSignatureInfo $Signature
     *           сведения о подписи акта
     *     @type \Diadoc\Api\Proto\Invoicing\Signer $Signer
     *           подписант
     *     @type string $AdditionalInfo
     *           дополнительная информация
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Invoicing\AcceptanceCertificateInfo::initOnce();
        parent::__construct($data);
    }

    /**
     * исполнитель (продавец услуг)
     *
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.DiadocOrganizationInfo Seller = 1;</code>
     * @return \Diadoc\Api\Proto\Invoicing\DiadocOrganizationInfo|null
     */
    public function getSeller()
    {
        return $this->Seller;
    }

    public function hasSeller()
    {
        return isset($this->Seller);
    }

    public function clearSeller()
    {
        unset($this->Seller);
    }

    /**
     * исполнитель (продавец услуг)
     *
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.DiadocOrganizationInfo Seller = 1;</code>
     * @param \Diadoc\Api\Proto\Invoicing\DiadocOrganizationInfo $var
     * @return $this
     */
    public function setSeller($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\Invoicing\DiadocOrganizationInfo::class);
        $this->Seller = $var;

        return $this;
    }

    /**
     * заказчик (покупатель услуг)
     *
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.DocflowParticipant Buyer = 2;</code>
     * @return \Diadoc\Api\Proto\Invoicing\DocflowParticipant|null
     */
    public function getBuyer()
    {
        return $this->Buyer;
    }

    public function hasBuyer()
    {
        return isset($this->Buyer);
    }

    public function clearBuyer()
    {
        unset($this->Buyer);
    }

    /**
     * заказчик (покупатель услуг)
     *
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.DocflowParticipant Buyer = 2;</code>
     * @param \Diadoc\Api\Proto\Invoicing\DocflowParticipant $var
     * @return $this
     */
    public function setBuyer($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\Invoicing\DocflowParticipant::class);
        $this->Buyer = $var;

        return $this;
    }

    /**
     * дата составления акта о выполнении
     *
     * Generated from protobuf field <code>optional string DocumentDate = 3;</code>
     * @return string
     */
    public function getDocumentDate()
    {
        return isset($this->DocumentDate) ? $this->DocumentDate : '';
    }

    public function hasDocumentDate()
    {
        return isset($this->DocumentDate);
    }

    public function clearDocumentDate()
    {
        unset($this->DocumentDate);
    }

    /**
     * дата составления акта о выполнении
     *
     * Generated from protobuf field <code>optional string DocumentDate = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDocumentDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->DocumentDate = $var;

        return $this;
    }

    /**
     * номер акта
     *
     * Generated from protobuf field <code>optional string DocumentNumber = 4;</code>
     * @return string
     */
    public function getDocumentNumber()
    {
        return isset($this->DocumentNumber) ? $this->DocumentNumber : '';
    }

    public function hasDocumentNumber()
    {
        return isset($this->DocumentNumber);
    }

    public function clearDocumentNumber()
    {
        unset($this->DocumentNumber);
    }

    /**
     * номер акта
     *
     * Generated from protobuf field <code>optional string DocumentNumber = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setDocumentNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->DocumentNumber = $var;

        return $this;
    }

    /**
     * заголовок документа
     *
     * Generated from protobuf field <code>optional string DocumentTitle = 5;</code>
     * @return string
     */
    public function getDocumentTitle()
    {
        return isset($this->DocumentTitle) ? $this->DocumentTitle : '';
    }

    public function hasDocumentTitle()
    {
        return isset($this->DocumentTitle);
    }

    public function clearDocumentTitle()
    {
        unset($this->DocumentTitle);
    }

    /**
     * заголовок документа
     *
     * Generated from protobuf field <code>optional string DocumentTitle = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setDocumentTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->DocumentTitle = $var;

        return $this;
    }

    /**
     * описание выполненных работ
     *
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.Invoicing.WorkDescription Works = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getWorks()
    {
        return $this->Works;
    }

    /**
     * описание выполненных работ
     *
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.Invoicing.WorkDescription Works = 6;</code>
     * @param array<\Diadoc\Api\Proto\Invoicing\WorkDescription>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setWorks($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Diadoc\Api\Proto\Invoicing\WorkDescription::class);
        $this->Works = $arr;

        return $this;
    }

    /**
     * сведения о подписи акта
     *
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.AcceptanceCertificateSignatureInfo Signature = 7;</code>
     * @return \Diadoc\Api\Proto\Invoicing\AcceptanceCertificateSignatureInfo|null
     */
    public function getSignature()
    {
        return $this->Signature;
    }

    public function hasSignature()
    {
        return isset($this->Signature);
    }

    public function clearSignature()
    {
        unset($this->Signature);
    }

    /**
     * сведения о подписи акта
     *
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.AcceptanceCertificateSignatureInfo Signature = 7;</code>
     * @param \Diadoc\Api\Proto\Invoicing\AcceptanceCertificateSignatureInfo $var
     * @return $this
     */
    public function setSignature($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\Invoicing\AcceptanceCertificateSignatureInfo::class);
        $this->Signature = $var;

        return $this;
    }

    /**
     * подписант
     *
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.Signer Signer = 8;</code>
     * @return \Diadoc\Api\Proto\Invoicing\Signer|null
     */
    public function getSigner()
    {
        return $this->Signer;
    }

    public function hasSigner()
    {
        return isset($this->Signer);
    }

    public function clearSigner()
    {
        unset($this->Signer);
    }

    /**
     * подписант
     *
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.Signer Signer = 8;</code>
     * @param \Diadoc\Api\Proto\Invoicing\Signer $var
     * @return $this
     */
    public function setSigner($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\Invoicing\Signer::class);
        $this->Signer = $var;

        return $this;
    }

    /**
     * дополнительная информация
     *
     * Generated from protobuf field <code>optional string AdditionalInfo = 9;</code>
     * @return string
     */
    public function getAdditionalInfo()
    {
        return isset($this->AdditionalInfo) ? $this->AdditionalInfo : '';
    }

    public function hasAdditionalInfo()
    {
        return isset($this->AdditionalInfo);
    }

    public function clearAdditionalInfo()
    {
        unset($this->AdditionalInfo);
    }

    /**
     * дополнительная информация
     *
     * Generated from protobuf field <code>optional string AdditionalInfo = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setAdditionalInfo($var)
    {
        GPBUtil::checkString($var, True);
        $this->AdditionalInfo = $var;

        return $this;
    }

}

