<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Invoicing/AcceptanceCertificate552Info.proto

namespace Diadoc\Proto\Invoicing;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.Invoicing.AcceptanceCertificate552WorkDescription</code>
 */
class AcceptanceCertificate552WorkDescription extends \Google\Protobuf\Internal\Message
{
    /**
     * начало периода выполнения работ // НачРабот
     *
     * Generated from protobuf field <code>optional string StartingDate = 1;</code>
     */
    protected $StartingDate = null;
    /**
     * окончание периода выполнения работ // КонРабот
     *
     * Generated from protobuf field <code>optional string CompletionDate = 2;</code>
     */
    protected $CompletionDate = null;
    /**
     * сумма без учета НДС - итого // СтБезНДСИт
     *
     * Generated from protobuf field <code>optional string TotalWithVatExcluded = 3;</code>
     */
    protected $TotalWithVatExcluded = null;
    /**
     * сумма НДС - итого // СумНДСИт
     *
     * Generated from protobuf field <code>optional string TotalVat = 4;</code>
     */
    protected $TotalVat = null;
    /**
     * сумма с учетом НДС - итого // СтУчНДСИт
     *
     * Generated from protobuf field <code>optional string Total = 5;</code>
     */
    protected $Total = null;
    /**
     * сведения о произведенной работе // Работа
     *
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.Invoicing.AcceptanceCertificate552WorkItem Items = 6;</code>
     */
    private $Items;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $StartingDate
     *           начало периода выполнения работ // НачРабот
     *     @type string $CompletionDate
     *           окончание периода выполнения работ // КонРабот
     *     @type string $TotalWithVatExcluded
     *           сумма без учета НДС - итого // СтБезНДСИт
     *     @type string $TotalVat
     *           сумма НДС - итого // СумНДСИт
     *     @type string $Total
     *           сумма с учетом НДС - итого // СтУчНДСИт
     *     @type array<\Diadoc\Api\Proto\Invoicing\AcceptanceCertificate552WorkItem>|\Google\Protobuf\Internal\RepeatedField $Items
     *           сведения о произведенной работе // Работа
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Invoicing\AcceptanceCertificate552Info::initOnce();
        parent::__construct($data);
    }

    /**
     * начало периода выполнения работ // НачРабот
     *
     * Generated from protobuf field <code>optional string StartingDate = 1;</code>
     * @return string
     */
    public function getStartingDate()
    {
        return isset($this->StartingDate) ? $this->StartingDate : '';
    }

    public function hasStartingDate()
    {
        return isset($this->StartingDate);
    }

    public function clearStartingDate()
    {
        unset($this->StartingDate);
    }

    /**
     * начало периода выполнения работ // НачРабот
     *
     * Generated from protobuf field <code>optional string StartingDate = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setStartingDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->StartingDate = $var;

        return $this;
    }

    /**
     * окончание периода выполнения работ // КонРабот
     *
     * Generated from protobuf field <code>optional string CompletionDate = 2;</code>
     * @return string
     */
    public function getCompletionDate()
    {
        return isset($this->CompletionDate) ? $this->CompletionDate : '';
    }

    public function hasCompletionDate()
    {
        return isset($this->CompletionDate);
    }

    public function clearCompletionDate()
    {
        unset($this->CompletionDate);
    }

    /**
     * окончание периода выполнения работ // КонРабот
     *
     * Generated from protobuf field <code>optional string CompletionDate = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCompletionDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->CompletionDate = $var;

        return $this;
    }

    /**
     * сумма без учета НДС - итого // СтБезНДСИт
     *
     * Generated from protobuf field <code>optional string TotalWithVatExcluded = 3;</code>
     * @return string
     */
    public function getTotalWithVatExcluded()
    {
        return isset($this->TotalWithVatExcluded) ? $this->TotalWithVatExcluded : '';
    }

    public function hasTotalWithVatExcluded()
    {
        return isset($this->TotalWithVatExcluded);
    }

    public function clearTotalWithVatExcluded()
    {
        unset($this->TotalWithVatExcluded);
    }

    /**
     * сумма без учета НДС - итого // СтБезНДСИт
     *
     * Generated from protobuf field <code>optional string TotalWithVatExcluded = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setTotalWithVatExcluded($var)
    {
        GPBUtil::checkString($var, True);
        $this->TotalWithVatExcluded = $var;

        return $this;
    }

    /**
     * сумма НДС - итого // СумНДСИт
     *
     * Generated from protobuf field <code>optional string TotalVat = 4;</code>
     * @return string
     */
    public function getTotalVat()
    {
        return isset($this->TotalVat) ? $this->TotalVat : '';
    }

    public function hasTotalVat()
    {
        return isset($this->TotalVat);
    }

    public function clearTotalVat()
    {
        unset($this->TotalVat);
    }

    /**
     * сумма НДС - итого // СумНДСИт
     *
     * Generated from protobuf field <code>optional string TotalVat = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setTotalVat($var)
    {
        GPBUtil::checkString($var, True);
        $this->TotalVat = $var;

        return $this;
    }

    /**
     * сумма с учетом НДС - итого // СтУчНДСИт
     *
     * Generated from protobuf field <code>optional string Total = 5;</code>
     * @return string
     */
    public function getTotal()
    {
        return isset($this->Total) ? $this->Total : '';
    }

    public function hasTotal()
    {
        return isset($this->Total);
    }

    public function clearTotal()
    {
        unset($this->Total);
    }

    /**
     * сумма с учетом НДС - итого // СтУчНДСИт
     *
     * Generated from protobuf field <code>optional string Total = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setTotal($var)
    {
        GPBUtil::checkString($var, True);
        $this->Total = $var;

        return $this;
    }

    /**
     * сведения о произведенной работе // Работа
     *
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.Invoicing.AcceptanceCertificate552WorkItem Items = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getItems()
    {
        return $this->Items;
    }

    /**
     * сведения о произведенной работе // Работа
     *
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.Invoicing.AcceptanceCertificate552WorkItem Items = 6;</code>
     * @param array<\Diadoc\Api\Proto\Invoicing\AcceptanceCertificate552WorkItem>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setItems($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Diadoc\Api\Proto\Invoicing\AcceptanceCertificate552WorkItem::class);
        $this->Items = $arr;

        return $this;
    }

}

