<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Invoicing/OrganizationInfo.proto

namespace Diadoc\Api\Proto\Invoicing;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.Invoicing.DocflowParticipant</code>
 */
class DocflowParticipant extends \Google\Protobuf\Internal\Message
{
    /**
     * идентификатор ящика в Диадоке
     *
     * Generated from protobuf field <code>optional string BoxId = 1;</code>
     */
    protected $BoxId = null;
    /**
     * ИНН организации-участника обмена
     *
     * Generated from protobuf field <code>optional string Inn = 2;</code>
     */
    protected $Inn = null;
    /**
     * КПП организации-участника обмена
     *
     * Generated from protobuf field <code>optional string Kpp = 3;</code>
     */
    protected $Kpp = null;
    /**
     * идентификатор участника ЭДО
     *
     * Generated from protobuf field <code>optional string FnsParticipantId = 4;</code>
     */
    protected $FnsParticipantId = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $BoxId
     *           идентификатор ящика в Диадоке
     *     @type string $Inn
     *           ИНН организации-участника обмена
     *     @type string $Kpp
     *           КПП организации-участника обмена
     *     @type string $FnsParticipantId
     *           идентификатор участника ЭДО
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Invoicing\OrganizationInfo::initOnce();
        parent::__construct($data);
    }

    /**
     * идентификатор ящика в Диадоке
     *
     * Generated from protobuf field <code>optional string BoxId = 1;</code>
     * @return string
     */
    public function getBoxId()
    {
        return isset($this->BoxId) ? $this->BoxId : '';
    }

    public function hasBoxId()
    {
        return isset($this->BoxId);
    }

    public function clearBoxId()
    {
        unset($this->BoxId);
    }

    /**
     * идентификатор ящика в Диадоке
     *
     * Generated from protobuf field <code>optional string BoxId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setBoxId($var)
    {
        GPBUtil::checkString($var, True);
        $this->BoxId = $var;

        return $this;
    }

    /**
     * ИНН организации-участника обмена
     *
     * Generated from protobuf field <code>optional string Inn = 2;</code>
     * @return string
     */
    public function getInn()
    {
        return isset($this->Inn) ? $this->Inn : '';
    }

    public function hasInn()
    {
        return isset($this->Inn);
    }

    public function clearInn()
    {
        unset($this->Inn);
    }

    /**
     * ИНН организации-участника обмена
     *
     * Generated from protobuf field <code>optional string Inn = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setInn($var)
    {
        GPBUtil::checkString($var, True);
        $this->Inn = $var;

        return $this;
    }

    /**
     * КПП организации-участника обмена
     *
     * Generated from protobuf field <code>optional string Kpp = 3;</code>
     * @return string
     */
    public function getKpp()
    {
        return isset($this->Kpp) ? $this->Kpp : '';
    }

    public function hasKpp()
    {
        return isset($this->Kpp);
    }

    public function clearKpp()
    {
        unset($this->Kpp);
    }

    /**
     * КПП организации-участника обмена
     *
     * Generated from protobuf field <code>optional string Kpp = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setKpp($var)
    {
        GPBUtil::checkString($var, True);
        $this->Kpp = $var;

        return $this;
    }

    /**
     * идентификатор участника ЭДО
     *
     * Generated from protobuf field <code>optional string FnsParticipantId = 4;</code>
     * @return string
     */
    public function getFnsParticipantId()
    {
        return isset($this->FnsParticipantId) ? $this->FnsParticipantId : '';
    }

    public function hasFnsParticipantId()
    {
        return isset($this->FnsParticipantId);
    }

    public function clearFnsParticipantId()
    {
        unset($this->FnsParticipantId);
    }

    /**
     * идентификатор участника ЭДО
     *
     * Generated from protobuf field <code>optional string FnsParticipantId = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setFnsParticipantId($var)
    {
        GPBUtil::checkString($var, True);
        $this->FnsParticipantId = $var;

        return $this;
    }

}

