<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Invoicing/Torg12Info.proto

namespace Diadoc\Proto\Invoicing;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Документ-основание
 *
 * Generated from protobuf message <code>Diadoc.Api.Proto.Invoicing.Grounds</code>
 */
class Grounds extends \Google\Protobuf\Internal\Message
{
    /**
     * имя документа
     *
     * Generated from protobuf field <code>optional string DocumentName = 1;</code>
     */
    protected $DocumentName = null;
    /**
     * номер документа
     *
     * Generated from protobuf field <code>optional string DocumentNumber = 2;</code>
     */
    protected $DocumentNumber = null;
    /**
     * дата документа
     *
     * Generated from protobuf field <code>optional string DocumentDate = 3;</code>
     */
    protected $DocumentDate = null;
    /**
     * дополнительные сведения
     *
     * Generated from protobuf field <code>optional string AdditionalInfo = 4;</code>
     */
    protected $AdditionalInfo = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $DocumentName
     *           имя документа
     *     @type string $DocumentNumber
     *           номер документа
     *     @type string $DocumentDate
     *           дата документа
     *     @type string $AdditionalInfo
     *           дополнительные сведения
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Invoicing\Torg12Info::initOnce();
        parent::__construct($data);
    }

    /**
     * имя документа
     *
     * Generated from protobuf field <code>optional string DocumentName = 1;</code>
     * @return string
     */
    public function getDocumentName()
    {
        return isset($this->DocumentName) ? $this->DocumentName : '';
    }

    public function hasDocumentName()
    {
        return isset($this->DocumentName);
    }

    public function clearDocumentName()
    {
        unset($this->DocumentName);
    }

    /**
     * имя документа
     *
     * Generated from protobuf field <code>optional string DocumentName = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDocumentName($var)
    {
        GPBUtil::checkString($var, True);
        $this->DocumentName = $var;

        return $this;
    }

    /**
     * номер документа
     *
     * Generated from protobuf field <code>optional string DocumentNumber = 2;</code>
     * @return string
     */
    public function getDocumentNumber()
    {
        return isset($this->DocumentNumber) ? $this->DocumentNumber : '';
    }

    public function hasDocumentNumber()
    {
        return isset($this->DocumentNumber);
    }

    public function clearDocumentNumber()
    {
        unset($this->DocumentNumber);
    }

    /**
     * номер документа
     *
     * Generated from protobuf field <code>optional string DocumentNumber = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDocumentNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->DocumentNumber = $var;

        return $this;
    }

    /**
     * дата документа
     *
     * Generated from protobuf field <code>optional string DocumentDate = 3;</code>
     * @return string
     */
    public function getDocumentDate()
    {
        return isset($this->DocumentDate) ? $this->DocumentDate : '';
    }

    public function hasDocumentDate()
    {
        return isset($this->DocumentDate);
    }

    public function clearDocumentDate()
    {
        unset($this->DocumentDate);
    }

    /**
     * дата документа
     *
     * Generated from protobuf field <code>optional string DocumentDate = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDocumentDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->DocumentDate = $var;

        return $this;
    }

    /**
     * дополнительные сведения
     *
     * Generated from protobuf field <code>optional string AdditionalInfo = 4;</code>
     * @return string
     */
    public function getAdditionalInfo()
    {
        return isset($this->AdditionalInfo) ? $this->AdditionalInfo : '';
    }

    public function hasAdditionalInfo()
    {
        return isset($this->AdditionalInfo);
    }

    public function clearAdditionalInfo()
    {
        unset($this->AdditionalInfo);
    }

    /**
     * дополнительные сведения
     *
     * Generated from protobuf field <code>optional string AdditionalInfo = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setAdditionalInfo($var)
    {
        GPBUtil::checkString($var, True);
        $this->AdditionalInfo = $var;

        return $this;
    }

}

