<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Invoicing/InvoiceCorrectionRequestInfo.proto

namespace Diadoc\Api\Proto\Invoicing;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.Invoicing.InvoiceCorrectionRequestInfo</code>
 */
class InvoiceCorrectionRequestInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional string ErrorMessage = 1;</code>
     */
    protected $ErrorMessage = null;
    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.Signer Signer = 2;</code>
     */
    protected $Signer = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $ErrorMessage
     *     @type \Diadoc\Api\Proto\Invoicing\Signer $Signer
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Invoicing\InvoiceCorrectionRequestInfo::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string ErrorMessage = 1;</code>
     * @return string
     */
    public function getErrorMessage()
    {
        return isset($this->ErrorMessage) ? $this->ErrorMessage : '';
    }

    public function hasErrorMessage()
    {
        return isset($this->ErrorMessage);
    }

    public function clearErrorMessage()
    {
        unset($this->ErrorMessage);
    }

    /**
     * Generated from protobuf field <code>optional string ErrorMessage = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setErrorMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->ErrorMessage = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.Signer Signer = 2;</code>
     * @return \Diadoc\Api\Proto\Invoicing\Signer|null
     */
    public function getSigner()
    {
        return $this->Signer;
    }

    public function hasSigner()
    {
        return isset($this->Signer);
    }

    public function clearSigner()
    {
        unset($this->Signer);
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.Signer Signer = 2;</code>
     * @param \Diadoc\Api\Proto\Invoicing\Signer $var
     * @return $this
     */
    public function setSigner($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\Invoicing\Signer::class);
        $this->Signer = $var;

        return $this;
    }

}

