<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Invoicing/SignatureRejectionInfo.proto

namespace Diadoc\Proto\Invoicing;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.Invoicing.SignatureRejectionGenerationRequestV2</code>
 */
class SignatureRejectionGenerationRequestV2 extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional string ErrorMessage = 1;</code>
     */
    protected $ErrorMessage = null;
    /**
     * Generated from protobuf field <code>optional string MessageId = 2;</code>
     */
    protected $MessageId = null;
    /**
     * Generated from protobuf field <code>optional string AttachmentId = 3;</code>
     */
    protected $AttachmentId = null;
    /**
     * Generated from protobuf field <code>optional bytes SignerContent = 4;</code>
     */
    protected $SignerContent = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $ErrorMessage
     *     @type string $MessageId
     *     @type string $AttachmentId
     *     @type string $SignerContent
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Invoicing\SignatureRejectionInfo::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string ErrorMessage = 1;</code>
     * @return string
     */
    public function getErrorMessage()
    {
        return isset($this->ErrorMessage) ? $this->ErrorMessage : '';
    }

    public function hasErrorMessage()
    {
        return isset($this->ErrorMessage);
    }

    public function clearErrorMessage()
    {
        unset($this->ErrorMessage);
    }

    /**
     * Generated from protobuf field <code>optional string ErrorMessage = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setErrorMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->ErrorMessage = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string MessageId = 2;</code>
     * @return string
     */
    public function getMessageId()
    {
        return isset($this->MessageId) ? $this->MessageId : '';
    }

    public function hasMessageId()
    {
        return isset($this->MessageId);
    }

    public function clearMessageId()
    {
        unset($this->MessageId);
    }

    /**
     * Generated from protobuf field <code>optional string MessageId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMessageId($var)
    {
        GPBUtil::checkString($var, True);
        $this->MessageId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string AttachmentId = 3;</code>
     * @return string
     */
    public function getAttachmentId()
    {
        return isset($this->AttachmentId) ? $this->AttachmentId : '';
    }

    public function hasAttachmentId()
    {
        return isset($this->AttachmentId);
    }

    public function clearAttachmentId()
    {
        unset($this->AttachmentId);
    }

    /**
     * Generated from protobuf field <code>optional string AttachmentId = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setAttachmentId($var)
    {
        GPBUtil::checkString($var, True);
        $this->AttachmentId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bytes SignerContent = 4;</code>
     * @return string
     */
    public function getSignerContent()
    {
        return isset($this->SignerContent) ? $this->SignerContent : '';
    }

    public function hasSignerContent()
    {
        return isset($this->SignerContent);
    }

    public function clearSignerContent()
    {
        unset($this->SignerContent);
    }

    /**
     * Generated from protobuf field <code>optional bytes SignerContent = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSignerContent($var)
    {
        GPBUtil::checkString($var, False);
        $this->SignerContent = $var;

        return $this;
    }

}

