<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Invoicing/Torg12Info.proto

namespace Diadoc\Api\Proto\Invoicing;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Со стороны продавца
 *
 * Generated from protobuf message <code>Diadoc.Api.Proto.Invoicing.Torg12SellerTitleInfo</code>
 */
class Torg12SellerTitleInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * дата товарной накладной
     *
     * Generated from protobuf field <code>optional string DocumentDate = 1;</code>
     */
    protected $DocumentDate = null;
    /**
     * номер товарной накладной
     *
     * Generated from protobuf field <code>optional string DocumentNumber = 2;</code>
     */
    protected $DocumentNumber = null;
    /**
     * участник документооборота, отпустивший товар
     *
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.DocflowParticipant SellerDocflowParticipant = 3;</code>
     */
    protected $SellerDocflowParticipant = null;
    /**
     * участник документооборота, которому отпущен товар
     *
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.DocflowParticipant BuyerDocflowParticipant = 4;</code>
     */
    protected $BuyerDocflowParticipant = null;
    /**
     * грузоотправитель
     *
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.OrganizationInfo Shipper = 5;</code>
     */
    protected $Shipper = null;
    /**
     * грузополучатель
     *
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.OrganizationInfo Consignee = 6;</code>
     */
    protected $Consignee = null;
    /**
     * поставщик
     *
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.OrganizationInfo Supplier = 7;</code>
     */
    protected $Supplier = null;
    /**
     * плательщик
     *
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.OrganizationInfo Payer = 8;</code>
     */
    protected $Payer = null;
    /**
     * основание
     *
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.Grounds Grounds = 9;</code>
     */
    protected $Grounds = null;
    /**
     * дата составления транспортной накладной
     *
     * Generated from protobuf field <code>optional string WaybillDate = 10;</code>
     */
    protected $WaybillDate = null;
    /**
     * номер транспортной накладной
     *
     * Generated from protobuf field <code>optional string WaybillNumber = 11;</code>
     */
    protected $WaybillNumber = null;
    /**
     * код вида операции
     *
     * Generated from protobuf field <code>optional string OperationCode = 12;</code>
     */
    protected $OperationCode = null;
    /**
     * табличные сведения товарной накладной
     *
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.Invoicing.Torg12Item Items = 13;</code>
     */
    private $Items;
    /**
     * количество мест, штук - всего по накладной
     *
     * Generated from protobuf field <code>optional string ParcelsQuantityTotal = 14;</code>
     */
    protected $ParcelsQuantityTotal = null;
    /**
     * количество мест, штук - всего по накладной, прописью
     *
     * Generated from protobuf field <code>optional string ParcelsQuantityTotalInWords = 15;</code>
     */
    protected $ParcelsQuantityTotalInWords = null;
    /**
     * брутто - всего по накладной
     *
     * Generated from protobuf field <code>optional string GrossQuantityTotal = 16;</code>
     */
    protected $GrossQuantityTotal = null;
    /**
     * брутто - всего по накладной, прописью
     *
     * Generated from protobuf field <code>optional string GrossQuantityTotalInWords = 17;</code>
     */
    protected $GrossQuantityTotalInWords = null;
    /**
     * нетто - всего по накладной
     *
     * Generated from protobuf field <code>optional string NetQuantityTotal = 18;</code>
     */
    protected $NetQuantityTotal = null;
    /**
     * нетто - всего по накладной, прописью
     *
     * Generated from protobuf field <code>optional string NetQuantityTotalInWords = 19;</code>
     */
    protected $NetQuantityTotalInWords = null;
    /**
     * количество (масса нетто) - всего по накладной
     *
     * Generated from protobuf field <code>optional string QuantityTotal = 20;</code>
     */
    protected $QuantityTotal = null;
    /**
     * сумма без учета НДС - всего по накладной
     *
     * Generated from protobuf field <code>optional string TotalWithVatExcluded = 21;</code>
     */
    protected $TotalWithVatExcluded = null;
    /**
     * сумма НДС - всего по накладной
     *
     * Generated from protobuf field <code>optional string Vat = 22;</code>
     */
    protected $Vat = null;
    /**
     * сумма с учетом НДС - всего по накладной
     *
     * Generated from protobuf field <code>optional string Total = 23;</code>
     */
    protected $Total = null;
    /**
     * сумма с учетом НДС - всего по накладной, прописью
     *
     * Generated from protobuf field <code>optional string TotalInWords = 24;</code>
     */
    protected $TotalInWords = null;
    /**
     * дата отпуска
     *
     * Generated from protobuf field <code>optional string SupplyDate = 25;</code>
     */
    protected $SupplyDate = null;
    /**
     * отпуск разрешил
     *
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.Official SupplyAllowedBy = 26;</code>
     */
    protected $SupplyAllowedBy = null;
    /**
     * отпуск произвел
     *
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.Official SupplyPerformedBy = 27;</code>
     */
    protected $SupplyPerformedBy = null;
    /**
     * главный бухгалтер
     *
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.Official ChiefAccountant = 28;</code>
     */
    protected $ChiefAccountant = null;
    /**
     * подписант
     *
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.Signer Signer = 29;</code>
     */
    protected $Signer = null;
    /**
     * дополнительные сведения
     *
     * Generated from protobuf field <code>optional string AdditionalInfo = 30;</code>
     */
    protected $AdditionalInfo = null;
    /**
     * приложение, количество листов
     *
     * Generated from protobuf field <code>optional string AttachmentSheetsQuantity = 31;</code>
     */
    protected $AttachmentSheetsQuantity = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $DocumentDate
     *           дата товарной накладной
     *     @type string $DocumentNumber
     *           номер товарной накладной
     *     @type \Diadoc\Api\Proto\Invoicing\DocflowParticipant $SellerDocflowParticipant
     *           участник документооборота, отпустивший товар
     *     @type \Diadoc\Api\Proto\Invoicing\DocflowParticipant $BuyerDocflowParticipant
     *           участник документооборота, которому отпущен товар
     *     @type \Diadoc\Api\Proto\Invoicing\OrganizationInfo $Shipper
     *           грузоотправитель
     *     @type \Diadoc\Api\Proto\Invoicing\OrganizationInfo $Consignee
     *           грузополучатель
     *     @type \Diadoc\Api\Proto\Invoicing\OrganizationInfo $Supplier
     *           поставщик
     *     @type \Diadoc\Api\Proto\Invoicing\OrganizationInfo $Payer
     *           плательщик
     *     @type \Diadoc\Api\Proto\Invoicing\Grounds $Grounds
     *           основание
     *     @type string $WaybillDate
     *           дата составления транспортной накладной
     *     @type string $WaybillNumber
     *           номер транспортной накладной
     *     @type string $OperationCode
     *           код вида операции
     *     @type array<\Diadoc\Api\Proto\Invoicing\Torg12Item>|\Google\Protobuf\Internal\RepeatedField $Items
     *           табличные сведения товарной накладной
     *     @type string $ParcelsQuantityTotal
     *           количество мест, штук - всего по накладной
     *     @type string $ParcelsQuantityTotalInWords
     *           количество мест, штук - всего по накладной, прописью
     *     @type string $GrossQuantityTotal
     *           брутто - всего по накладной
     *     @type string $GrossQuantityTotalInWords
     *           брутто - всего по накладной, прописью
     *     @type string $NetQuantityTotal
     *           нетто - всего по накладной
     *     @type string $NetQuantityTotalInWords
     *           нетто - всего по накладной, прописью
     *     @type string $QuantityTotal
     *           количество (масса нетто) - всего по накладной
     *     @type string $TotalWithVatExcluded
     *           сумма без учета НДС - всего по накладной
     *     @type string $Vat
     *           сумма НДС - всего по накладной
     *     @type string $Total
     *           сумма с учетом НДС - всего по накладной
     *     @type string $TotalInWords
     *           сумма с учетом НДС - всего по накладной, прописью
     *     @type string $SupplyDate
     *           дата отпуска
     *     @type \Diadoc\Api\Proto\Invoicing\Official $SupplyAllowedBy
     *           отпуск разрешил
     *     @type \Diadoc\Api\Proto\Invoicing\Official $SupplyPerformedBy
     *           отпуск произвел
     *     @type \Diadoc\Api\Proto\Invoicing\Official $ChiefAccountant
     *           главный бухгалтер
     *     @type \Diadoc\Api\Proto\Invoicing\Signer $Signer
     *           подписант
     *     @type string $AdditionalInfo
     *           дополнительные сведения
     *     @type string $AttachmentSheetsQuantity
     *           приложение, количество листов
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Invoicing\Torg12Info::initOnce();
        parent::__construct($data);
    }

    /**
     * дата товарной накладной
     *
     * Generated from protobuf field <code>optional string DocumentDate = 1;</code>
     * @return string
     */
    public function getDocumentDate()
    {
        return isset($this->DocumentDate) ? $this->DocumentDate : '';
    }

    public function hasDocumentDate()
    {
        return isset($this->DocumentDate);
    }

    public function clearDocumentDate()
    {
        unset($this->DocumentDate);
    }

    /**
     * дата товарной накладной
     *
     * Generated from protobuf field <code>optional string DocumentDate = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDocumentDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->DocumentDate = $var;

        return $this;
    }

    /**
     * номер товарной накладной
     *
     * Generated from protobuf field <code>optional string DocumentNumber = 2;</code>
     * @return string
     */
    public function getDocumentNumber()
    {
        return isset($this->DocumentNumber) ? $this->DocumentNumber : '';
    }

    public function hasDocumentNumber()
    {
        return isset($this->DocumentNumber);
    }

    public function clearDocumentNumber()
    {
        unset($this->DocumentNumber);
    }

    /**
     * номер товарной накладной
     *
     * Generated from protobuf field <code>optional string DocumentNumber = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDocumentNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->DocumentNumber = $var;

        return $this;
    }

    /**
     * участник документооборота, отпустивший товар
     *
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.DocflowParticipant SellerDocflowParticipant = 3;</code>
     * @return \Diadoc\Api\Proto\Invoicing\DocflowParticipant|null
     */
    public function getSellerDocflowParticipant()
    {
        return $this->SellerDocflowParticipant;
    }

    public function hasSellerDocflowParticipant()
    {
        return isset($this->SellerDocflowParticipant);
    }

    public function clearSellerDocflowParticipant()
    {
        unset($this->SellerDocflowParticipant);
    }

    /**
     * участник документооборота, отпустивший товар
     *
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.DocflowParticipant SellerDocflowParticipant = 3;</code>
     * @param \Diadoc\Api\Proto\Invoicing\DocflowParticipant $var
     * @return $this
     */
    public function setSellerDocflowParticipant($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\Invoicing\DocflowParticipant::class);
        $this->SellerDocflowParticipant = $var;

        return $this;
    }

    /**
     * участник документооборота, которому отпущен товар
     *
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.DocflowParticipant BuyerDocflowParticipant = 4;</code>
     * @return \Diadoc\Api\Proto\Invoicing\DocflowParticipant|null
     */
    public function getBuyerDocflowParticipant()
    {
        return $this->BuyerDocflowParticipant;
    }

    public function hasBuyerDocflowParticipant()
    {
        return isset($this->BuyerDocflowParticipant);
    }

    public function clearBuyerDocflowParticipant()
    {
        unset($this->BuyerDocflowParticipant);
    }

    /**
     * участник документооборота, которому отпущен товар
     *
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.DocflowParticipant BuyerDocflowParticipant = 4;</code>
     * @param \Diadoc\Api\Proto\Invoicing\DocflowParticipant $var
     * @return $this
     */
    public function setBuyerDocflowParticipant($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\Invoicing\DocflowParticipant::class);
        $this->BuyerDocflowParticipant = $var;

        return $this;
    }

    /**
     * грузоотправитель
     *
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.OrganizationInfo Shipper = 5;</code>
     * @return \Diadoc\Api\Proto\Invoicing\OrganizationInfo|null
     */
    public function getShipper()
    {
        return $this->Shipper;
    }

    public function hasShipper()
    {
        return isset($this->Shipper);
    }

    public function clearShipper()
    {
        unset($this->Shipper);
    }

    /**
     * грузоотправитель
     *
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.OrganizationInfo Shipper = 5;</code>
     * @param \Diadoc\Api\Proto\Invoicing\OrganizationInfo $var
     * @return $this
     */
    public function setShipper($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\Invoicing\OrganizationInfo::class);
        $this->Shipper = $var;

        return $this;
    }

    /**
     * грузополучатель
     *
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.OrganizationInfo Consignee = 6;</code>
     * @return \Diadoc\Api\Proto\Invoicing\OrganizationInfo|null
     */
    public function getConsignee()
    {
        return $this->Consignee;
    }

    public function hasConsignee()
    {
        return isset($this->Consignee);
    }

    public function clearConsignee()
    {
        unset($this->Consignee);
    }

    /**
     * грузополучатель
     *
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.OrganizationInfo Consignee = 6;</code>
     * @param \Diadoc\Api\Proto\Invoicing\OrganizationInfo $var
     * @return $this
     */
    public function setConsignee($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\Invoicing\OrganizationInfo::class);
        $this->Consignee = $var;

        return $this;
    }

    /**
     * поставщик
     *
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.OrganizationInfo Supplier = 7;</code>
     * @return \Diadoc\Api\Proto\Invoicing\OrganizationInfo|null
     */
    public function getSupplier()
    {
        return $this->Supplier;
    }

    public function hasSupplier()
    {
        return isset($this->Supplier);
    }

    public function clearSupplier()
    {
        unset($this->Supplier);
    }

    /**
     * поставщик
     *
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.OrganizationInfo Supplier = 7;</code>
     * @param \Diadoc\Api\Proto\Invoicing\OrganizationInfo $var
     * @return $this
     */
    public function setSupplier($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\Invoicing\OrganizationInfo::class);
        $this->Supplier = $var;

        return $this;
    }

    /**
     * плательщик
     *
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.OrganizationInfo Payer = 8;</code>
     * @return \Diadoc\Api\Proto\Invoicing\OrganizationInfo|null
     */
    public function getPayer()
    {
        return $this->Payer;
    }

    public function hasPayer()
    {
        return isset($this->Payer);
    }

    public function clearPayer()
    {
        unset($this->Payer);
    }

    /**
     * плательщик
     *
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.OrganizationInfo Payer = 8;</code>
     * @param \Diadoc\Api\Proto\Invoicing\OrganizationInfo $var
     * @return $this
     */
    public function setPayer($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\Invoicing\OrganizationInfo::class);
        $this->Payer = $var;

        return $this;
    }

    /**
     * основание
     *
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.Grounds Grounds = 9;</code>
     * @return \Diadoc\Api\Proto\Invoicing\Grounds|null
     */
    public function getGrounds()
    {
        return $this->Grounds;
    }

    public function hasGrounds()
    {
        return isset($this->Grounds);
    }

    public function clearGrounds()
    {
        unset($this->Grounds);
    }

    /**
     * основание
     *
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.Grounds Grounds = 9;</code>
     * @param \Diadoc\Api\Proto\Invoicing\Grounds $var
     * @return $this
     */
    public function setGrounds($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\Invoicing\Grounds::class);
        $this->Grounds = $var;

        return $this;
    }

    /**
     * дата составления транспортной накладной
     *
     * Generated from protobuf field <code>optional string WaybillDate = 10;</code>
     * @return string
     */
    public function getWaybillDate()
    {
        return isset($this->WaybillDate) ? $this->WaybillDate : '';
    }

    public function hasWaybillDate()
    {
        return isset($this->WaybillDate);
    }

    public function clearWaybillDate()
    {
        unset($this->WaybillDate);
    }

    /**
     * дата составления транспортной накладной
     *
     * Generated from protobuf field <code>optional string WaybillDate = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setWaybillDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->WaybillDate = $var;

        return $this;
    }

    /**
     * номер транспортной накладной
     *
     * Generated from protobuf field <code>optional string WaybillNumber = 11;</code>
     * @return string
     */
    public function getWaybillNumber()
    {
        return isset($this->WaybillNumber) ? $this->WaybillNumber : '';
    }

    public function hasWaybillNumber()
    {
        return isset($this->WaybillNumber);
    }

    public function clearWaybillNumber()
    {
        unset($this->WaybillNumber);
    }

    /**
     * номер транспортной накладной
     *
     * Generated from protobuf field <code>optional string WaybillNumber = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setWaybillNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->WaybillNumber = $var;

        return $this;
    }

    /**
     * код вида операции
     *
     * Generated from protobuf field <code>optional string OperationCode = 12;</code>
     * @return string
     */
    public function getOperationCode()
    {
        return isset($this->OperationCode) ? $this->OperationCode : '';
    }

    public function hasOperationCode()
    {
        return isset($this->OperationCode);
    }

    public function clearOperationCode()
    {
        unset($this->OperationCode);
    }

    /**
     * код вида операции
     *
     * Generated from protobuf field <code>optional string OperationCode = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setOperationCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->OperationCode = $var;

        return $this;
    }

    /**
     * табличные сведения товарной накладной
     *
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.Invoicing.Torg12Item Items = 13;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getItems()
    {
        return $this->Items;
    }

    /**
     * табличные сведения товарной накладной
     *
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.Invoicing.Torg12Item Items = 13;</code>
     * @param array<\Diadoc\Api\Proto\Invoicing\Torg12Item>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setItems($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Diadoc\Api\Proto\Invoicing\Torg12Item::class);
        $this->Items = $arr;

        return $this;
    }

    /**
     * количество мест, штук - всего по накладной
     *
     * Generated from protobuf field <code>optional string ParcelsQuantityTotal = 14;</code>
     * @return string
     */
    public function getParcelsQuantityTotal()
    {
        return isset($this->ParcelsQuantityTotal) ? $this->ParcelsQuantityTotal : '';
    }

    public function hasParcelsQuantityTotal()
    {
        return isset($this->ParcelsQuantityTotal);
    }

    public function clearParcelsQuantityTotal()
    {
        unset($this->ParcelsQuantityTotal);
    }

    /**
     * количество мест, штук - всего по накладной
     *
     * Generated from protobuf field <code>optional string ParcelsQuantityTotal = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setParcelsQuantityTotal($var)
    {
        GPBUtil::checkString($var, True);
        $this->ParcelsQuantityTotal = $var;

        return $this;
    }

    /**
     * количество мест, штук - всего по накладной, прописью
     *
     * Generated from protobuf field <code>optional string ParcelsQuantityTotalInWords = 15;</code>
     * @return string
     */
    public function getParcelsQuantityTotalInWords()
    {
        return isset($this->ParcelsQuantityTotalInWords) ? $this->ParcelsQuantityTotalInWords : '';
    }

    public function hasParcelsQuantityTotalInWords()
    {
        return isset($this->ParcelsQuantityTotalInWords);
    }

    public function clearParcelsQuantityTotalInWords()
    {
        unset($this->ParcelsQuantityTotalInWords);
    }

    /**
     * количество мест, штук - всего по накладной, прописью
     *
     * Generated from protobuf field <code>optional string ParcelsQuantityTotalInWords = 15;</code>
     * @param string $var
     * @return $this
     */
    public function setParcelsQuantityTotalInWords($var)
    {
        GPBUtil::checkString($var, True);
        $this->ParcelsQuantityTotalInWords = $var;

        return $this;
    }

    /**
     * брутто - всего по накладной
     *
     * Generated from protobuf field <code>optional string GrossQuantityTotal = 16;</code>
     * @return string
     */
    public function getGrossQuantityTotal()
    {
        return isset($this->GrossQuantityTotal) ? $this->GrossQuantityTotal : '';
    }

    public function hasGrossQuantityTotal()
    {
        return isset($this->GrossQuantityTotal);
    }

    public function clearGrossQuantityTotal()
    {
        unset($this->GrossQuantityTotal);
    }

    /**
     * брутто - всего по накладной
     *
     * Generated from protobuf field <code>optional string GrossQuantityTotal = 16;</code>
     * @param string $var
     * @return $this
     */
    public function setGrossQuantityTotal($var)
    {
        GPBUtil::checkString($var, True);
        $this->GrossQuantityTotal = $var;

        return $this;
    }

    /**
     * брутто - всего по накладной, прописью
     *
     * Generated from protobuf field <code>optional string GrossQuantityTotalInWords = 17;</code>
     * @return string
     */
    public function getGrossQuantityTotalInWords()
    {
        return isset($this->GrossQuantityTotalInWords) ? $this->GrossQuantityTotalInWords : '';
    }

    public function hasGrossQuantityTotalInWords()
    {
        return isset($this->GrossQuantityTotalInWords);
    }

    public function clearGrossQuantityTotalInWords()
    {
        unset($this->GrossQuantityTotalInWords);
    }

    /**
     * брутто - всего по накладной, прописью
     *
     * Generated from protobuf field <code>optional string GrossQuantityTotalInWords = 17;</code>
     * @param string $var
     * @return $this
     */
    public function setGrossQuantityTotalInWords($var)
    {
        GPBUtil::checkString($var, True);
        $this->GrossQuantityTotalInWords = $var;

        return $this;
    }

    /**
     * нетто - всего по накладной
     *
     * Generated from protobuf field <code>optional string NetQuantityTotal = 18;</code>
     * @return string
     */
    public function getNetQuantityTotal()
    {
        return isset($this->NetQuantityTotal) ? $this->NetQuantityTotal : '';
    }

    public function hasNetQuantityTotal()
    {
        return isset($this->NetQuantityTotal);
    }

    public function clearNetQuantityTotal()
    {
        unset($this->NetQuantityTotal);
    }

    /**
     * нетто - всего по накладной
     *
     * Generated from protobuf field <code>optional string NetQuantityTotal = 18;</code>
     * @param string $var
     * @return $this
     */
    public function setNetQuantityTotal($var)
    {
        GPBUtil::checkString($var, True);
        $this->NetQuantityTotal = $var;

        return $this;
    }

    /**
     * нетто - всего по накладной, прописью
     *
     * Generated from protobuf field <code>optional string NetQuantityTotalInWords = 19;</code>
     * @return string
     */
    public function getNetQuantityTotalInWords()
    {
        return isset($this->NetQuantityTotalInWords) ? $this->NetQuantityTotalInWords : '';
    }

    public function hasNetQuantityTotalInWords()
    {
        return isset($this->NetQuantityTotalInWords);
    }

    public function clearNetQuantityTotalInWords()
    {
        unset($this->NetQuantityTotalInWords);
    }

    /**
     * нетто - всего по накладной, прописью
     *
     * Generated from protobuf field <code>optional string NetQuantityTotalInWords = 19;</code>
     * @param string $var
     * @return $this
     */
    public function setNetQuantityTotalInWords($var)
    {
        GPBUtil::checkString($var, True);
        $this->NetQuantityTotalInWords = $var;

        return $this;
    }

    /**
     * количество (масса нетто) - всего по накладной
     *
     * Generated from protobuf field <code>optional string QuantityTotal = 20;</code>
     * @return string
     */
    public function getQuantityTotal()
    {
        return isset($this->QuantityTotal) ? $this->QuantityTotal : '';
    }

    public function hasQuantityTotal()
    {
        return isset($this->QuantityTotal);
    }

    public function clearQuantityTotal()
    {
        unset($this->QuantityTotal);
    }

    /**
     * количество (масса нетто) - всего по накладной
     *
     * Generated from protobuf field <code>optional string QuantityTotal = 20;</code>
     * @param string $var
     * @return $this
     */
    public function setQuantityTotal($var)
    {
        GPBUtil::checkString($var, True);
        $this->QuantityTotal = $var;

        return $this;
    }

    /**
     * сумма без учета НДС - всего по накладной
     *
     * Generated from protobuf field <code>optional string TotalWithVatExcluded = 21;</code>
     * @return string
     */
    public function getTotalWithVatExcluded()
    {
        return isset($this->TotalWithVatExcluded) ? $this->TotalWithVatExcluded : '';
    }

    public function hasTotalWithVatExcluded()
    {
        return isset($this->TotalWithVatExcluded);
    }

    public function clearTotalWithVatExcluded()
    {
        unset($this->TotalWithVatExcluded);
    }

    /**
     * сумма без учета НДС - всего по накладной
     *
     * Generated from protobuf field <code>optional string TotalWithVatExcluded = 21;</code>
     * @param string $var
     * @return $this
     */
    public function setTotalWithVatExcluded($var)
    {
        GPBUtil::checkString($var, True);
        $this->TotalWithVatExcluded = $var;

        return $this;
    }

    /**
     * сумма НДС - всего по накладной
     *
     * Generated from protobuf field <code>optional string Vat = 22;</code>
     * @return string
     */
    public function getVat()
    {
        return isset($this->Vat) ? $this->Vat : '';
    }

    public function hasVat()
    {
        return isset($this->Vat);
    }

    public function clearVat()
    {
        unset($this->Vat);
    }

    /**
     * сумма НДС - всего по накладной
     *
     * Generated from protobuf field <code>optional string Vat = 22;</code>
     * @param string $var
     * @return $this
     */
    public function setVat($var)
    {
        GPBUtil::checkString($var, True);
        $this->Vat = $var;

        return $this;
    }

    /**
     * сумма с учетом НДС - всего по накладной
     *
     * Generated from protobuf field <code>optional string Total = 23;</code>
     * @return string
     */
    public function getTotal()
    {
        return isset($this->Total) ? $this->Total : '';
    }

    public function hasTotal()
    {
        return isset($this->Total);
    }

    public function clearTotal()
    {
        unset($this->Total);
    }

    /**
     * сумма с учетом НДС - всего по накладной
     *
     * Generated from protobuf field <code>optional string Total = 23;</code>
     * @param string $var
     * @return $this
     */
    public function setTotal($var)
    {
        GPBUtil::checkString($var, True);
        $this->Total = $var;

        return $this;
    }

    /**
     * сумма с учетом НДС - всего по накладной, прописью
     *
     * Generated from protobuf field <code>optional string TotalInWords = 24;</code>
     * @return string
     */
    public function getTotalInWords()
    {
        return isset($this->TotalInWords) ? $this->TotalInWords : '';
    }

    public function hasTotalInWords()
    {
        return isset($this->TotalInWords);
    }

    public function clearTotalInWords()
    {
        unset($this->TotalInWords);
    }

    /**
     * сумма с учетом НДС - всего по накладной, прописью
     *
     * Generated from protobuf field <code>optional string TotalInWords = 24;</code>
     * @param string $var
     * @return $this
     */
    public function setTotalInWords($var)
    {
        GPBUtil::checkString($var, True);
        $this->TotalInWords = $var;

        return $this;
    }

    /**
     * дата отпуска
     *
     * Generated from protobuf field <code>optional string SupplyDate = 25;</code>
     * @return string
     */
    public function getSupplyDate()
    {
        return isset($this->SupplyDate) ? $this->SupplyDate : '';
    }

    public function hasSupplyDate()
    {
        return isset($this->SupplyDate);
    }

    public function clearSupplyDate()
    {
        unset($this->SupplyDate);
    }

    /**
     * дата отпуска
     *
     * Generated from protobuf field <code>optional string SupplyDate = 25;</code>
     * @param string $var
     * @return $this
     */
    public function setSupplyDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->SupplyDate = $var;

        return $this;
    }

    /**
     * отпуск разрешил
     *
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.Official SupplyAllowedBy = 26;</code>
     * @return \Diadoc\Api\Proto\Invoicing\Official|null
     */
    public function getSupplyAllowedBy()
    {
        return $this->SupplyAllowedBy;
    }

    public function hasSupplyAllowedBy()
    {
        return isset($this->SupplyAllowedBy);
    }

    public function clearSupplyAllowedBy()
    {
        unset($this->SupplyAllowedBy);
    }

    /**
     * отпуск разрешил
     *
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.Official SupplyAllowedBy = 26;</code>
     * @param \Diadoc\Api\Proto\Invoicing\Official $var
     * @return $this
     */
    public function setSupplyAllowedBy($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\Invoicing\Official::class);
        $this->SupplyAllowedBy = $var;

        return $this;
    }

    /**
     * отпуск произвел
     *
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.Official SupplyPerformedBy = 27;</code>
     * @return \Diadoc\Api\Proto\Invoicing\Official|null
     */
    public function getSupplyPerformedBy()
    {
        return $this->SupplyPerformedBy;
    }

    public function hasSupplyPerformedBy()
    {
        return isset($this->SupplyPerformedBy);
    }

    public function clearSupplyPerformedBy()
    {
        unset($this->SupplyPerformedBy);
    }

    /**
     * отпуск произвел
     *
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.Official SupplyPerformedBy = 27;</code>
     * @param \Diadoc\Api\Proto\Invoicing\Official $var
     * @return $this
     */
    public function setSupplyPerformedBy($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\Invoicing\Official::class);
        $this->SupplyPerformedBy = $var;

        return $this;
    }

    /**
     * главный бухгалтер
     *
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.Official ChiefAccountant = 28;</code>
     * @return \Diadoc\Api\Proto\Invoicing\Official|null
     */
    public function getChiefAccountant()
    {
        return $this->ChiefAccountant;
    }

    public function hasChiefAccountant()
    {
        return isset($this->ChiefAccountant);
    }

    public function clearChiefAccountant()
    {
        unset($this->ChiefAccountant);
    }

    /**
     * главный бухгалтер
     *
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.Official ChiefAccountant = 28;</code>
     * @param \Diadoc\Api\Proto\Invoicing\Official $var
     * @return $this
     */
    public function setChiefAccountant($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\Invoicing\Official::class);
        $this->ChiefAccountant = $var;

        return $this;
    }

    /**
     * подписант
     *
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.Signer Signer = 29;</code>
     * @return \Diadoc\Api\Proto\Invoicing\Signer|null
     */
    public function getSigner()
    {
        return $this->Signer;
    }

    public function hasSigner()
    {
        return isset($this->Signer);
    }

    public function clearSigner()
    {
        unset($this->Signer);
    }

    /**
     * подписант
     *
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.Signer Signer = 29;</code>
     * @param \Diadoc\Api\Proto\Invoicing\Signer $var
     * @return $this
     */
    public function setSigner($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\Invoicing\Signer::class);
        $this->Signer = $var;

        return $this;
    }

    /**
     * дополнительные сведения
     *
     * Generated from protobuf field <code>optional string AdditionalInfo = 30;</code>
     * @return string
     */
    public function getAdditionalInfo()
    {
        return isset($this->AdditionalInfo) ? $this->AdditionalInfo : '';
    }

    public function hasAdditionalInfo()
    {
        return isset($this->AdditionalInfo);
    }

    public function clearAdditionalInfo()
    {
        unset($this->AdditionalInfo);
    }

    /**
     * дополнительные сведения
     *
     * Generated from protobuf field <code>optional string AdditionalInfo = 30;</code>
     * @param string $var
     * @return $this
     */
    public function setAdditionalInfo($var)
    {
        GPBUtil::checkString($var, True);
        $this->AdditionalInfo = $var;

        return $this;
    }

    /**
     * приложение, количество листов
     *
     * Generated from protobuf field <code>optional string AttachmentSheetsQuantity = 31;</code>
     * @return string
     */
    public function getAttachmentSheetsQuantity()
    {
        return isset($this->AttachmentSheetsQuantity) ? $this->AttachmentSheetsQuantity : '';
    }

    public function hasAttachmentSheetsQuantity()
    {
        return isset($this->AttachmentSheetsQuantity);
    }

    public function clearAttachmentSheetsQuantity()
    {
        unset($this->AttachmentSheetsQuantity);
    }

    /**
     * приложение, количество листов
     *
     * Generated from protobuf field <code>optional string AttachmentSheetsQuantity = 31;</code>
     * @param string $var
     * @return $this
     */
    public function setAttachmentSheetsQuantity($var)
    {
        GPBUtil::checkString($var, True);
        $this->AttachmentSheetsQuantity = $var;

        return $this;
    }

}

