<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Invoicing/Torg12Info.proto

namespace Diadoc\Api\Proto\Invoicing;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.Invoicing.Torg12Item</code>
 */
class Torg12Item extends \Google\Protobuf\Internal\Message
{
    /**
     * наименование
     *
     * Generated from protobuf field <code>optional string Name = 1;</code>
     */
    protected $Name = null;
    /**
     * характеристика
     *
     * Generated from protobuf field <code>optional string Feature = 2;</code>
     */
    protected $Feature = null;
    /**
     * сорт товара
     *
     * Generated from protobuf field <code>optional string Sort = 3;</code>
     */
    protected $Sort = null;
    /**
     * артикул
     *
     * Generated from protobuf field <code>optional string NomenclatureArticle = 4;</code>
     */
    protected $NomenclatureArticle = null;
    /**
     * код товара
     *
     * Generated from protobuf field <code>optional string Code = 5;</code>
     */
    protected $Code = null;
    /**
     * код единицы измерения
     *
     * Generated from protobuf field <code>optional string UnitCode = 6;</code>
     */
    protected $UnitCode = null;
    /**
     * наименование единицы измерения
     *
     * Generated from protobuf field <code>optional string UnitName = 7;</code>
     */
    protected $UnitName = null;
    /**
     * вид упаковки
     *
     * Generated from protobuf field <code>optional string ParcelType = 8;</code>
     */
    protected $ParcelType = null;
    /**
     * количество в одном месте
     *
     * Generated from protobuf field <code>optional string ParcelCapacity = 9;</code>
     */
    protected $ParcelCapacity = null;
    /**
     * количество мест
     *
     * Generated from protobuf field <code>optional string ParcelsQuantity = 10;</code>
     */
    protected $ParcelsQuantity = null;
    /**
     * брутто
     *
     * Generated from protobuf field <code>optional string GrossQuantity = 11;</code>
     */
    protected $GrossQuantity = null;
    /**
     * нетто // количество (масса)
     *
     * Generated from protobuf field <code>optional string Quantity = 12;</code>
     */
    protected $Quantity = null;
    /**
     * цена
     *
     * Generated from protobuf field <code>optional string Price = 13;</code>
     */
    protected $Price = null;
    /**
     * ставка налога
     *
     * Generated from protobuf field <code>optional string TaxRate = 14;</code>
     */
    protected $TaxRate = null;
    /**
     * сумма без учета налога
     *
     * Generated from protobuf field <code>optional string SubtotalWithVatExcluded = 15;</code>
     */
    protected $SubtotalWithVatExcluded = null;
    /**
     * сумма налога
     *
     * Generated from protobuf field <code>optional string Vat = 16;</code>
     */
    protected $Vat = null;
    /**
     * сумма всего
     *
     * Generated from protobuf field <code>optional string Subtotal = 17;</code>
     */
    protected $Subtotal = null;
    /**
     * информационное поле сведений о товаре
     *
     * Generated from protobuf field <code>optional string AdditionalInfo = 18;</code>
     */
    protected $AdditionalInfo = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Name
     *           наименование
     *     @type string $Feature
     *           характеристика
     *     @type string $Sort
     *           сорт товара
     *     @type string $NomenclatureArticle
     *           артикул
     *     @type string $Code
     *           код товара
     *     @type string $UnitCode
     *           код единицы измерения
     *     @type string $UnitName
     *           наименование единицы измерения
     *     @type string $ParcelType
     *           вид упаковки
     *     @type string $ParcelCapacity
     *           количество в одном месте
     *     @type string $ParcelsQuantity
     *           количество мест
     *     @type string $GrossQuantity
     *           брутто
     *     @type string $Quantity
     *           нетто // количество (масса)
     *     @type string $Price
     *           цена
     *     @type string $TaxRate
     *           ставка налога
     *     @type string $SubtotalWithVatExcluded
     *           сумма без учета налога
     *     @type string $Vat
     *           сумма налога
     *     @type string $Subtotal
     *           сумма всего
     *     @type string $AdditionalInfo
     *           информационное поле сведений о товаре
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Invoicing\Torg12Info::initOnce();
        parent::__construct($data);
    }

    /**
     * наименование
     *
     * Generated from protobuf field <code>optional string Name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return isset($this->Name) ? $this->Name : '';
    }

    public function hasName()
    {
        return isset($this->Name);
    }

    public function clearName()
    {
        unset($this->Name);
    }

    /**
     * наименование
     *
     * Generated from protobuf field <code>optional string Name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->Name = $var;

        return $this;
    }

    /**
     * характеристика
     *
     * Generated from protobuf field <code>optional string Feature = 2;</code>
     * @return string
     */
    public function getFeature()
    {
        return isset($this->Feature) ? $this->Feature : '';
    }

    public function hasFeature()
    {
        return isset($this->Feature);
    }

    public function clearFeature()
    {
        unset($this->Feature);
    }

    /**
     * характеристика
     *
     * Generated from protobuf field <code>optional string Feature = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setFeature($var)
    {
        GPBUtil::checkString($var, True);
        $this->Feature = $var;

        return $this;
    }

    /**
     * сорт товара
     *
     * Generated from protobuf field <code>optional string Sort = 3;</code>
     * @return string
     */
    public function getSort()
    {
        return isset($this->Sort) ? $this->Sort : '';
    }

    public function hasSort()
    {
        return isset($this->Sort);
    }

    public function clearSort()
    {
        unset($this->Sort);
    }

    /**
     * сорт товара
     *
     * Generated from protobuf field <code>optional string Sort = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setSort($var)
    {
        GPBUtil::checkString($var, True);
        $this->Sort = $var;

        return $this;
    }

    /**
     * артикул
     *
     * Generated from protobuf field <code>optional string NomenclatureArticle = 4;</code>
     * @return string
     */
    public function getNomenclatureArticle()
    {
        return isset($this->NomenclatureArticle) ? $this->NomenclatureArticle : '';
    }

    public function hasNomenclatureArticle()
    {
        return isset($this->NomenclatureArticle);
    }

    public function clearNomenclatureArticle()
    {
        unset($this->NomenclatureArticle);
    }

    /**
     * артикул
     *
     * Generated from protobuf field <code>optional string NomenclatureArticle = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setNomenclatureArticle($var)
    {
        GPBUtil::checkString($var, True);
        $this->NomenclatureArticle = $var;

        return $this;
    }

    /**
     * код товара
     *
     * Generated from protobuf field <code>optional string Code = 5;</code>
     * @return string
     */
    public function getCode()
    {
        return isset($this->Code) ? $this->Code : '';
    }

    public function hasCode()
    {
        return isset($this->Code);
    }

    public function clearCode()
    {
        unset($this->Code);
    }

    /**
     * код товара
     *
     * Generated from protobuf field <code>optional string Code = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->Code = $var;

        return $this;
    }

    /**
     * код единицы измерения
     *
     * Generated from protobuf field <code>optional string UnitCode = 6;</code>
     * @return string
     */
    public function getUnitCode()
    {
        return isset($this->UnitCode) ? $this->UnitCode : '';
    }

    public function hasUnitCode()
    {
        return isset($this->UnitCode);
    }

    public function clearUnitCode()
    {
        unset($this->UnitCode);
    }

    /**
     * код единицы измерения
     *
     * Generated from protobuf field <code>optional string UnitCode = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setUnitCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->UnitCode = $var;

        return $this;
    }

    /**
     * наименование единицы измерения
     *
     * Generated from protobuf field <code>optional string UnitName = 7;</code>
     * @return string
     */
    public function getUnitName()
    {
        return isset($this->UnitName) ? $this->UnitName : '';
    }

    public function hasUnitName()
    {
        return isset($this->UnitName);
    }

    public function clearUnitName()
    {
        unset($this->UnitName);
    }

    /**
     * наименование единицы измерения
     *
     * Generated from protobuf field <code>optional string UnitName = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setUnitName($var)
    {
        GPBUtil::checkString($var, True);
        $this->UnitName = $var;

        return $this;
    }

    /**
     * вид упаковки
     *
     * Generated from protobuf field <code>optional string ParcelType = 8;</code>
     * @return string
     */
    public function getParcelType()
    {
        return isset($this->ParcelType) ? $this->ParcelType : '';
    }

    public function hasParcelType()
    {
        return isset($this->ParcelType);
    }

    public function clearParcelType()
    {
        unset($this->ParcelType);
    }

    /**
     * вид упаковки
     *
     * Generated from protobuf field <code>optional string ParcelType = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setParcelType($var)
    {
        GPBUtil::checkString($var, True);
        $this->ParcelType = $var;

        return $this;
    }

    /**
     * количество в одном месте
     *
     * Generated from protobuf field <code>optional string ParcelCapacity = 9;</code>
     * @return string
     */
    public function getParcelCapacity()
    {
        return isset($this->ParcelCapacity) ? $this->ParcelCapacity : '';
    }

    public function hasParcelCapacity()
    {
        return isset($this->ParcelCapacity);
    }

    public function clearParcelCapacity()
    {
        unset($this->ParcelCapacity);
    }

    /**
     * количество в одном месте
     *
     * Generated from protobuf field <code>optional string ParcelCapacity = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setParcelCapacity($var)
    {
        GPBUtil::checkString($var, True);
        $this->ParcelCapacity = $var;

        return $this;
    }

    /**
     * количество мест
     *
     * Generated from protobuf field <code>optional string ParcelsQuantity = 10;</code>
     * @return string
     */
    public function getParcelsQuantity()
    {
        return isset($this->ParcelsQuantity) ? $this->ParcelsQuantity : '';
    }

    public function hasParcelsQuantity()
    {
        return isset($this->ParcelsQuantity);
    }

    public function clearParcelsQuantity()
    {
        unset($this->ParcelsQuantity);
    }

    /**
     * количество мест
     *
     * Generated from protobuf field <code>optional string ParcelsQuantity = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setParcelsQuantity($var)
    {
        GPBUtil::checkString($var, True);
        $this->ParcelsQuantity = $var;

        return $this;
    }

    /**
     * брутто
     *
     * Generated from protobuf field <code>optional string GrossQuantity = 11;</code>
     * @return string
     */
    public function getGrossQuantity()
    {
        return isset($this->GrossQuantity) ? $this->GrossQuantity : '';
    }

    public function hasGrossQuantity()
    {
        return isset($this->GrossQuantity);
    }

    public function clearGrossQuantity()
    {
        unset($this->GrossQuantity);
    }

    /**
     * брутто
     *
     * Generated from protobuf field <code>optional string GrossQuantity = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setGrossQuantity($var)
    {
        GPBUtil::checkString($var, True);
        $this->GrossQuantity = $var;

        return $this;
    }

    /**
     * нетто // количество (масса)
     *
     * Generated from protobuf field <code>optional string Quantity = 12;</code>
     * @return string
     */
    public function getQuantity()
    {
        return isset($this->Quantity) ? $this->Quantity : '';
    }

    public function hasQuantity()
    {
        return isset($this->Quantity);
    }

    public function clearQuantity()
    {
        unset($this->Quantity);
    }

    /**
     * нетто // количество (масса)
     *
     * Generated from protobuf field <code>optional string Quantity = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setQuantity($var)
    {
        GPBUtil::checkString($var, True);
        $this->Quantity = $var;

        return $this;
    }

    /**
     * цена
     *
     * Generated from protobuf field <code>optional string Price = 13;</code>
     * @return string
     */
    public function getPrice()
    {
        return isset($this->Price) ? $this->Price : '';
    }

    public function hasPrice()
    {
        return isset($this->Price);
    }

    public function clearPrice()
    {
        unset($this->Price);
    }

    /**
     * цена
     *
     * Generated from protobuf field <code>optional string Price = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setPrice($var)
    {
        GPBUtil::checkString($var, True);
        $this->Price = $var;

        return $this;
    }

    /**
     * ставка налога
     *
     * Generated from protobuf field <code>optional string TaxRate = 14;</code>
     * @return string
     */
    public function getTaxRate()
    {
        return isset($this->TaxRate) ? $this->TaxRate : '';
    }

    public function hasTaxRate()
    {
        return isset($this->TaxRate);
    }

    public function clearTaxRate()
    {
        unset($this->TaxRate);
    }

    /**
     * ставка налога
     *
     * Generated from protobuf field <code>optional string TaxRate = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setTaxRate($var)
    {
        GPBUtil::checkString($var, True);
        $this->TaxRate = $var;

        return $this;
    }

    /**
     * сумма без учета налога
     *
     * Generated from protobuf field <code>optional string SubtotalWithVatExcluded = 15;</code>
     * @return string
     */
    public function getSubtotalWithVatExcluded()
    {
        return isset($this->SubtotalWithVatExcluded) ? $this->SubtotalWithVatExcluded : '';
    }

    public function hasSubtotalWithVatExcluded()
    {
        return isset($this->SubtotalWithVatExcluded);
    }

    public function clearSubtotalWithVatExcluded()
    {
        unset($this->SubtotalWithVatExcluded);
    }

    /**
     * сумма без учета налога
     *
     * Generated from protobuf field <code>optional string SubtotalWithVatExcluded = 15;</code>
     * @param string $var
     * @return $this
     */
    public function setSubtotalWithVatExcluded($var)
    {
        GPBUtil::checkString($var, True);
        $this->SubtotalWithVatExcluded = $var;

        return $this;
    }

    /**
     * сумма налога
     *
     * Generated from protobuf field <code>optional string Vat = 16;</code>
     * @return string
     */
    public function getVat()
    {
        return isset($this->Vat) ? $this->Vat : '';
    }

    public function hasVat()
    {
        return isset($this->Vat);
    }

    public function clearVat()
    {
        unset($this->Vat);
    }

    /**
     * сумма налога
     *
     * Generated from protobuf field <code>optional string Vat = 16;</code>
     * @param string $var
     * @return $this
     */
    public function setVat($var)
    {
        GPBUtil::checkString($var, True);
        $this->Vat = $var;

        return $this;
    }

    /**
     * сумма всего
     *
     * Generated from protobuf field <code>optional string Subtotal = 17;</code>
     * @return string
     */
    public function getSubtotal()
    {
        return isset($this->Subtotal) ? $this->Subtotal : '';
    }

    public function hasSubtotal()
    {
        return isset($this->Subtotal);
    }

    public function clearSubtotal()
    {
        unset($this->Subtotal);
    }

    /**
     * сумма всего
     *
     * Generated from protobuf field <code>optional string Subtotal = 17;</code>
     * @param string $var
     * @return $this
     */
    public function setSubtotal($var)
    {
        GPBUtil::checkString($var, True);
        $this->Subtotal = $var;

        return $this;
    }

    /**
     * информационное поле сведений о товаре
     *
     * Generated from protobuf field <code>optional string AdditionalInfo = 18;</code>
     * @return string
     */
    public function getAdditionalInfo()
    {
        return isset($this->AdditionalInfo) ? $this->AdditionalInfo : '';
    }

    public function hasAdditionalInfo()
    {
        return isset($this->AdditionalInfo);
    }

    public function clearAdditionalInfo()
    {
        unset($this->AdditionalInfo);
    }

    /**
     * информационное поле сведений о товаре
     *
     * Generated from protobuf field <code>optional string AdditionalInfo = 18;</code>
     * @param string $var
     * @return $this
     */
    public function setAdditionalInfo($var)
    {
        GPBUtil::checkString($var, True);
        $this->AdditionalInfo = $var;

        return $this;
    }

}

