<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Departments/DepartmentToCreate.proto

namespace GPBMetadata\Departments;

class DepartmentToCreate
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Address::initOnce();
        \GPBMetadata\Departments\Routing::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xC3\x02\x0A\$Departments/DepartmentToCreate.proto\x12\x1CDiadoc.Api.Proto.Departments\x1A\x19Departments/Routing.proto\"\xC5\x01\x0A\x12DepartmentToCreate\x12\x1A\x0A\x12ParentDepartmentId\x18\x01 \x01(\x09\x12\x0C\x0A\x04Name\x18\x02 \x01(\x09\x12\x14\x0A\x0CAbbreviation\x18\x03 \x01(\x09\x12\x0B\x0A\x03Kpp\x18\x04 \x01(\x09\x12*\x0A\x07Address\x18\x05 \x01(\x0B2\x19.Diadoc.Api.Proto.Address\x126\x0A\x07Routing\x18\x06 \x01(\x0B2%.Diadoc.Api.Proto.Departments.RoutingB\x1AB\x18DepartmentToCreateProtos"
        , true);

        static::$is_initialized = true;
    }
}

