<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Departments/DepartmentList.proto

namespace GPBMetadata\Departments;

class DepartmentList
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Departments\Department::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xBD\x01\x0A Departments/DepartmentList.proto\x12\x1CDiadoc.Api.Proto.Departments\"c\x0A\x0EDepartmentList\x12=\x0A\x0BDepartments\x18\x01 \x03(\x0B2(.Diadoc.Api.Proto.Departments.Department\x12\x12\x0A\x0ATotalCount\x18\x02 \x01(\x05B\x16B\x14DepartmentListProtos"
        , true);

        static::$is_initialized = true;
    }
}

