<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Departments/Department.proto

namespace GPBMetadata\Departments;

class Department
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Address::initOnce();
        \GPBMetadata\Timestamp::initOnce();
        \GPBMetadata\Departments\Routing::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\x80\x03\x0A\x1CDepartments/Department.proto\x12\x1CDiadoc.Api.Proto.Departments\x1A\x0FTimestamp.proto\x1A\x19Departments/Routing.proto\"\x81\x02\x0A\x0ADepartment\x12\x0A\x0A\x02Id\x18\x01 \x01(\x09\x12\x1A\x0A\x12ParentDepartmentId\x18\x02 \x01(\x09\x12\x0C\x0A\x04Name\x18\x03 \x01(\x09\x12\x14\x0A\x0CAbbreviation\x18\x04 \x01(\x09\x12\x0B\x0A\x03Kpp\x18\x05 \x01(\x09\x12*\x0A\x07Address\x18\x06 \x01(\x0B2\x19.Diadoc.Api.Proto.Address\x126\x0A\x07Routing\x18\x07 \x01(\x0B2%.Diadoc.Api.Proto.Departments.Routing\x126\x0A\x11CreationTimestamp\x18\x08 \x01(\x0B2\x1B.Diadoc.Api.Proto.TimestampB\x12B\x10DepartmentProtos"
        , true);

        static::$is_initialized = true;
    }
}

