<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Departments/DepartmentToUpdate.proto

namespace GPBMetadata\Departments;

class DepartmentToUpdate
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Address::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xF5\x05\x0A\$Departments/DepartmentToUpdate.proto\x12\x1CDiadoc.Api.Proto.Departments\"\xFF\x02\x0A\x12DepartmentToUpdate\x12M\x0A\x10ParentDepartment\x18\x01 \x01(\x0B23.Diadoc.Api.Proto.Departments.ParentDepartmentPatch\x12M\x0A\x10DepartmentNaming\x18\x02 \x01(\x0B23.Diadoc.Api.Proto.Departments.DepartmentNamingPatch\x12=\x0A\x03Kpp\x18\x03 \x01(\x0B20.Diadoc.Api.Proto.Departments.DepartmentKppPatch\x12E\x0A\x07Address\x18\x04 \x01(\x0B24.Diadoc.Api.Proto.Departments.DepartmentAddressPatch\x12E\x0A\x07Routing\x18\x05 \x01(\x0B24.Diadoc.Api.Proto.Departments.DepartmentRoutingPatch\"3\x0A\x15ParentDepartmentPatch\x12\x1A\x0A\x12ParentDepartmentId\x18\x01 \x01(\x09\";\x0A\x15DepartmentNamingPatch\x12\x0C\x0A\x04Name\x18\x01 \x01(\x09\x12\x14\x0A\x0CAbbreviation\x18\x02 \x01(\x09\"!\x0A\x12DepartmentKppPatch\x12\x0B\x0A\x03Kpp\x18\x01 \x01(\x09\"D\x0A\x16DepartmentAddressPatch\x12*\x0A\x07Address\x18\x01 \x01(\x0B2\x19.Diadoc.Api.Proto.Address\"6\x0A\x16DepartmentRoutingPatch\x12\x0B\x0A\x03Kpp\x18\x01 \x01(\x08\x12\x0F\x0A\x07Address\x18\x02 \x01(\x08B\x1AB\x18DepartmentToUpdateProtos"
        , true);

        static::$is_initialized = true;
    }
}

