<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Departments/Routing.proto

namespace GPBMetadata\Departments;

class Routing
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0As\x0A\x19Departments/Routing.proto\x12\x1CDiadoc.Api.Proto.Departments\"'\x0A\x07Routing\x12\x0B\x0A\x03Kpp\x18\x01 \x01(\x08\x12\x0F\x0A\x07Address\x18\x02 \x01(\x08B\x0FB\x0DRoutingProtos"
        , true);

        static::$is_initialized = true;
    }
}

