<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SignatureVerificationResult.proto

namespace Diadoc\Api\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.CertificateChainElement</code>
 */
class CertificateChainElement extends \Google\Protobuf\Internal\Message
{
    /**
     * X509ChainStatusFlags value
     *
     * Generated from protobuf field <code>optional int32 CertificateChainStatusFlags = 1;</code>
     */
    protected $CertificateChainStatusFlags = null;
    /**
     * Generated from protobuf field <code>optional bytes DerCertificate = 2;</code>
     */
    protected $DerCertificate = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $CertificateChainStatusFlags
     *           X509ChainStatusFlags value
     *     @type string $DerCertificate
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\SignatureVerificationResult::initOnce();
        parent::__construct($data);
    }

    /**
     * X509ChainStatusFlags value
     *
     * Generated from protobuf field <code>optional int32 CertificateChainStatusFlags = 1;</code>
     * @return int
     */
    public function getCertificateChainStatusFlags()
    {
        return isset($this->CertificateChainStatusFlags) ? $this->CertificateChainStatusFlags : 0;
    }

    public function hasCertificateChainStatusFlags()
    {
        return isset($this->CertificateChainStatusFlags);
    }

    public function clearCertificateChainStatusFlags()
    {
        unset($this->CertificateChainStatusFlags);
    }

    /**
     * X509ChainStatusFlags value
     *
     * Generated from protobuf field <code>optional int32 CertificateChainStatusFlags = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setCertificateChainStatusFlags($var)
    {
        GPBUtil::checkInt32($var);
        $this->CertificateChainStatusFlags = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bytes DerCertificate = 2;</code>
     * @return string
     */
    public function getDerCertificate()
    {
        return isset($this->DerCertificate) ? $this->DerCertificate : '';
    }

    public function hasDerCertificate()
    {
        return isset($this->DerCertificate);
    }

    public function clearDerCertificate()
    {
        unset($this->DerCertificate);
    }

    /**
     * Generated from protobuf field <code>optional bytes DerCertificate = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDerCertificate($var)
    {
        GPBUtil::checkString($var, False);
        $this->DerCertificate = $var;

        return $this;
    }

}

