<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Content.proto

namespace Diadoc\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.Content</code>
 */
class Content extends \Google\Protobuf\Internal\Message
{
    /**
     * -1 if content size is unknown
     *
     * Generated from protobuf field <code>optional sfixed32 Size = 1;</code>
     */
    protected $Size = null;
    /**
     * null <=> entity content exists but is not included in proto buffer
     *
     * Generated from protobuf field <code>optional bytes Data = 2;</code>
     */
    protected $Data = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $Size
     *           -1 if content size is unknown
     *     @type string $Data
     *           null <=> entity content exists but is not included in proto buffer
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Content::initOnce();
        parent::__construct($data);
    }

    /**
     * -1 if content size is unknown
     *
     * Generated from protobuf field <code>optional sfixed32 Size = 1;</code>
     * @return int
     */
    public function getSize()
    {
        return isset($this->Size) ? $this->Size : 0;
    }

    public function hasSize()
    {
        return isset($this->Size);
    }

    public function clearSize()
    {
        unset($this->Size);
    }

    /**
     * -1 if content size is unknown
     *
     * Generated from protobuf field <code>optional sfixed32 Size = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->Size = $var;

        return $this;
    }

    /**
     * null <=> entity content exists but is not included in proto buffer
     *
     * Generated from protobuf field <code>optional bytes Data = 2;</code>
     * @return string
     */
    public function getData()
    {
        return isset($this->Data) ? $this->Data : '';
    }

    public function hasData()
    {
        return isset($this->Data);
    }

    public function clearData()
    {
        unset($this->Data);
    }

    /**
     * null <=> entity content exists but is not included in proto buffer
     *
     * Generated from protobuf field <code>optional bytes Data = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkString($var, False);
        $this->Data = $var;

        return $this;
    }

}

