<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Address.proto

namespace Diadoc\Api\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.ForeignAddress</code>
 */
class ForeignAddress extends \Google\Protobuf\Internal\Message
{
    /**
     * страна (код)
     *
     * Generated from protobuf field <code>optional string Country = 1;</code>
     */
    protected $Country = null;
    /**
     * текст адреса
     *
     * Generated from protobuf field <code>optional string Address = 2;</code>
     */
    protected $Address = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Country
     *           страна (код)
     *     @type string $Address
     *           текст адреса
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Address::initOnce();
        parent::__construct($data);
    }

    /**
     * страна (код)
     *
     * Generated from protobuf field <code>optional string Country = 1;</code>
     * @return string
     */
    public function getCountry()
    {
        return isset($this->Country) ? $this->Country : '';
    }

    public function hasCountry()
    {
        return isset($this->Country);
    }

    public function clearCountry()
    {
        unset($this->Country);
    }

    /**
     * страна (код)
     *
     * Generated from protobuf field <code>optional string Country = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCountry($var)
    {
        GPBUtil::checkString($var, True);
        $this->Country = $var;

        return $this;
    }

    /**
     * текст адреса
     *
     * Generated from protobuf field <code>optional string Address = 2;</code>
     * @return string
     */
    public function getAddress()
    {
        return isset($this->Address) ? $this->Address : '';
    }

    public function hasAddress()
    {
        return isset($this->Address);
    }

    public function clearAddress()
    {
        unset($this->Address);
    }

    /**
     * текст адреса
     *
     * Generated from protobuf field <code>optional string Address = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->Address = $var;

        return $this;
    }

}

