<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: LoginPassword.proto

namespace Diadoc\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.LoginPassword</code>
 */
class LoginPassword extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional string Login = 1;</code>
     */
    protected $Login = null;
    /**
     * Generated from protobuf field <code>optional string Password = 2;</code>
     */
    protected $Password = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Login
     *     @type string $Password
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\LoginPassword::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string Login = 1;</code>
     * @return string
     */
    public function getLogin()
    {
        return isset($this->Login) ? $this->Login : '';
    }

    public function hasLogin()
    {
        return isset($this->Login);
    }

    public function clearLogin()
    {
        unset($this->Login);
    }

    /**
     * Generated from protobuf field <code>optional string Login = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setLogin($var)
    {
        GPBUtil::checkString($var, True);
        $this->Login = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string Password = 2;</code>
     * @return string
     */
    public function getPassword()
    {
        return isset($this->Password) ? $this->Password : '';
    }

    public function hasPassword()
    {
        return isset($this->Password);
    }

    public function clearPassword()
    {
        unset($this->Password);
    }

    /**
     * Generated from protobuf field <code>optional string Password = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPassword($var)
    {
        GPBUtil::checkString($var, True);
        $this->Password = $var;

        return $this;
    }

}

