<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: RoamingOperator.proto

namespace Diadoc\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.OperatorFeature</code>
 */
class OperatorFeature extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional string Name = 1;</code>
     */
    protected $Name = null;
    /**
     * Generated from protobuf field <code>optional string Description = 2;</code>
     */
    protected $Description = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Name
     *     @type string $Description
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\RoamingOperator::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string Name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return isset($this->Name) ? $this->Name : '';
    }

    public function hasName()
    {
        return isset($this->Name);
    }

    public function clearName()
    {
        unset($this->Name);
    }

    /**
     * Generated from protobuf field <code>optional string Name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->Name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string Description = 2;</code>
     * @return string
     */
    public function getDescription()
    {
        return isset($this->Description) ? $this->Description : '';
    }

    public function hasDescription()
    {
        return isset($this->Description);
    }

    public function clearDescription()
    {
        unset($this->Description);
    }

    /**
     * Generated from protobuf field <code>optional string Description = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->Description = $var;

        return $this;
    }

}

