<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: OrganizationUser.proto

namespace Diadoc\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.OrganizationUser</code>
 */
class OrganizationUser extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional string Id = 1;</code>
     */
    protected $Id = null;
    /**
     * ФИО сотрудника
     *
     * Generated from protobuf field <code>optional string Name = 2;</code>
     */
    protected $Name = null;
    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.OrganizationUserPermissions Permissions = 3;</code>
     */
    protected $Permissions = null;
    /**
     * Generated from protobuf field <code>optional string Position = 4;</code>
     */
    protected $Position = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Id
     *     @type string $Name
     *           ФИО сотрудника
     *     @type \Diadoc\Api\Proto\OrganizationUserPermissions $Permissions
     *     @type string $Position
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\OrganizationUser::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string Id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return isset($this->Id) ? $this->Id : '';
    }

    public function hasId()
    {
        return isset($this->Id);
    }

    public function clearId()
    {
        unset($this->Id);
    }

    /**
     * Generated from protobuf field <code>optional string Id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->Id = $var;

        return $this;
    }

    /**
     * ФИО сотрудника
     *
     * Generated from protobuf field <code>optional string Name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return isset($this->Name) ? $this->Name : '';
    }

    public function hasName()
    {
        return isset($this->Name);
    }

    public function clearName()
    {
        unset($this->Name);
    }

    /**
     * ФИО сотрудника
     *
     * Generated from protobuf field <code>optional string Name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->Name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.OrganizationUserPermissions Permissions = 3;</code>
     * @return \Diadoc\Api\Proto\OrganizationUserPermissions|null
     */
    public function getPermissions()
    {
        return $this->Permissions;
    }

    public function hasPermissions()
    {
        return isset($this->Permissions);
    }

    public function clearPermissions()
    {
        unset($this->Permissions);
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.OrganizationUserPermissions Permissions = 3;</code>
     * @param \Diadoc\Api\Proto\OrganizationUserPermissions $var
     * @return $this
     */
    public function setPermissions($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\OrganizationUserPermissions::class);
        $this->Permissions = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string Position = 4;</code>
     * @return string
     */
    public function getPosition()
    {
        return isset($this->Position) ? $this->Position : '';
    }

    public function hasPosition()
    {
        return isset($this->Position);
    }

    public function clearPosition()
    {
        unset($this->Position);
    }

    /**
     * Generated from protobuf field <code>optional string Position = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPosition($var)
    {
        GPBUtil::checkString($var, True);
        $this->Position = $var;

        return $this;
    }

}

