<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ResolutionRouteList.proto

namespace Diadoc\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.ResolutionRoute</code>
 */
class ResolutionRoute extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional string RouteId = 1;</code>
     */
    protected $RouteId = null;
    /**
     * Generated from protobuf field <code>optional string Name = 2;</code>
     */
    protected $Name = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $RouteId
     *     @type string $Name
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ResolutionRouteList::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string RouteId = 1;</code>
     * @return string
     */
    public function getRouteId()
    {
        return isset($this->RouteId) ? $this->RouteId : '';
    }

    public function hasRouteId()
    {
        return isset($this->RouteId);
    }

    public function clearRouteId()
    {
        unset($this->RouteId);
    }

    /**
     * Generated from protobuf field <code>optional string RouteId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRouteId($var)
    {
        GPBUtil::checkString($var, True);
        $this->RouteId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string Name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return isset($this->Name) ? $this->Name : '';
    }

    public function hasName()
    {
        return isset($this->Name);
    }

    public function clearName()
    {
        unset($this->Name);
    }

    /**
     * Generated from protobuf field <code>optional string Name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->Name = $var;

        return $this;
    }

}

