<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: RoamingOperator.proto

namespace Diadoc\Api\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.RoamingOperator</code>
 */
class RoamingOperator extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional string FnsId = 1;</code>
     */
    protected $FnsId = null;
    /**
     * Generated from protobuf field <code>optional string Name = 2;</code>
     */
    protected $Name = null;
    /**
     * Generated from protobuf field <code>optional bool IsActive = 3;</code>
     */
    protected $IsActive = null;
    /**
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.OperatorFeature Features = 4;</code>
     */
    private $Features;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $FnsId
     *     @type string $Name
     *     @type bool $IsActive
     *     @type array<\Diadoc\Api\Proto\OperatorFeature>|\Google\Protobuf\Internal\RepeatedField $Features
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\RoamingOperator::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string FnsId = 1;</code>
     * @return string
     */
    public function getFnsId()
    {
        return isset($this->FnsId) ? $this->FnsId : '';
    }

    public function hasFnsId()
    {
        return isset($this->FnsId);
    }

    public function clearFnsId()
    {
        unset($this->FnsId);
    }

    /**
     * Generated from protobuf field <code>optional string FnsId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFnsId($var)
    {
        GPBUtil::checkString($var, True);
        $this->FnsId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string Name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return isset($this->Name) ? $this->Name : '';
    }

    public function hasName()
    {
        return isset($this->Name);
    }

    public function clearName()
    {
        unset($this->Name);
    }

    /**
     * Generated from protobuf field <code>optional string Name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->Name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool IsActive = 3;</code>
     * @return bool
     */
    public function getIsActive()
    {
        return isset($this->IsActive) ? $this->IsActive : false;
    }

    public function hasIsActive()
    {
        return isset($this->IsActive);
    }

    public function clearIsActive()
    {
        unset($this->IsActive);
    }

    /**
     * Generated from protobuf field <code>optional bool IsActive = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsActive($var)
    {
        GPBUtil::checkBool($var);
        $this->IsActive = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.OperatorFeature Features = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFeatures()
    {
        return $this->Features;
    }

    /**
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.OperatorFeature Features = 4;</code>
     * @param array<\Diadoc\Api\Proto\OperatorFeature>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFeatures($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Diadoc\Api\Proto\OperatorFeature::class);
        $this->Features = $arr;

        return $this;
    }

}

