<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Address.proto

namespace Diadoc\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.RussianAddress</code>
 */
class RussianAddress extends \Google\Protobuf\Internal\Message
{
    /**
     * индекс
     *
     * Generated from protobuf field <code>optional string ZipCode = 1;</code>
     */
    protected $ZipCode = null;
    /**
     * регион (код)
     *
     * Generated from protobuf field <code>optional string Region = 2;</code>
     */
    protected $Region = null;
    /**
     * район
     *
     * Generated from protobuf field <code>optional string Territory = 3;</code>
     */
    protected $Territory = null;
    /**
     * город
     *
     * Generated from protobuf field <code>optional string City = 4;</code>
     */
    protected $City = null;
    /**
     * населенный пункт
     *
     * Generated from protobuf field <code>optional string Locality = 5;</code>
     */
    protected $Locality = null;
    /**
     * улица
     *
     * Generated from protobuf field <code>optional string Street = 6;</code>
     */
    protected $Street = null;
    /**
     * дом
     *
     * Generated from protobuf field <code>optional string Building = 7;</code>
     */
    protected $Building = null;
    /**
     * корпус
     *
     * Generated from protobuf field <code>optional string Block = 8;</code>
     */
    protected $Block = null;
    /**
     * квартира
     *
     * Generated from protobuf field <code>optional string Apartment = 9;</code>
     */
    protected $Apartment = null;
    /**
     * иные сведения
     *
     * Generated from protobuf field <code>optional string OtherInformation = 10;</code>
     */
    protected $OtherInformation = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $ZipCode
     *           индекс
     *     @type string $Region
     *           регион (код)
     *     @type string $Territory
     *           район
     *     @type string $City
     *           город
     *     @type string $Locality
     *           населенный пункт
     *     @type string $Street
     *           улица
     *     @type string $Building
     *           дом
     *     @type string $Block
     *           корпус
     *     @type string $Apartment
     *           квартира
     *     @type string $OtherInformation
     *           иные сведения
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Address::initOnce();
        parent::__construct($data);
    }

    /**
     * индекс
     *
     * Generated from protobuf field <code>optional string ZipCode = 1;</code>
     * @return string
     */
    public function getZipCode()
    {
        return isset($this->ZipCode) ? $this->ZipCode : '';
    }

    public function hasZipCode()
    {
        return isset($this->ZipCode);
    }

    public function clearZipCode()
    {
        unset($this->ZipCode);
    }

    /**
     * индекс
     *
     * Generated from protobuf field <code>optional string ZipCode = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setZipCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->ZipCode = $var;

        return $this;
    }

    /**
     * регион (код)
     *
     * Generated from protobuf field <code>optional string Region = 2;</code>
     * @return string
     */
    public function getRegion()
    {
        return isset($this->Region) ? $this->Region : '';
    }

    public function hasRegion()
    {
        return isset($this->Region);
    }

    public function clearRegion()
    {
        unset($this->Region);
    }

    /**
     * регион (код)
     *
     * Generated from protobuf field <code>optional string Region = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRegion($var)
    {
        GPBUtil::checkString($var, True);
        $this->Region = $var;

        return $this;
    }

    /**
     * район
     *
     * Generated from protobuf field <code>optional string Territory = 3;</code>
     * @return string
     */
    public function getTerritory()
    {
        return isset($this->Territory) ? $this->Territory : '';
    }

    public function hasTerritory()
    {
        return isset($this->Territory);
    }

    public function clearTerritory()
    {
        unset($this->Territory);
    }

    /**
     * район
     *
     * Generated from protobuf field <code>optional string Territory = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setTerritory($var)
    {
        GPBUtil::checkString($var, True);
        $this->Territory = $var;

        return $this;
    }

    /**
     * город
     *
     * Generated from protobuf field <code>optional string City = 4;</code>
     * @return string
     */
    public function getCity()
    {
        return isset($this->City) ? $this->City : '';
    }

    public function hasCity()
    {
        return isset($this->City);
    }

    public function clearCity()
    {
        unset($this->City);
    }

    /**
     * город
     *
     * Generated from protobuf field <code>optional string City = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCity($var)
    {
        GPBUtil::checkString($var, True);
        $this->City = $var;

        return $this;
    }

    /**
     * населенный пункт
     *
     * Generated from protobuf field <code>optional string Locality = 5;</code>
     * @return string
     */
    public function getLocality()
    {
        return isset($this->Locality) ? $this->Locality : '';
    }

    public function hasLocality()
    {
        return isset($this->Locality);
    }

    public function clearLocality()
    {
        unset($this->Locality);
    }

    /**
     * населенный пункт
     *
     * Generated from protobuf field <code>optional string Locality = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setLocality($var)
    {
        GPBUtil::checkString($var, True);
        $this->Locality = $var;

        return $this;
    }

    /**
     * улица
     *
     * Generated from protobuf field <code>optional string Street = 6;</code>
     * @return string
     */
    public function getStreet()
    {
        return isset($this->Street) ? $this->Street : '';
    }

    public function hasStreet()
    {
        return isset($this->Street);
    }

    public function clearStreet()
    {
        unset($this->Street);
    }

    /**
     * улица
     *
     * Generated from protobuf field <code>optional string Street = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setStreet($var)
    {
        GPBUtil::checkString($var, True);
        $this->Street = $var;

        return $this;
    }

    /**
     * дом
     *
     * Generated from protobuf field <code>optional string Building = 7;</code>
     * @return string
     */
    public function getBuilding()
    {
        return isset($this->Building) ? $this->Building : '';
    }

    public function hasBuilding()
    {
        return isset($this->Building);
    }

    public function clearBuilding()
    {
        unset($this->Building);
    }

    /**
     * дом
     *
     * Generated from protobuf field <code>optional string Building = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setBuilding($var)
    {
        GPBUtil::checkString($var, True);
        $this->Building = $var;

        return $this;
    }

    /**
     * корпус
     *
     * Generated from protobuf field <code>optional string Block = 8;</code>
     * @return string
     */
    public function getBlock()
    {
        return isset($this->Block) ? $this->Block : '';
    }

    public function hasBlock()
    {
        return isset($this->Block);
    }

    public function clearBlock()
    {
        unset($this->Block);
    }

    /**
     * корпус
     *
     * Generated from protobuf field <code>optional string Block = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setBlock($var)
    {
        GPBUtil::checkString($var, True);
        $this->Block = $var;

        return $this;
    }

    /**
     * квартира
     *
     * Generated from protobuf field <code>optional string Apartment = 9;</code>
     * @return string
     */
    public function getApartment()
    {
        return isset($this->Apartment) ? $this->Apartment : '';
    }

    public function hasApartment()
    {
        return isset($this->Apartment);
    }

    public function clearApartment()
    {
        unset($this->Apartment);
    }

    /**
     * квартира
     *
     * Generated from protobuf field <code>optional string Apartment = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setApartment($var)
    {
        GPBUtil::checkString($var, True);
        $this->Apartment = $var;

        return $this;
    }

    /**
     * иные сведения
     *
     * Generated from protobuf field <code>optional string OtherInformation = 10;</code>
     * @return string
     */
    public function getOtherInformation()
    {
        return isset($this->OtherInformation) ? $this->OtherInformation : '';
    }

    public function hasOtherInformation()
    {
        return isset($this->OtherInformation);
    }

    public function clearOtherInformation()
    {
        unset($this->OtherInformation);
    }

    /**
     * иные сведения
     *
     * Generated from protobuf field <code>optional string OtherInformation = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setOtherInformation($var)
    {
        GPBUtil::checkString($var, True);
        $this->OtherInformation = $var;

        return $this;
    }

}

