<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Docflow/DocflowV3.proto

namespace Diadoc\Api\Proto\Docflow;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.Docflow.AmendmentRequestDocflow</code>
 */
class AmendmentRequestDocflow extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional bool IsFinished = 1;</code>
     */
    protected $IsFinished = null;
    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Docflow.SignedAttachmentV3 AmendmentRequest = 2;</code>
     */
    protected $AmendmentRequest = null;
    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Timestamp SentAt = 3;</code>
     */
    protected $SentAt = null;
    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Timestamp DeliveredAt = 4;</code>
     */
    protected $DeliveredAt = null;
    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Docflow.ReceiptDocflowV3 Receipt = 5;</code>
     */
    protected $Receipt = null;
    /**
     * Generated from protobuf field <code>optional int32 AmendmentFlags = 6;</code>
     */
    protected $AmendmentFlags = null;
    /**
     * Generated from protobuf field <code>optional string PlainText = 7;</code>
     */
    protected $PlainText = null;
    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Docflow.ConfirmationDocflow ConfirmationDocflow = 8;</code>
     */
    protected $ConfirmationDocflow = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $IsFinished
     *     @type \Diadoc\Api\Proto\Docflow\SignedAttachmentV3 $AmendmentRequest
     *     @type \Diadoc\Api\Proto\Timestamp $SentAt
     *     @type \Diadoc\Api\Proto\Timestamp $DeliveredAt
     *     @type \Diadoc\Api\Proto\Docflow\ReceiptDocflowV3 $Receipt
     *     @type int $AmendmentFlags
     *     @type string $PlainText
     *     @type \Diadoc\Api\Proto\Docflow\ConfirmationDocflow $ConfirmationDocflow
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Docflow\DocflowV3::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional bool IsFinished = 1;</code>
     * @return bool
     */
    public function getIsFinished()
    {
        return isset($this->IsFinished) ? $this->IsFinished : false;
    }

    public function hasIsFinished()
    {
        return isset($this->IsFinished);
    }

    public function clearIsFinished()
    {
        unset($this->IsFinished);
    }

    /**
     * Generated from protobuf field <code>optional bool IsFinished = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsFinished($var)
    {
        GPBUtil::checkBool($var);
        $this->IsFinished = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Docflow.SignedAttachmentV3 AmendmentRequest = 2;</code>
     * @return \Diadoc\Api\Proto\Docflow\SignedAttachmentV3|null
     */
    public function getAmendmentRequest()
    {
        return $this->AmendmentRequest;
    }

    public function hasAmendmentRequest()
    {
        return isset($this->AmendmentRequest);
    }

    public function clearAmendmentRequest()
    {
        unset($this->AmendmentRequest);
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Docflow.SignedAttachmentV3 AmendmentRequest = 2;</code>
     * @param \Diadoc\Api\Proto\Docflow\SignedAttachmentV3 $var
     * @return $this
     */
    public function setAmendmentRequest($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\Docflow\SignedAttachmentV3::class);
        $this->AmendmentRequest = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Timestamp SentAt = 3;</code>
     * @return \Diadoc\Api\Proto\Timestamp|null
     */
    public function getSentAt()
    {
        return $this->SentAt;
    }

    public function hasSentAt()
    {
        return isset($this->SentAt);
    }

    public function clearSentAt()
    {
        unset($this->SentAt);
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Timestamp SentAt = 3;</code>
     * @param \Diadoc\Api\Proto\Timestamp $var
     * @return $this
     */
    public function setSentAt($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\Timestamp::class);
        $this->SentAt = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Timestamp DeliveredAt = 4;</code>
     * @return \Diadoc\Api\Proto\Timestamp|null
     */
    public function getDeliveredAt()
    {
        return $this->DeliveredAt;
    }

    public function hasDeliveredAt()
    {
        return isset($this->DeliveredAt);
    }

    public function clearDeliveredAt()
    {
        unset($this->DeliveredAt);
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Timestamp DeliveredAt = 4;</code>
     * @param \Diadoc\Api\Proto\Timestamp $var
     * @return $this
     */
    public function setDeliveredAt($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\Timestamp::class);
        $this->DeliveredAt = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Docflow.ReceiptDocflowV3 Receipt = 5;</code>
     * @return \Diadoc\Api\Proto\Docflow\ReceiptDocflowV3|null
     */
    public function getReceipt()
    {
        return $this->Receipt;
    }

    public function hasReceipt()
    {
        return isset($this->Receipt);
    }

    public function clearReceipt()
    {
        unset($this->Receipt);
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Docflow.ReceiptDocflowV3 Receipt = 5;</code>
     * @param \Diadoc\Api\Proto\Docflow\ReceiptDocflowV3 $var
     * @return $this
     */
    public function setReceipt($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\Docflow\ReceiptDocflowV3::class);
        $this->Receipt = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 AmendmentFlags = 6;</code>
     * @return int
     */
    public function getAmendmentFlags()
    {
        return isset($this->AmendmentFlags) ? $this->AmendmentFlags : 0;
    }

    public function hasAmendmentFlags()
    {
        return isset($this->AmendmentFlags);
    }

    public function clearAmendmentFlags()
    {
        unset($this->AmendmentFlags);
    }

    /**
     * Generated from protobuf field <code>optional int32 AmendmentFlags = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setAmendmentFlags($var)
    {
        GPBUtil::checkInt32($var);
        $this->AmendmentFlags = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string PlainText = 7;</code>
     * @return string
     */
    public function getPlainText()
    {
        return isset($this->PlainText) ? $this->PlainText : '';
    }

    public function hasPlainText()
    {
        return isset($this->PlainText);
    }

    public function clearPlainText()
    {
        unset($this->PlainText);
    }

    /**
     * Generated from protobuf field <code>optional string PlainText = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setPlainText($var)
    {
        GPBUtil::checkString($var, True);
        $this->PlainText = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Docflow.ConfirmationDocflow ConfirmationDocflow = 8;</code>
     * @return \Diadoc\Api\Proto\Docflow\ConfirmationDocflow|null
     */
    public function getConfirmationDocflow()
    {
        return $this->ConfirmationDocflow;
    }

    public function hasConfirmationDocflow()
    {
        return isset($this->ConfirmationDocflow);
    }

    public function clearConfirmationDocflow()
    {
        unset($this->ConfirmationDocflow);
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Docflow.ConfirmationDocflow ConfirmationDocflow = 8;</code>
     * @param \Diadoc\Api\Proto\Docflow\ConfirmationDocflow $var
     * @return $this
     */
    public function setConfirmationDocflow($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\Docflow\ConfirmationDocflow::class);
        $this->ConfirmationDocflow = $var;

        return $this;
    }

}

