<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Docflow/DocumentInfoV3.proto

namespace Diadoc\Proto\Docflow;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.Docflow.DocumentDraftInfo</code>
 */
class DocumentDraftInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional bool IsRecycled = 1;</code>
     */
    protected $IsRecycled = null;
    /**
     * Generated from protobuf field <code>optional bool IsLocked = 2;</code>
     */
    protected $IsLocked = null;
    /**
     * Generated from protobuf field <code>repeated string TransformedToLetterIds = 3;</code>
     */
    private $TransformedToLetterIds;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $IsRecycled
     *     @type bool $IsLocked
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $TransformedToLetterIds
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Docflow\DocumentInfoV3::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional bool IsRecycled = 1;</code>
     * @return bool
     */
    public function getIsRecycled()
    {
        return isset($this->IsRecycled) ? $this->IsRecycled : false;
    }

    public function hasIsRecycled()
    {
        return isset($this->IsRecycled);
    }

    public function clearIsRecycled()
    {
        unset($this->IsRecycled);
    }

    /**
     * Generated from protobuf field <code>optional bool IsRecycled = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsRecycled($var)
    {
        GPBUtil::checkBool($var);
        $this->IsRecycled = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool IsLocked = 2;</code>
     * @return bool
     */
    public function getIsLocked()
    {
        return isset($this->IsLocked) ? $this->IsLocked : false;
    }

    public function hasIsLocked()
    {
        return isset($this->IsLocked);
    }

    public function clearIsLocked()
    {
        unset($this->IsLocked);
    }

    /**
     * Generated from protobuf field <code>optional bool IsLocked = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsLocked($var)
    {
        GPBUtil::checkBool($var);
        $this->IsLocked = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string TransformedToLetterIds = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTransformedToLetterIds()
    {
        return $this->TransformedToLetterIds;
    }

    /**
     * Generated from protobuf field <code>repeated string TransformedToLetterIds = 3;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTransformedToLetterIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->TransformedToLetterIds = $arr;

        return $this;
    }

}

