<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Docflow/DocumentInfoV3.proto

namespace Diadoc\Proto\Docflow;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.Docflow.DocumentLetterInfo</code>
 */
class DocumentLetterInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional bool IsEncrypted = 1;</code>
     */
    protected $IsEncrypted = null;
    /**
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.ForwardDocumentEvent ForwardDocumentEvents = 2;</code>
     */
    private $ForwardDocumentEvents;
    /**
     * Generated from protobuf field <code>optional bool IsTest = 3;</code>
     */
    protected $IsTest = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $IsEncrypted
     *     @type array<\Diadoc\Api\Proto\ForwardDocumentEvent>|\Google\Protobuf\Internal\RepeatedField $ForwardDocumentEvents
     *     @type bool $IsTest
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Docflow\DocumentInfoV3::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional bool IsEncrypted = 1;</code>
     * @return bool
     */
    public function getIsEncrypted()
    {
        return isset($this->IsEncrypted) ? $this->IsEncrypted : false;
    }

    public function hasIsEncrypted()
    {
        return isset($this->IsEncrypted);
    }

    public function clearIsEncrypted()
    {
        unset($this->IsEncrypted);
    }

    /**
     * Generated from protobuf field <code>optional bool IsEncrypted = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsEncrypted($var)
    {
        GPBUtil::checkBool($var);
        $this->IsEncrypted = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.ForwardDocumentEvent ForwardDocumentEvents = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getForwardDocumentEvents()
    {
        return $this->ForwardDocumentEvents;
    }

    /**
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.ForwardDocumentEvent ForwardDocumentEvents = 2;</code>
     * @param array<\Diadoc\Api\Proto\ForwardDocumentEvent>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setForwardDocumentEvents($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Diadoc\Api\Proto\ForwardDocumentEvent::class);
        $this->ForwardDocumentEvents = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool IsTest = 3;</code>
     * @return bool
     */
    public function getIsTest()
    {
        return isset($this->IsTest) ? $this->IsTest : false;
    }

    public function hasIsTest()
    {
        return isset($this->IsTest);
    }

    public function clearIsTest()
    {
        unset($this->IsTest);
    }

    /**
     * Generated from protobuf field <code>optional bool IsTest = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsTest($var)
    {
        GPBUtil::checkBool($var);
        $this->IsTest = $var;

        return $this;
    }

}

