<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Docflow/DocumentWithDocflowV3.proto

namespace Diadoc\Proto\Docflow;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.Docflow.LastEvent</code>
 */
class LastEvent extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional string EventId = 1;</code>
     */
    protected $EventId = null;
    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Timestamp Timestamp = 2;</code>
     */
    protected $Timestamp = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $EventId
     *     @type \Diadoc\Api\Proto\Timestamp $Timestamp
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Docflow\DocumentWithDocflowV3::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string EventId = 1;</code>
     * @return string
     */
    public function getEventId()
    {
        return isset($this->EventId) ? $this->EventId : '';
    }

    public function hasEventId()
    {
        return isset($this->EventId);
    }

    public function clearEventId()
    {
        unset($this->EventId);
    }

    /**
     * Generated from protobuf field <code>optional string EventId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setEventId($var)
    {
        GPBUtil::checkString($var, True);
        $this->EventId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Timestamp Timestamp = 2;</code>
     * @return \Diadoc\Api\Proto\Timestamp|null
     */
    public function getTimestamp()
    {
        return $this->Timestamp;
    }

    public function hasTimestamp()
    {
        return isset($this->Timestamp);
    }

    public function clearTimestamp()
    {
        unset($this->Timestamp);
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Timestamp Timestamp = 2;</code>
     * @param \Diadoc\Api\Proto\Timestamp $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\Timestamp::class);
        $this->Timestamp = $var;

        return $this;
    }

}

