<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Docflow/RoamingNotification.proto

namespace Diadoc\Proto\Docflow;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.Docflow.RoamingNotification</code>
 */
class RoamingNotification extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Docflow.Entity Notification = 1;</code>
     */
    protected $Notification = null;
    /**
     * Generated from protobuf field <code>optional bool IsSuccess = 2;</code>
     */
    protected $IsSuccess = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Diadoc\Api\Proto\Docflow\Entity $Notification
     *     @type bool $IsSuccess
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Docflow\RoamingNotification::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Docflow.Entity Notification = 1;</code>
     * @return \Diadoc\Api\Proto\Docflow\Entity|null
     */
    public function getNotification()
    {
        return $this->Notification;
    }

    public function hasNotification()
    {
        return isset($this->Notification);
    }

    public function clearNotification()
    {
        unset($this->Notification);
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Docflow.Entity Notification = 1;</code>
     * @param \Diadoc\Api\Proto\Docflow\Entity $var
     * @return $this
     */
    public function setNotification($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\Docflow\Entity::class);
        $this->Notification = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool IsSuccess = 2;</code>
     * @return bool
     */
    public function getIsSuccess()
    {
        return isset($this->IsSuccess) ? $this->IsSuccess : false;
    }

    public function hasIsSuccess()
    {
        return isset($this->IsSuccess);
    }

    public function clearIsSuccess()
    {
        unset($this->IsSuccess);
    }

    /**
     * Generated from protobuf field <code>optional bool IsSuccess = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsSuccess($var)
    {
        GPBUtil::checkBool($var);
        $this->IsSuccess = $var;

        return $this;
    }

}

